import { HostInfo } from '@type/host-info';

/**
 * Request interface for adding a new host.
 *
 * Contains host information without UID (which will be generated by the server).
 *
 * @category Requests
 * @since 1.0.0
 */
export type AddHostRequest = Omit<HostInfo, 'uid' | 'dbProfiles' | 'token' | 'initialLogin'>;
