/**
 * UI labels aligned with CUBRID Manager (Admin) RCP.
 * Source: cubrid-manager .../cubrid/database/Messages.properties, spi/Messages.properties, common/Messages.properties
 *
 * Static English export — use useCM() in components for locale-aware labels.
 */
export const CM = {
  ok: 'OK',
  cancel: 'Cancel',
  close: 'Close',
  refresh: 'Refresh',
  confirm: 'Confirm',
  error: 'Error',
  warning: 'Warning',
  success: 'Success',
  failure: 'Failure',

  loginDatabase: 'Login Database',
  loginDatabaseMsg: 'Log into the selected database.',
  loggingInto: (db) => `Logging into "${db}" database...`,
  connectionSuccessful: 'The connection was successful.',
  userName: 'User name',
  password: 'Password',
  databaseName: 'Database name',
  savePassword: 'Save Password',

  transactionInformation: 'Transaction information',
  activeTransactionsOf: 'Active transactions of database:',
  tranIndex: 'Tran index',
  userNameCol: 'User name',
  host: 'Host',
  processId: 'Process id',
  programName: 'Program name',
  killTransaction: 'Kill transaction',
  killTransactionTitle: 'Kill Transaction',
  killType: 'Kill type',
  killSelectedOnly: 'Kill the selected transaction only',
  killSameUser: 'Kill all transactions associated with the same user',
  killSameHost: 'Kill all transactions associated with the same client host',
  killSameProgram: 'Kill all transactions associated with the same program name',
  killSuccess: 'Transaction has been successfully killed.',

  lockingInformation: 'Locking Information',
  lockSettingClientInfo: 'Lock setting/client information',
  objectLockTable: 'Object lock table',
  lockAndTransaction: 'Lock and Transaction',
  loadingLockAndTransaction: 'Loading lock and transaction information...',
  lockIndex: 'Index',
  pname: 'Pname',
  uid: 'Uid',
  pid: 'Pid',
  isolationLevel: 'Isolation level',
  timeOut: 'Time out',
  oid: 'Oid',
  objectType: 'Object type',
  mode: 'Mode',
  numHolders: 'Num holders',
  numBlockedHolders: 'Num blocked holders',
  numWaiters: 'Num waiters',
  lockEscalation: 'Lock escalation',
  runDeadlockInterval: 'Run deadlock interval',
  currentLockedObjNum: 'Current number of objects which are locked',
  maxLockedObjNum: 'Maximum number of objects which can be locked',

  checkDatabase: 'Check Database',
  checkDatabaseDesc:
    'Verifies a database. If inconsistencies are found, please contact CUBRID Support to help interpret the output and address any indicated problem so that it will not reoccur.',
  repairWhenInconsistency: 'Repair when inconsistency is found',
  jobCompletedSuccess: (job) => `Job ${job} has been completed successfully`,

  createDatabase: 'Create Database',
  deleteDatabase: 'Delete Database',
  deleteDatabaseConfirm: 'Are you sure you want to delete this database?',
  backupDatabase: 'Backup Database',
  restoreDatabase: 'Restore Database',
  compactDatabase: 'Compact Database',
  optimizeDatabase: 'Optimize Database',
  copyDatabase: 'Copy Database',
  renameDatabase: 'Rename Database',
  loadDatabase: 'Load Database',
  unloadDatabase: 'Unload Database',
  dbaConfirm: 'DBA confirm',
  dbaPassword: 'DBA password',

  manageDatabase: 'Manage Database',
  databaseInfo: 'Database Info',
  usedParameterDump: 'Used Parameter Dump',
  planCacheDump: 'Plan Cache Dump',

  manageDatabaseMenu: {
    unload: 'Unload Database...',
    load: 'Load Database...',
    create: 'Create Database...',
    check: 'Check Database',
    compact: 'Compact Database',
    optimize: 'Optimize Database',
    copy: 'Copy Database',
    rename: 'Rename Database',
    restore: 'Restore Database',
    backup: 'Backup Database',
    delete: 'Delete Database',
  },

  // Create Database (createdb wizard)
  createDatabaseMsg: 'Create a new database.',
  createDbJobComplete: (job) => `Job ${job} has been completed.`,
  createDbFailed: 'Failed to start the database. Please verify that the connection credentials are correct.',
  wizardGeneral: 'General Information',
  wizardAdditionalVol: 'Additional Volume Information',
  wizardAutoVol: 'Automatic volume extension',
  wizardSetDbaPass: 'Set DBA Password',
  wizardDbInfo: 'Database Information',
  wizardDbInfoList:
    'You have completed the steps required to create a new database. The new database will be created according to the below preferences.',
  pageSize: 'Page size (byte)',
  logPageSize: 'Log page size (byte)',
  localeCharset: 'Charset',
  userDefined: 'User Defined',
  volumeSize: 'Volume size (Mbyte)',
  genericVolInfo: 'Generic Volume Information',
  genericVolPath: 'Generic volume path',
  logVolInfo: 'Log Volume Information',
  logVolPath: 'Log volume path',
  volumeName: 'Volume name',
  volumePath: 'Volume path',
  volumeType: 'Volume type',
  autoStartDb: 'Auto start database when start the cubrid service',
  passwordConfirm: 'Password Confirm',
  setPassword: 'Set Password',
  readyToCreate: 'Ready to create',
  back: 'Back',
  next: 'Next',
  finish: 'Finish',

  // Unload Database (unloaddb)
  unloadDatabaseMsg: 'Unload the selected database.',
  unloadSuccess: 'The database have been unloaded successfully.',
  unloadResultTitle: 'Unload Database Result',
  unloadResultMsg: 'Below you can view the unload database result informaton.',
  grpDbInfo: 'Database Information',
  targetDbName: 'Target database name',
  targetDirectory: 'Target directory',
  unloadTarget: 'Unload Target',
  unloadOption: 'Unload Option',
  schema: 'Schema',
  data: 'Data',
  all: 'All',
  selectedTables: 'Selected tables',
  notInclude: 'Not include',
  useDelimitedIdentifier: 'Use delimited identifier ("")',
  includeReferencedTables: 'Include referenced tables',
  prefixOutputFiles: 'Prefix for output files',
  fileForHash: 'File for hash',
  numCachedPages: 'Number of cached pages',
  estimatedInstances: 'Estimated number of instances',
  loFileCountPerDir: 'Lo file count per a directory',
  availableClasses: 'Available Classes',

  // Load Database (loaddb)
  loadDatabaseMsg: 'Load the selected database.',
  loadResultTitle: 'Load Database Result',
  loadResultMsg: 'Below you can view the load database result information.',
  unloadedFiles: 'Unloaded Files',
  loadType: 'Load Type',
  path: 'Path',
  date: 'Date',
  selectFromList: 'Select unloaded file from list',
  selectFromRemote: 'Select unloaded file from remote system',
  selectFromLocal: 'Select unloaded file from local system',
  loadOption: 'Load Option',
  loadSchema: 'Load schema',
  loadObject: 'Load object',
  loadIndex: 'Load index',
  loadTrigger: 'Load trigger',
  checkSyntaxAndLoad: 'Check syntax and load database',
  insertionCountPeriodicCommit: 'Insertion count for periodic commit',
  dontUseOid: "Don't use OID",
  dontUpdateStatistics: "Don't update statistics",
  usingErrorControlFile: 'Using error control file',
  ignoredTableFile: 'Ignored table file',
  loadDbTask: 'Load Database',

  // Common actions
  save: 'Save',
  retry: 'Retry',
  dismiss: 'Dismiss',
  apply: 'Apply',
  discard: 'Discard',
  connect: 'Connect',
  loginAll: 'Login All',
  disconnect: 'Disconnect',
  tryAgain: 'Try Again',
  add: 'Add',
  edit: 'Edit',
  remove: 'Remove',
  startLabel: 'Start',
  stopLabel: 'Stop',
  restart: 'Restart',
  processing: 'Running...',
  pleaseWait: 'Please wait...',
  selectAll: 'Select All',
  name: 'Name',
  address: 'Address',
  port: 'Port',
  status: 'Status',
  type: 'Type',
  value: 'Value',
  actions: 'Actions',
  live: 'Live',
  paused: 'Paused',
  identity: 'Identity',
  credentials: 'Credentials',
  username: 'Username',
  newPassword: 'New Password',
  leaveBlankToKeep: 'Leave blank to keep current password',
  passwordsDoNotMatch: 'Passwords do not match',
  hostNameRequired: 'Host name is required',
  addressRequired: 'Address is required',
  portRequired: 'Port is required',
  usernameRequired: 'Username is required',
  passwordRequired: 'Password is required',

  // App / tabs / loading
  appName: 'CUBRID Manager',
  selectHostHint: 'Select a host from the sidebar to start monitoring databases, brokers, and logs.',
  hostManagement: 'Host Management',
  volumeMonitor: 'Volume Monitor',
  performance: 'Performance',
  lockInfo: 'Lock Info',
  systemReady: 'System Ready',
  managerAccess: 'Manager Access',
  managerError: 'Manager Error',
  brokerStatus: 'Broker Status',
  processingDbRequest: 'Processing database request...',
  processingRequest: 'Processing your request, please wait...',
  cmsJobRunningInBackground: (target, statusHint = '') =>
    `${target}${statusHint} — running in background`,
  backgroundJobsTitle: 'Background jobs',
  backgroundJobsRunning: (n) => `${n} running`,
  backgroundJobsEmpty: 'No background jobs',
  clearCompletedJobs: 'Clear completed',
  jobStatusQueued: 'Queued',
  jobStatusRunning: 'Running',
  jobStatusSucceeded: 'Completed',
  jobStatusFailed: 'Failed',
  jobNotifySucceeded: (op, db) => `${op} completed — ${db}`,
  jobNotifyFailed: (op, db) => `${op} failed — ${db}`,
  jobTypeUnload: 'Unload',
  jobTypeLoad: 'Load',
  jobTypeCreate: 'Create database',
  jobTypeOptimize: 'Optimize',
  jobTypeCheck: 'Check',
  jobTypeCompact: 'Compact',
  jobTypeCopy: 'Copy',
  jobTypeAddVol: 'Add volume',
  jobTypeRename: 'Rename',
  databaseAction: 'Database Action',
  brokerAction: 'Broker Action',
  actionFailed: 'Action Failed',
  updateFailed: 'Update Failed',
  updateInterrupted: 'Update Interrupted',
  applyingChanges: 'Applying Changes...',
  startingDatabase: (db) => `Starting database: ${db}`,
  startingBroker: (b) => `Starting broker: ${b}`,
  startingService: 'Starting Service',
  stoppingService: 'Stopping Service',
  startingDbNamed: (db) => `Starting database : ${db}`,
  stoppingDbNamed: (db) => `Stopping database : ${db}`,
  startingBrokerNamed: (b) => `Starting Broker: ${b}`,
  stoppingBrokerNamed: (b) => `Stopping Broker: ${b}`,
  startBrokerLine: (name) => `Start broker : ${name}`,
  stopBrokerLine: (name) => `Stop broker : ${name}`,
  serviceStartWait: 'Please wait while we start all brokers and databases...',
  serviceStopWait: 'Please wait while we stop all brokers and databases...',
  editConfigTab: (name) => `Edit ${name}`,
  allLogsTab: (name) => `All Logs: ${name}`,
  allServerLogsTab: (name) => `All Server Logs: ${name}`,
  statusTab: (name) => `Status: ${name}`,
  spaceTab: (db) => `Space: ${db}`,
  volumeTab: (path) => `Volume: ${path}`,
  volumesTab: (cat) => `Volumes: ${cat.replace(/_/g, ' ')}`,
  brokerConfig: 'Broker Config',
  serviceDashboard: 'Service Dashboard',

  // Header / menus
  file: 'File',
  view: 'View',
  service: 'Service',
  database: 'Database',
  broker: 'Broker',
  addHost: 'Add Host',
  changeHost: 'Change Host',
  exportHost: 'Export Host',
  importHost: 'Import Host',
  exportHosts: 'Export Hosts',
  importHosts: 'Import Hosts',
  importHostsXml: 'Import Hosts XML',
  tools: 'Tools',
  hostServiceManagement: 'Host Service Management',
  help: 'Help',
  aboutCubridAdmin: 'About CUBRID Admin',
  aboutCubrid: 'About CUBRID',
  cubridWebManager: 'CUBRID Web Manager',
  systemDetails: 'System Details',
  coreVersion: 'Core Version',
  certifiedStable: 'Certified Stable',
  startService: 'Start Service',
  stopService: 'Stop Service',
  startStopService: 'Start/Stop Service',
  startStopDatabase: 'Start/Stop Database',
  startStopBroker: 'Start/Stop Broker',
  editCubridConfig: 'Edit Cubrid Config',
  logout: 'Logout',
  startSelectedDbBroker: 'Start selected database / broker',
  switchToDarkMode: 'Switch to dark mode',
  switchToLightMode: 'Switch to light mode',

  // Sidebar
  addYourFirstHost: 'Add your first host',
  connectToCubridServer: 'Connect to a CUBRID server',
  hostLogin: 'Host login',
  establishingSession: 'Establishing secure session...',
  connectionFailed: 'Connection failed',
  editHost: 'Edit Host',
  deleteHost: 'Delete Host',
  changePassword: 'Change Password',
  userManagement: 'User Management',
  cmsAccountManagement: 'CMS Account Management',
  serverVersion: 'Server Version',
  serverColon: (s) => `Server: ${s}`,
  databaseColon: (db) => `Database: ${db}`,
  allDatabases: 'All Databases',
  allBrokers: 'All Brokers',
  brokerColon: (b) => `Broker: ${b}`,
  startDatabase: 'Start Database',
  stopDatabase: 'Stop Database',
  startAllDatabases: 'Start All Databases',
  stopAllDatabases: 'Stop All Databases',
  restartAllDatabases: 'Restart All Databases',
  startAllBrokers: 'Start All Brokers',
  stopAllBrokers: 'Stop All Brokers',
  restartAllBrokers: 'Restart All Brokers',
  editBrokerConfig: 'Edit Broker Config',
  showStatus: 'Show Status',
  startBroker: 'Start Broker',
  stopBroker: 'Stop Broker',
  paramDump: 'Param Dump...',
  planDump: 'Plan Dump...',
  properties: 'Properties',
  databaseInfoMenu: 'Database Info',

  // Sidebar tree
  users: 'Users',
  jobAutomation: 'Job automation',
  backupPlan: 'Backup Plan',
  queryPlan: 'Query Plan',
  space: 'Space',
  log: 'Log',
  access: 'Access',
  adminLog: 'Admin Log',
  manager: 'Manager',
  accessLog: 'Access log',
  errorLog: 'Error log',
  serverLogs: 'Server logs',
  sqlLog: 'SQL Log',
  noHostSelectedTitle: 'No Host Selected',
  selectServerFromList: 'Select a server from the list above to view details.',
  serverListAbove: 'Server list above',
  admin: 'Admin',
  managerConsole: 'Manager Console',

  // Breadcrumb / footer
  closeTab: 'Close Tab',
  closeOtherTabs: 'Close Other Tabs',
  closeAllTabs: 'Close All Tabs',
  reloadTab: 'Reload Tab',
  connectedTo: (host) => `Connected to ${host}`,
  noHostSelected: 'No host selected',
  version: 'Version',

  // Host modals
  newConnection: 'New Connection',
  friendlyName: 'Friendly Name',
  ipAddressDomain: 'IP Address / Domain',
  modifyHost: 'Modify Host',
  removeHostConnection: 'Remove Host Connection',
  keepHost: 'Keep Host',
  confirmRemoval: 'Confirm Removal',
  activeConnectionsTerminated: 'Active connections to this host will be terminated.',
  changeManagerPasscode: 'Change Manager Passcode',
  newPasscode: 'New Passcode',
  verifyNewPasscode: 'Verify New Passcode',
  cubridVersion: 'CUBRID Version',
  environmentDetails: 'Environment Details',
  osPlatform: 'OS Platform',
  installPath: 'Install Path',
  haPeersDiscovered: 'HA Peers Discovered',
  peerNodes: 'Peer Nodes',
  editUser: 'Edit user',
  deleteUser: 'Delete user',
  addUser: 'Add User',
  fullSystemAuth: 'Full system authorization',
  primaryAdminCannotDelete: 'The primary administrator account cannot be deleted.',
  noAccess: 'No Access',
  monitorOnly: 'Monitor Only',
  fullControl: 'Full Control',
  permissions: 'Permissions',
  brokerAuthority: 'Broker Authority',
  monitoringPermission: 'monitoring',
  dbCreatePermission: 'db-creation',
  brokerPermission: 'broker',

  // Server dashboard
  serverDashboard: 'Server Dashboard',
  refreshDashboard: 'Refresh dashboard',
  syncedAt: (t) => `Synced ${t}`,
  databases: 'Databases',
  autoStartup: 'Auto Startup',
  systemStatusError: 'System Status Error',
  period: 'Period',
  memory: 'Memory',
  disk: 'Disk',
  cpu: 'CPU',
  tps: 'TPS',
  qps: 'QPS',
  accessPoint: 'Access Point',
  authUser: 'Auth User',
  operatingSystem: 'Operating System',
  cubridEngine: 'CUBRID Engine',
  homeDirectory: 'Home Directory',
  permanent: 'Permanent',
  temporary: 'Temporary',
  freeStorage: 'Free Storage',
  refreshBrokersList: 'Refresh brokers list',
  startServices: 'Start Services',
  stopAllServices: 'Stop All Services',
  sensorsOffline: 'Sensors Offline',
  serviceError: 'Service Error',
  groupHost: 'GROUP/HOST',
  dbStatus: 'DB STATUS',
  undoChanges: 'Undo changes',
  saveChanges: 'Save changes',
  reloadConfig: 'Reload config',
  modified: 'Modified',
  sourceEditor: 'Source Editor',
  configPlaceholder: '# Configuration content...',
  tableEditor: 'Table Editor',

  // Auth
  signIn: 'Sign In',
  authorizeAccess: 'Authorize Access',
  rememberDevice: 'Remember this device',
  authenticationFailed: 'Authentication Failed',
  createAccount: 'Create Account',
  backToLogin: 'Back to Login',
  accountRecovery: 'Account Recovery',
  resetCredentials: 'Reset your access credentials.',
  registrationFailed: 'Registration failed. Please try again.',
  passwordStrengthWeak: 'Weak',
  passwordStrengthAverage: 'Average',
  passwordStrengthGood: 'Good',
  passwordStrengthStrong: 'Strong',
  minChars3: 'At least 3 characters',

  // Broker UI
  brokerProperties: 'Broker Properties',
  common: 'Common',
  advanced: 'Advanced',
  reset: 'Reset',
  propertyName: 'Property Name',
  runtimeConfiguration: 'Runtime Configuration',
  synchronizing: 'Synchronizing…',
  failedToLoadStatus: 'Failed to load status',
  refreshBrokerStatus: 'Refresh broker status',
  downloadExcel: 'Download as Excel',
  copyToClipboard: 'Copy to clipboard',
  copyStatement: 'Copy statement',
  refreshLog: 'Refresh Log',
  monitoring: 'Monitoring',
  copyVisibleEntries: 'Copy visible entries to clipboard',
  connected: 'Connected',

  // Database modals (extra)
  criticalWarning: 'Critical Warning',
  volumesToDelete: 'Volumes To Be Deleted',
  destructiveAction: 'Destructive Action',
  noBackupRecords: 'No Backup Records Found',
  newDatabaseName: 'New Database Name',
  downtimeRequired: 'Downtime Required',
  cloneDatabase: 'Clone Database',
  cloneIdentifier: 'Clone Identifier',
  backupStrategy: 'Backup Strategy',
  backupDatabaseNameLabel: 'Database name:',
  volumeNameCol: 'Volume name:',
  backupInformation: 'Backup Information',
  backupHistoryInformation: 'Backup History Information',
  backupLevel: 'Backup level:',
  backupDate: 'Last Backup Date',
  backupSizeColumn: 'Size (MB)',
  backupPath: 'Backup Path',
  backupHistoryListHint: 'Previous backup history Information',
  checkDatabaseConsistency: 'Check the database consistency',
  deleteArchivedLogs: 'Delete unnecessary log-archives',
  compressBackupVolume: 'Compress backup volumes',
  safeBackup: 'Safe backup for replication',
  parallelThreads: 'Parallel backup:',
  dynamicCompaction: 'Compact Database',
  compactDatabaseName: 'Database name:',
  compactDatabaseMessage: 'Compact Database',
  compactDescriptionInformation: 'Description',
  compactDatabaseDescription: 'This utility reclaims space from two sources\n\n-OIDs of deleted objects\n-multiple table representations',
  maintenanceTarget: 'Maintenance Target',
  compactionFailed: 'Compaction Failed',
  performanceTuning: 'Performance Tuning',
  noMatches: 'No Matches',
  optimizationScope: 'Optimization Scope',
  provisionVolume: 'Add Volume',
  autoVolume: 'Auto Volume',
  triggerThreshold: 'Trigger threshold',
  dataVolume: 'Data Volume',
  dataIndexVolume: 'Data + Index Volume',
  dataIndexVolumeDescription: 'Data and index volumes',
  autoVolumeEnabled: 'Auto-Volume On',
  autoVolumeDisabled: 'Auto-Volume Off',
  createBackupPlan: 'Create Backup Plan',
  editBackupPlan: 'Edit Backup Plan',
  executionSchedule: 'Execution Schedule',
  concurrentThreads: 'Concurrent Threads',
  addQueryPlan: 'Add Query Plan',
  editQueryPlan: 'Edit Query Plan',
  connectionInformation: 'Connection Information',
  standardParameters: 'Standard Parameters',
  syncingConfiguration: 'Syncing Configuration',
  noPlanData: 'No Plan Data',
  configuration: 'Configuration',
  autoBackupLog: 'Auto Backup Log',
  autoVolumeLog: 'Auto Volume Log',
  autoQueryLog: 'Auto Query Log',
  filterLogs: 'Filter logs…',
  auditHistoryFor: (db) => `Audit history for: ${db}`,
  noLog: 'No log',

  yes: 'Yes',
  no: 'No',
  ready: 'Ready',
  active: 'Active',
  options: 'Options',
  locks: 'Locks',
  size: 'Size',
  regionLocale: 'Region locale',
  noSessions: 'No sessions',
  noActiveTransactions: 'No active transactions.',
  noObjectLocks: 'No object locks',
  noHeldObjectLocks: 'No held object locks.',
  failedToGetLockInfo: 'Failed to get lock information.',
  leaveBlankNoPassword: 'Leave blank for no password',
  repeatPassword: 'Repeat password',
  addVolume: 'Add Volume',
  clickAddVolumeHint: 'Click "Add Volume" to provision extra storage segments.',
  identifier: 'Identifier',
  segment: 'Segment',
  sizeMb: 'Size MB',
  absolutePath: 'Absolute Path',
  autoStart: 'Auto-start',
  totalVolumes: 'Total volumes',
  genericVolume: 'Generic volume',
  logVolume: 'Log volume',
  volumeTypeData: 'Data',
  volumeTypeIndex: 'Index',
  volumeTypeTemp: 'Temp',
  operationInterrupted: 'Operation Interrupted',
  operationFailed: 'Operation Failed',
  operationComplete: 'Operation Complete',
  transactionDropped: 'Transaction Dropped',
  copyCompleted: 'Copy completed',
  snapshotInProgress: 'Backup In Progress',
  snapshotSecured: 'Backup Completed',
  backupSubtitle: 'Create a backup of the database volumes',
  storageConfiguration: 'Backup Information',
  revisionId: 'Backup Level',
  backupDirectory: 'Backup Directory',
  backupDirFetchError: 'Could not retrieve the default backup directory. Please enter the path manually.',
  restoringDatabase: 'Restoring Database',
  reconstructingInstance: 'Restoring Database',
  restoreCompleted: 'Restore Completed',
  recoveryFailed: 'Recovery Failed',
  restoreSubtitle: 'Restore the database from a backup',
  databaseMustBeStopped: 'Database must be stopped before restoration',
  targetInstance: 'Target Database',
  snapshotCatalog: 'Backup Information',
  scanningCatalog: 'Loading backup information…',
  restoreOptions: 'Recovery Options',
  applyIntermediateLogs: 'Perform partial recovery when archive logs are absent',
  pathOverride: 'Specify Recovery Path',
  restoreInPlaceHint: 'Leave blank to use the original path',
  renamingDatabase: 'Renaming Database',
  updatingIdentity: 'Updating Identity',
  renameComplete: 'Rename Complete',
  renameSuccessful: 'Rename Successful',
  renameFailed: 'Rename Failed',
  executeRename: 'Execute Rename',
  retryRename: 'Retry Rename',
  sourceDatabase: 'Source Database',
  currentIdentifier: 'Current Name',
  targetIdentifier: 'New Name',
  destructiveOptions: 'Options',
  overwriteExistingTarget: 'Overwrite Existing Target',
  overwriteTargetDesc: 'Force-delete target path directories if they already exist',
  overwriteTargetWarning: 'This will permanently delete any existing directory at the target path before migration begins.',
  renameDowntimeHint: 'Ensure the database service is fully stopped before renaming to prevent binary corruption.',
  synchronizingVolumes: 'Copying Database',
  cloningComplete: 'Copy Complete',
  cloningFailed: 'Copy Failed',
  cloneSubtitle: 'Copy the database volumes',
  cloningContext: 'Copy Information',
  targetEnvironment: 'Destination',
  executionStrategy: 'Copy Options',
  overwriteExistingEnvironment: 'Overwrite Existing',
  transformToMove: 'Transform to Move Operation',
  executeCopy: 'Copy',
  consolidatingBlocks: 'Compacting Database',
  optimizationComplete: 'Optimization Complete',
  optimizationPipeline: 'Optimization',
  executionOptions: 'Options',
  executeCompaction: 'Compact',
  retryOptimization: 'Retry Optimization',
  verboseMonitoring: 'Verbose Monitoring',
  verboseMonitoringDesc: 'Show real-time OID transformation logs',
  executingHeuristics: 'Optimizing',
  executionInterrupted: 'Interrupted',
  performanceTuningSubtitle: 'Optimize query execution plans',
  optimizerIntel: 'Optimizer',
  targetInstanceSection: 'Target Database',
  applyChanges: 'Apply Changes',
  updateSuccessful: 'Update Successful',
  configurationReIndexed: 'Configuration Updated',
  updateRejected: 'Update Failed',
  synchronizationHalted: 'Synchronization Failed',
  updatingRegistry: 'Updating Configuration',
  syncingRegistrySubtitle: 'Updating cubrid.conf on the server.',
  navigation: 'Navigation',
  context: 'Context',
  loadingLabel: 'Loading',
  queryingHostRegistry: 'Loading configuration…',
  brokerConnection: 'Broker Connection',
  brokerIp: 'Broker IP',
  publicAddress: 'Public address',
  servicePort: 'Service Port',
  activeBroker: 'Active broker',
  textEncoding: 'Text Encoding',
  charset: 'Charset',
  synchronizationNotice: 'Synchronization Notice',
  brokerParamsNotice: 'Broker parameters define how the Web Manager communicates with the CUBRID Broker. Changes only impact Manager-to-Host synchronization logic.',
  lockingSection: 'Locking',
  transactionSection: 'Transaction',
  systemSection: 'System',
  advancedHeuristics: 'Advanced Heuristics',
  databaseProperties: 'Database Properties',
  initializingSchedule: 'Initializing',
  committingAutomation: 'Saving',
  scheduleCommitted: 'Saved',
  automationActive: 'Active',
  executionError: 'Execution Error',
  initializeCycle: 'Save',
  abstractionLevel: 'Type',
  planRegistryId: 'Plan ID',
  payloadPath: 'Path',
  rotationLogic: 'Rotation',
  targetTime: 'Target Time',
  standard24hCycle: 'Daily (24h cycle)',
  registryDate: 'Date',
  optimizationMatrix: 'Optimization',
  rotationRetention: 'Retention',
  deleteBackupPlan: 'Delete Backup Plan',
  deleteQueryPlan: 'Delete Query Plan',
  deletingQueryPlan: 'Deleting Query Plan',
  removingRegistry: 'Deleting',
  deletionSuccess: 'Deletion Success',
  registryPurged: 'Query Plan Deleted',
  queryPlanRemovedMsg: 'The query plan has been deleted.',
  deletionFailed: 'Deletion Failed',
  signalRejected: 'Deletion Failed',
  deletionSignalFailed: 'Failed to delete the query plan.',
  retryDeletion: 'Retry Deletion',
  dangerousDiscardQueryPlan: 'Delete Query Plan',
  permanentRemovalSql: 'Remove SQL automation entry',
  executeDiscard: 'Delete',
  discardQueryStrategy: 'Delete Query Plan?',
  planRetirement: 'Delete Query Plan',
  planCacheDumpTitle: 'Plan Cache Dump',
  loadingParameters: 'Loading parameters',
  parameter: 'Parameter',
  serverValue: 'Server Value',
  clientValue: 'Client Value',
  failedToGetDbParams: 'Failed to get database parameters.',
  message: 'Message',
  activeContext: 'Active Context',
  offlineStatic: 'Offline Static',
  noConfigParameters: 'No configuration parameters identified for this instance.',
  parameterDumpSubtitle: 'Check out the parameter values',
  environmentReady: 'Ready',
  analysisPipeline: 'Analysis',
  comparativeAnalysis: 'Comparative Analysis',
  comparativeAnalysisDesc: 'Extract both client/server values',
  loadingBrokerStatus: 'Loading broker status…',
  basicInformation: 'Basic Information',
  lastAccess: 'Last Access',
  clientIp: 'Client IP',
  jobId: 'Job ID',
  priority: 'Priority',
  elapsed: 'Elapsed',
  request: 'Request',
  activeCount: (n) => `${n} active`,
  queuedCount: (n) => `${n} queued`,
  downloadAllLogs: 'Download all loaded logs into a single file',
  setAutomationVolume: 'Set Automation Volume',
  addStorageVolume: 'Add Storage Volume',
  editBackupPlanTitle: 'Edit Backup Plan',
  deleteBackupPlanTitle: 'Delete Backup Plan',
  runBackup: 'Run Backup',
  retryBackup: 'Retry Backup',
  backupCompleted: 'Backup Completed',
  backupFailed: 'Backup Failed',
  targetDatabase: 'Target Database',
  executeRestore: 'Execute Restore',
  retryRecovery: 'Retry Recovery',
  restoreSuccessful: 'Restore Successful',
  initiateCopy: 'Initiate Copy',
  retryClone: 'Retry Clone',
  executeOptimization: 'Execute Optimization',
  retryExecution: 'Retry Execution',
  volumeAllocation: 'Add Volume',
  scalingFoundation: 'Adding Volume',
  allocationSuccessful: 'Volume Added',
  storageExpanded: 'Volume Added Successfully',
  allocationInterrupted: 'Add Volume Error',
  scalingFailed: 'Failed to Add Volume',
  storageOptimization: 'Optimize Database',
  allocationStrategy: 'Volume Options',
  instanceRegistry: 'Database',
  privilegedOperation: 'Note',
  addVolumeNote: 'The database must be running to add a volume. Ensure the volume path has write permissions.',
  extendDiskCapacity: (db) => `Add volume to ${db}`,
  historyForDatabase: (db) => `History for database: ${db}`,
  globalBackupHistory: 'Global Backup History',
  dumpingPlanCache: 'Dumping Plan Cache',
  displayQueryPlan: 'Show the query plan',
  dumpingPlanCacheSubtitle: 'Reading XASL plan cache from server...',
  runDumpHint: 'Run the dump to view query plan cache entries.',
  backupId: 'Backup ID',
  logTime: 'Log Time',
  description: 'Description',

  // Header menu (extra)
  actionMenu: 'Top Tasks',
  configParam: 'Config Param',
  editCmConfig: 'Edit CM Config',
  reportBug: 'Report Bug',
  cubridOnlineForum: 'CUBRID Online Forum',
  cubridToolsDevelopment: 'CUBRID tools developments',
  checkForUpdates: 'Check for Updates',

  // Dashboard shared
  globalHealthOverview: 'Global Health Overview',
  hostsLabel: 'Hosts',
  activeLabel: 'Active',
  unknownHost: 'Unknown Host',
  localhost: 'Localhost',
  statusOn: 'On',
  statusOff: 'Off',
  synchronizingServices: 'Synchronizing Services',
  stopServices: 'Stop Services',
  startServicesConfirmTitle: 'Start Services',
  startServicesConfirmDesc: (server) => `Are you sure you want to start all CUBRID services on host "${server}"?`,
  stopServicesConfirmTitle: 'Stop Services',
  stopServicesConfirmDesc: (server) =>
    `Are you sure you want to stop all CUBRID services on host "${server}"? This will terminate all active brokers and databases.`,
  startingServicesOn: (server) => `Starting services on ${server}`,
  stoppingServicesOn: (server) => `Stopping services on ${server}`,
  serviceStartRejected: 'Service start command rejected by host agent.',
  serviceStopFailed: 'Service termination failed. Check agent logs.',
  connectHostForMonitoring: 'Connect to a host server from the navigator to activate global resource monitoring.',
  permanentTemp: 'Permanent Temp',
  tempTemp: 'Temporary Temp',
  userLabel: 'User',
  haMaster: 'Master',
  haSlave: 'Slave',
  haReplica: 'Replica',
  clusterOverview: 'Cluster Overview',

  // Database dashboard
  databaseDashboard: 'Database Dashboard',
  refreshDatabaseStatus: 'Refresh database status',
  exportMetricsCsv: 'Export metrics as CSV',
  restartingCas: 'Restarting CAS',
  resettingCasProcess: 'Resetting broker application server process',
  loadingDashboard: 'Loading Dashboard…',
  restartCasConfirm: (cas, broker) => `Are you sure you want to restart CAS ID: ${cas} on broker: ${broker}?`,

  // Database dashboard sections
  performanceMetrics: 'Performance Metrics',
  realTime: 'Real-time',
  transPerSec: 'Trans/sec',
  queriesPerSec: 'Queries/sec',
  bufferHit: 'Buffer Hit',
  fetchesPerSec: 'Fetches/s',
  dirtyPerSec: 'Dirty/s',
  ioReadsPerSec: 'IO Reads/s',
  ioWritesPerSec: 'IO Writes/s',
  storageVolumes: 'Storage Volumes',
  volumeLabel: 'Volume',
  purpose: 'Purpose',
  spaceUsage: 'Space Usage',
  modifiedLabel: 'Modified',
  pathLabel: 'Path',
  fileDistribution: 'File Distribution',
  logicalPartitioning: 'Logical Partitioning',
  filesLabel: 'Files',
  usedLabel: 'Used',
  fileTable: 'File Table',
  reservedLabel: 'Reserved',
  totalLabel: 'Total',
  casBrokers: 'CAS Brokers',
  readyCount: (n) => `${n} ready`,
  busyCount: (n) => `${n} busy`,
  lastConn: 'Last Conn',
  sqlLogs: 'SQL Logs',
  slowQueryLogs: 'Slow Query Logs',
  restartCasTitle: 'Restart CAS',
  lockMode: 'Lock Mode',
  activeLog: 'Active Log',
  archiveLog: 'Archive Log',
  longTran: 'Long-T',
  longQuery: 'Long-Q',
  errQuery: 'Err-Q',
  reqLabel: 'REQ',
  jqLabel: 'JQ',
  asLabel: 'AS',

  // System status section
  systemStatus: 'System Status',
  nowLabel: 'Now',
  fiveMinAvg: '5 min Avg',
  resume: 'Resume',
  haClusterStatus: 'HA Cluster Status',
  nodesActiveInCluster: (n) => `${n} nodes active in cluster`,
  environmentUnavailable: 'Environment information unavailable',

  language: 'Language',
  languageEn: 'English',
  languageKo: 'Korean',

  // Backup dialog options (aligned with CUBRID Admin)
  backupLevelFullTitle: 'Full Backup',
  backupLevelFullDesc: 'Complete backup of all data',
  backupLevelIncrL1Title: 'Incremental (L1)',
  backupLevelIncrDesc: 'Changes since last L0 backup',
  backupLevelIncrL2Title: 'Incremental (L2)',
  backupLevelDiffDesc: 'Changes since last L1 backup',
  checkConsistencyLabel: 'Check Database Consistency',
  checkConsistencyDesc: 'Check the database consistency during backup',
  deleteArchiveLogsLabel: 'Delete Unnecessary Log-Archives',
  deleteArchiveLogsDesc: 'Remove transaction logs already archived',
  compressBackupLabel: 'Compress Backup Volumes',
  compressBackupDesc: 'Reduce backup file size with compression',
  parallelBackupDesc: 'Number of parallel backup threads',
  threadsLabel: 'Threads',

  // Compact database steps
  compactStep1Label: 'Clean References',
  compactStep1Desc: 'Remove unused object references',
  compactStep2Label: 'Clean Metadata',
  compactStep2Desc: 'Clean internal metadata',
  compactStep3Label: 'Consolidate Disk',
  compactStep3Desc: 'Merge fragmented disk pages',

  // Optimize database
  allTables: 'All Tables',
  filterObjects: 'Filter objects...',
  regeneratingStatistics: 'Regenerating Statistics',
  optimizationSuccess: 'Optimization Complete',
  optimizationFailed: 'Optimization Failed',
  optimizerHint: 'Regenerating statistics allows the query optimizer to choose the most efficient execution paths.',
  globalScanHint: 'Global scans may briefly lock schema metadata during analysis.',

  // Copy database path labels
  primaryVolumePath: 'Database Volume Path',
  extVolumePath: 'Extended Volume Path',
  logVolumePath: 'Log Volume Path',
  replaceExistingDesc: 'Replace destination files if a database with this name already exists.',
  moveSourceDesc: 'Remove source files after the copy is successfully finalized.',

  // Query plan modals (Add/Edit)
  queryIdentifierRequired: 'A Query ID is required.',
  sqlStatementRequired: 'An SQL statement is required.',
  queryPlanAdded: 'Query Plan Added',
  addQueryPlanFailed: 'Failed to Add Query Plan',
  editQueryPlanFailed: 'Failed to Update Query Plan',
  objectIdentification: 'Identification',
  queryIdentifierLabel: 'Query ID',
  secureContextSection: 'Database Credentials',
  databaseUsernameLabel: 'Username',
  databasePasswordLabel: 'Password',
  recurrenceFrequency: 'Frequency',
  startTimeLabel: 'Time',
  dailyLabel: 'Daily',
  weeklyLabel: 'Weekly',
  monthlyLabel: 'Monthly',
  specificDateLabel: 'Specific Date',
  sqlStatementSection: 'SQL Statement',
  systemComplianceNote: 'Queries are executed on the server side. The database user must have sufficient privileges.',
  runSchedule: 'Save',
  automatingDatabase: 'Automating database',

  // Backup plan level descs (short)
  levelFullShortDesc: 'Full backup',
  levelIncrL0ShortDesc: 'Since last L0',
  levelIncrL1ShortDesc: 'Since last L1',

  // Backup plan option labels
  updateStatisticsLabel: 'Update Statistics',
  updateStatisticsDesc: 'Update query optimizer statistics',
  deleteArchiveDesc: 'Delete transaction logs that have already been archived',

  // Backup plan schedule options
  monthly: 'Monthly',
  weekly: 'Weekly',
  daily: 'Daily',
  specificDays: 'Specific Date',
  onlineMode: 'Online',
  onlineModeDesc: 'Backup while the database is running',
  offlineMode: 'Offline',
  offlineModeDesc: 'Backup with the database stopped',
  savingSchedule: 'Saving',
  updatingSchedule: 'Updating',

  // Delete backup plan modal
  deletingBackupPlan: 'Deleting Backup Plan',
  backupPlanDeleted: 'Backup Plan Deleted',
  backupPlanRemovedMsg: 'The backup plan has been removed from the scheduler.',
  deleteBackupPlanFailed: 'Delete Backup Plan Failed',
  discardBackupStrategy: 'Delete Backup Plan?',
  backupScheduleNote: 'This only removes the schedule. Existing backup files remain on disk.',
  dangerousDiscardBackupPlan: 'Delete Backup Plan',
  permanentRemovalBackup: 'Permanently remove this backup schedule',

  // SetAutomationVolumeModal
  savingPolicies: 'Saving',
  policiesSaved: 'Saved',
  savedSuccessfully: 'Saved Successfully',
  saveInterrupted: 'Save Failed',
  savePolicies: 'Save',
  expansionSize: 'Expansion Size (MB)',
  extensionPages: 'Extension Pages',
  autoVolumeActive: 'Auto Volume Active',
  loadingConfig: 'Loading configuration…',
  indexVolume: 'Index Volume',

  // AddVolumeModal
  retryAddVolume: 'Retry',
  activeInstanceRequired: 'Database must be running',
  availableSpace: 'Free Space',
  customCapacity: 'Volume Size (MB)',
  blocksAllocated: 'Number of Pages',
  volumeIdentifier: 'Volume Name',
  volumeDir: 'Volume Path',
  addVolumeTargetDb: 'Target Database',
  calculating: 'Calculating',
  volumeSizeVisualizer: 'Volume Size',
  addVolumeSuccessMessage: (volName, db) => `Volume "${volName}" has been successfully added to ${db}.`,
  volumeTypeDataDesc: 'Tables and rows',
  volumeTypeTempDesc: 'Temporary workspace',

  // RestoreDatabaseModal
  logCatchup: 'Partial Recovery',
  noBackupFound: 'No Backup Records Found',
  noBackupHint: 'Ensure the backup directory is configured and synchronized.',
  showAllBackups: 'Show all',
  irreversibleOperation: 'Irreversible Operation',
  restoreOverwriteNote: 'All existing volumes will be permanently overwritten by the selected backup.',
  selectBackupFirst: 'Please select a backup to restore from.',
  restoreErrorFallback: 'An unexpected error occurred during restore.',
  tryOtherBackupLevel: 'Try selecting another backup level, or view all.',
  recoveryPathPlaceholder: 'Default: original location',
  backupLevelFullLongDesc: 'Complete snapshot of all data, schema and volumes.',
  backupLevelIncrL1LongDesc: 'Changes since last L0 backup. Requires L0 to restore.',
  backupLevelIncrL2LongDesc: 'Changes since last L1 backup. Requires L0 + L1 to restore.',

  // Auth
  pickUniqueUsername: 'Pick a unique username',
  createStrongPassword: 'Create a strong password',
  repeatPassword: 'Repeat your password',
  emailAddressLabel: 'Email Address',

  // Sidebar context menus
  newGroup: 'New Group',
  addNode: 'Add Node',
  renameGroup: 'Rename Group',
  deleteGroup: 'Delete Group',
  viewAllLogs: 'View All Logs',
  viewDatabase: 'View Database',

  // Host modals
  loginIdLabel: 'Login ID',
  statusAuthorityLabel: 'Status Authority',
  administratorAccount: 'Administrator Account',
  groupNameLabel: 'Group Name',
  hostPasswordPlaceholder: 'Host password',
  haClusterLinked: 'HA Cluster Linked',
  mergeHAPeers: 'Merge HA Cluster Peers',

  // User modals
  moveToGroups: 'Move to Groups',
  removeFromAssigned: 'Remove from assigned',
  departmentLabel: 'Department',
  currentPasswordLabel: 'Current Password',
  confirmNewPassword: 'Confirm New Password',
  dropDatabaseUser: 'Drop Database User',
  droppingUser: 'Deleting',
  userDropped: 'Deleted',
  dropUserConfirmSection: 'Confirm Delete',
  dropUserWarning: 'This action is permanent.',
  dropUserBtn: 'Drop User',

  // DeleteDatabaseModal
  deletingDatabase: 'Deleting',
  deleteSuccessful: 'Delete Successful',
  authorizationPointTitle: 'Authorization',
  targetSelection: 'Target Selection',
  recoveryCleanup: 'Recovery Cleanup',
  purgeLinkedBackups: 'Delete Linked Backups',
  purgeLinkedBackupsDesc: 'Remove all backup volumes and snapshots linked to this database.',
  fetchingAssets: 'Loading...',
  noVolumesDetected: 'No volumes detected',
  proceedBtn: 'Proceed',
  backBtn: 'Back',

  // VolumeInfoMonitor
  loadingVolumeInfo: 'Loading Volume Information',
  loadingVolumeInfoSub: 'Fetching volume allocation data...',
  volumeNotFound: 'Volume Not Found',

  // Log modals
  filterLogsById: 'Filter by ID or description...',
  buffering: 'Buffering',
  synchronizedStatus: 'Synchronized',

  // Monitoring / misc
  monitoringSync: 'Monitoring Synchronization',
  customIntervalPlaceholder: 'Custom interval',
  defaultValuePlaceholder: 'Default',

  // Config editors
  undoAllChanges: 'Undo all changes',
  brokerConfigPlaceholder: '# Enter broker configuration here...',

  // EditCMSUserModal
  savingChanges: 'Saving Changes',
  creatingUser: 'Creating User',
  accountInformation: 'Account Information',
  allowDatabaseCreation: 'Allow Database Creation',
  allowDbCreationDesc: 'User can create and drop databases on this host',

  // CreateUserModal
  createUser: 'Create User',
  userUpdated: 'User Updated',
  userCreated: 'User Created',

  // UserProfileModal
  accountDetails: 'Account Details',
  updateProfileSection: 'Update Profile',
  accountProfile: 'Account Profile',
  editProfile: 'Edit Profile',
  updatePasswordBtn: 'Update Password',
  securitySettings: 'Security Settings',

  // DatabasePropertyModal
  confirmReturn: 'Confirm & Return',
  retryPatch: 'Retry Patch',
  discardChanges: 'Discard Changes',

  // HaPeerMergeModal / HostGroupNameModal
  mergeIntoGroup: 'Merge into group',
  createGroup: 'Create Group',

  // CMSUserManagementModal
  systemAdministrator: 'System administrator',
  managementUsers: 'Management users',

  // Monitor refresh buttons
  refreshVolumeData: 'Refresh volume data',
  refreshCategoryMetrics: 'Refresh category metrics',
  refreshSpaceMetrics: 'Refresh space metrics',

  // DatabaseSpaceMonitor
  storageAnalysisError: 'Storage Analysis Error',

  // CreateDatabaseModal
  removeVolume: 'Remove volume',
  storage: 'Storage',

  // CreateUserModal
  source: 'Source',

  // Auth pages
  recoverPassword: 'Recover your password',
  linkExpiry: 'Link Expiry',
  registrationFailedTitle: 'Registration Failed',
  desktopOnly: 'Desktop only',
  desktopBridgeUnavailable: 'Desktop bridge unavailable',
};
