/**
 * CUBRID Manager 스타일 UI 라벨 (한국어).
 * cmLabels.js 와 동일한 키 구조.
 */
export const CM_KO = {
  ok: '확인',
  cancel: '취소',
  close: '닫기',
  refresh: '새로 고침',
  confirm: '확인',
  error: '오류',
  warning: '경고',
  success: '성공',
  failure: '실패',

  loginDatabase: '데이터베이스 로그인',
  loginDatabaseMsg: '선택한 데이터베이스에 로그인합니다.',
  loggingInto: (db) => `"${db}" 데이터베이스에 로그인 중...`,
  connectionSuccessful: '연결에 성공했습니다.',
  userName: '사용자 이름',
  password: '비밀번호',
  databaseName: '데이터베이스 이름',
  savePassword: '비밀번호 저장',

  transactionInformation: '트랜잭션 정보',
  activeTransactionsOf: '데이터베이스의 활성 트랜잭션:',
  tranIndex: '트랜잭션 인덱스',
  userNameCol: '사용자 이름',
  host: '호스트',
  processId: '프로세스 ID',
  programName: '프로그램 이름',
  killTransaction: '트랜잭션 종료',
  killTransactionTitle: '트랜잭션 종료',
  killType: '종료 유형',
  killSelectedOnly: '선택한 트랜잭션만 종료',
  killSameUser: '동일 사용자의 모든 트랜잭션 종료',
  killSameHost: '동일 클라이언트 호스트의 모든 트랜잭션 종료',
  killSameProgram: '동일 프로그램의 모든 트랜잭션 종료',
  killSuccess: '트랜잭션이 성공적으로 종료되었습니다.',

  lockingInformation: '잠금 정보',
  lockSettingClientInfo: '잠금 설정/클라이언트 정보',
  objectLockTable: '객체 잠금 테이블',
  lockAndTransaction: '잠금 및 트랜잭션',
  loadingLockAndTransaction: '잠금 및 트랜잭션 정보를 불러오는 중...',
  lockIndex: '인덱스',
  pname: '프로세스명',
  uid: '사용자 ID',
  pid: '프로세스 ID',
  isolationLevel: '격리 수준',
  timeOut: '타임아웃',
  oid: 'OID',
  objectType: '객체 유형',
  mode: '모드',
  numHolders: '보유자 수',
  numBlockedHolders: '차단 보유자 수',
  numWaiters: '대기자 수',
  lockEscalation: '잠금 에스컬레이션',
  runDeadlockInterval: '데드락 검사 간격',
  currentLockedObjNum: '현재 잠긴 객체 수',
  maxLockedObjNum: '최대 잠금 가능 객체 수',

  checkDatabase: '데이터베이스 검사',
  checkDatabaseDesc:
    '데이터베이스를 검사합니다. 불일치가 발견되면 CUBRID 지원에 문의하여 결과 해석 및 조치를 진행하십시오.',
  repairWhenInconsistency: '불일치 발견 시 복구',
  jobCompletedSuccess: (job) => `${job} 작업이 성공적으로 완료되었습니다`,

  createDatabase: '데이터베이스 생성',
  deleteDatabase: '데이터베이스 삭제',
  deleteDatabaseConfirm: '이 데이터베이스를 삭제하시겠습니까?',
  backupDatabase: '데이터베이스 백업',
  restoreDatabase: '데이터베이스 복원',
  compactDatabase: '데이터베이스 압축',
  optimizeDatabase: '데이터베이스 최적화',
  copyDatabase: '데이터베이스 복사',
  renameDatabase: '데이터베이스 이름 변경',
  loadDatabase: '데이터베이스 로드',
  unloadDatabase: '데이터베이스 언로드',
  dbaConfirm: 'DBA 확인',
  dbaPassword: 'DBA 비밀번호',

  manageDatabase: '데이터베이스 관리',
  databaseInfo: '데이터베이스 정보',
  usedParameterDump: '사용 파라미터 덤프',
  planCacheDump: '플랜 캐시 덤프',

  manageDatabaseMenu: {
    unload: '데이터베이스 언로드...',
    load: '데이터베이스 로드...',
    create: '데이터베이스 생성...',
    check: '데이터베이스 검사',
    compact: '데이터베이스 압축',
    optimize: '데이터베이스 최적화',
    copy: '데이터베이스 복사',
    rename: '데이터베이스 이름 변경',
    restore: '데이터베이스 복원',
    backup: '데이터베이스 백업',
    delete: '데이터베이스 삭제',
  },

  createDatabaseMsg: '새 데이터베이스를 생성합니다.',
  createDbJobComplete: (job) => `${job} 작업이 완료되었습니다.`,
  createDbFailed: '데이터베이스를 시작하지 못했습니다. 연결 정보를 확인하십시오.',
  wizardGeneral: '일반 정보',
  wizardAdditionalVol: '추가 볼륨 정보',
  wizardAutoVol: '볼륨 자동 확장',
  wizardSetDbaPass: 'DBA 비밀번호 설정',
  wizardDbInfo: '데이터베이스 정보',
  wizardDbInfoList: '새 데이터베이스 생성에 필요한 단계를 완료했습니다. 아래 설정에 따라 생성됩니다.',
  pageSize: '페이지 크기 (byte)',
  logPageSize: '로그 페이지 크기 (byte)',
  localeCharset: '문자 집합',
  userDefined: '사용자 정의',
  volumeSize: '볼륨 크기 (Mbyte)',
  genericVolInfo: '일반 볼륨 정보',
  genericVolPath: '일반 볼륨 경로',
  logVolInfo: '로그 볼륨 정보',
  logVolPath: '로그 볼륨 경로',
  volumeName: '볼륨 이름',
  volumePath: '볼륨 경로',
  volumeType: '볼륨 유형',
  autoStartDb: 'CUBRID 서비스 시작 시 데이터베이스 자동 시작',
  passwordConfirm: '비밀번호 확인',
  setPassword: '비밀번호 설정',
  readyToCreate: '생성 준비 완료',
  back: '이전',
  next: '다음',
  finish: '완료',

  unloadDatabaseMsg: '선택한 데이터베이스를 언로드합니다.',
  unloadSuccess: '데이터베이스가 성공적으로 언로드되었습니다.',
  unloadResultTitle: '데이터베이스 언로드 결과',
  unloadResultMsg: '아래에서 언로드 결과를 확인할 수 있습니다.',
  grpDbInfo: '데이터베이스 정보',
  targetDbName: '대상 데이터베이스 이름',
  targetDirectory: '대상 디렉터리',
  unloadTarget: '언로드 대상',
  unloadOption: '언로드 옵션',
  schema: '스키마',
  data: '데이터',
  all: '전체',
  selectedTables: '선택한 테이블',
  notInclude: '포함 안 함',
  useDelimitedIdentifier: '구분 식별자 사용 ("")',
  includeReferencedTables: '참조 테이블 포함',
  prefixOutputFiles: '출력 파일 접두사',
  fileForHash: '해시 파일',
  numCachedPages: '캐시 페이지 수',
  estimatedInstances: '예상 인스턴스 수',
  loFileCountPerDir: '디렉터리당 LO 파일 수',
  availableClasses: '사용 가능한 클래스',

  loadDatabaseMsg: '선택한 데이터베이스를 로드합니다.',
  loadResultTitle: '데이터베이스 로드 결과',
  loadResultMsg: '아래에서 로드 결과를 확인할 수 있습니다.',
  unloadedFiles: '언로드된 파일',
  loadType: '로드 유형',
  path: '경로',
  date: '날짜',
  selectFromList: '목록에서 언로드 파일 선택',
  selectFromRemote: '원격 시스템에서 언로드 파일 선택',
  selectFromLocal: '로컬 시스템에서 언로드 파일 선택',
  loadOption: '로드 옵션',
  loadSchema: '스키마 로드',
  loadObject: '객체 로드',
  loadIndex: '인덱스 로드',
  loadTrigger: '트리거 로드',
  checkSyntaxAndLoad: '구문 검사 후 로드',
  insertionCountPeriodicCommit: '주기적 커밋 삽입 건수',
  dontUseOid: 'OID 사용 안 함',
  dontUpdateStatistics: '통계 갱신 안 함',
  usingErrorControlFile: '오류 제어 파일 사용',
  ignoredTableFile: '무시할 테이블 파일',
  loadDbTask: '데이터베이스 로드',

  save: '저장',
  retry: '다시 시도',
  dismiss: '닫기',
  apply: '적용',
  discard: '취소',
  connect: '연결',
  loginAll: '전체 로그인',
  disconnect: '연결 해제',
  tryAgain: '다시 시도',
  add: '추가',
  edit: '편집',
  remove: '제거',
  startLabel: '시작',
  stopLabel: '중지',
  restart: '재시작',
  processing: '처리 중...',
  pleaseWait: '잠시만 기다려 주세요.',
  selectAll: '전체 선택',
  name: '이름',
  address: '주소',
  port: '포트',
  status: '상태',
  type: '유형',
  value: '값',
  actions: '작업',
  live: '실시간',
  paused: '일시정지',
  identity: '식별 정보',
  credentials: '인증 정보',
  username: '사용자 이름',
  newPassword: '새 비밀번호',
  leaveBlankToKeep: '비워 두면 기존 비밀번호 유지',
  passwordsDoNotMatch: '비밀번호가 일치하지 않습니다.',
  hostNameRequired: '호스트 이름을 입력하세요.',
  addressRequired: '주소를 입력하세요.',
  portRequired: '포트를 입력하세요.',
  usernameRequired: '사용자 이름을 입력하세요.',
  passwordRequired: '비밀번호를 입력하세요.',

  appName: 'CUBRID Manager',
  selectHostHint: '사이드바에서 호스트를 선택하면 데이터베이스, 브로커, 로그를 모니터링할 수 있습니다.',
  hostManagement: '호스트 관리',
  volumeMonitor: '볼륨 모니터',
  performance: '성능',
  lockInfo: '잠금 정보',
  systemReady: '시스템 준비됨',
  managerAccess: '관리자 접근 로그',
  managerError: '관리자 오류 로그',
  brokerStatus: '브로커 상태',
  processingDbRequest: '데이터베이스 요청 처리 중...',
  processingRequest: '요청을 처리하는 중입니다. 잠시만 기다려 주세요.',
  cmsJobRunningInBackground: (target, statusHint = '') =>
    `${target}${statusHint} — 백그라운드에서 실행 중`,
  backgroundJobsTitle: '백그라운드 작업',
  backgroundJobsRunning: (n) => `${n}개 실행 중`,
  backgroundJobsEmpty: '백그라운드 작업 없음',
  clearCompletedJobs: '완료 항목 지우기',
  jobStatusQueued: '대기',
  jobStatusRunning: '실행 중',
  jobStatusSucceeded: '완료',
  jobStatusFailed: '실패',
  jobNotifySucceeded: (op, db) => `${op} 완료 — ${db}`,
  jobNotifyFailed: (op, db) => `${op} 실패 — ${db}`,
  jobTypeUnload: '언로드',
  jobTypeLoad: '로드',
  jobTypeCreate: 'DB 생성',
  jobTypeOptimize: '최적화',
  jobTypeCheck: '검사',
  jobTypeCompact: '압축',
  jobTypeCopy: '복사',
  jobTypeAddVol: '볼륨 추가',
  jobTypeRename: '이름 변경',
  databaseAction: '데이터베이스 작업',
  brokerAction: '브로커 작업',
  actionFailed: '작업 실패',
  updateFailed: '업데이트 실패',
  updateInterrupted: '업데이트 중단',
  applyingChanges: '변경 사항 적용 중...',
  startingDatabase: (db) => `데이터베이스 시작 중: ${db}`,
  startingBroker: (b) => `브로커 시작 중: ${b}`,
  startingService: '서비스 시작 중',
  stoppingService: '서비스 중지 중',
  startingDbNamed: (db) => `데이터베이스 시작: ${db}`,
  stoppingDbNamed: (db) => `데이터베이스 중지: ${db}`,
  startingBrokerNamed: (b) => `브로커 시작: ${b}`,
  stoppingBrokerNamed: (b) => `브로커 중지: ${b}`,
  startBrokerLine: (name) => `브로커 시작: ${name}`,
  stopBrokerLine: (name) => `브로커 중지: ${name}`,
  serviceStartWait: '모든 브로커와 데이터베이스를 시작하는 중입니다. 잠시만 기다려 주세요.',
  serviceStopWait: '모든 브로커와 데이터베이스를 중지하는 중입니다. 잠시만 기다려 주세요.',
  editConfigTab: (name) => `${name} 편집`,
  allLogsTab: (name) => `전체 로그: ${name}`,
  allServerLogsTab: (name) => `서버 전체 로그: ${name}`,
  statusTab: (name) => `상태: ${name}`,
  spaceTab: (db) => `공간: ${db}`,
  volumeTab: (path) => `볼륨: ${path}`,
  volumesTab: (cat) => `볼륨: ${cat.replace(/_/g, ' ')}`,
  brokerConfig: '브로커 설정',
  serviceDashboard: '서비스 대시보드',

  file: '파일',
  view: '보기',
  service: '서비스',
  database: '데이터베이스',
  broker: '브로커',
  addHost: '호스트 추가',
  changeHost: '호스트 변경',
  exportHost: '호스트보내기',
  importHost: '호스트 가져오기',
  exportHosts: '호스트보내기',
  importHosts: '호스트 가져오기',
  importHostsXml: '호스트 XML 가져오기',
  tools: '도구',
  help: '도움말',
  aboutCubridAdmin: 'CUBRID Admin 정보',
  aboutCubrid: 'CUBRID 정보',
  cubridWebManager: 'CUBRID Web Manager',
  systemDetails: '시스템 정보',
  coreVersion: '코어 버전',
  certifiedStable: '안정 인증',
  startService: '서비스 시작',
  stopService: '서비스 중지',
  startStopService: '서비스 시작/중지',
  startStopDatabase: '데이터베이스 시작/중지',
  startStopBroker: '브로커 시작/중지',
  editCubridConfig: 'CUBRID 설정 편집',
  logout: '로그아웃',
  startSelectedDbBroker: '선택한 데이터베이스/브로커 시작',
  switchToDarkMode: '다크 모드',
  switchToLightMode: '라이트 모드',

  addYourFirstHost: '첫 호스트를 추가하세요',
  connectToCubridServer: 'CUBRID 서버에 연결',
  hostLogin: '호스트 로그인',
  establishingSession: '보안 세션을 설정하는 중...',
  connectionFailed: '연결 실패',
  editHost: '호스트 편집',
  deleteHost: '호스트 삭제',
  changePassword: '비밀번호 변경',
  userManagement: '사용자 관리',
  serverVersion: '서버 버전',
  serverColon: (s) => `서버: ${s}`,
  databaseColon: (db) => `데이터베이스: ${db}`,
  allDatabases: '모든 데이터베이스',
  allBrokers: '모든 브로커',
  brokerColon: (b) => `브로커: ${b}`,
  startDatabase: '데이터베이스 시작',
  stopDatabase: '데이터베이스 중지',
  startAllDatabases: '모든 데이터베이스 시작',
  stopAllDatabases: '모든 데이터베이스 중지',
  restartAllDatabases: '모든 데이터베이스 재시작',
  startAllBrokers: '모든 브로커 시작',
  stopAllBrokers: '모든 브로커 중지',
  restartAllBrokers: '모든 브로커 재시작',
  editBrokerConfig: '브로커 설정 편집',
  showStatus: '상태 보기',
  startBroker: '브로커 시작',
  stopBroker: '브로커 중지',
  paramDump: '파라미터 덤프...',
  planDump: '플랜 덤프...',
  properties: '속성',
  databaseInfoMenu: '데이터베이스 정보',

  users: '사용자',
  jobAutomation: '작업 자동화',
  backupPlan: '백업 계획',
  queryPlan: '쿼리 계획',
  space: '공간',
  log: '로그',
  access: '접근',
  adminLog: '관리 로그',
  manager: '관리자',
  accessLog: '접근 로그',
  errorLog: '오류 로그',
  serverLogs: '서버 로그',
  sqlLog: 'SQL 로그',
  noHostSelectedTitle: '호스트 미선택',
  selectServerFromList: '위 목록에서 서버를 선택하세요.',
  serverListAbove: '위 서버 목록',
  admin: 'Admin',
  managerConsole: '관리 콘솔',

  closeTab: '탭 닫기',
  closeOtherTabs: '다른 탭 닫기',
  closeAllTabs: '모든 탭 닫기',
  reloadTab: '탭 새로 고침',
  connectedTo: (host) => `${host}에 연결됨`,
  noHostSelected: '호스트가 선택되지 않음',
  version: '버전',

  newConnection: '새 연결',
  friendlyName: '표시 이름',
  ipAddressDomain: 'IP 주소 / 도메인',
  modifyHost: '호스트 수정',
  removeHostConnection: '호스트 연결 제거',
  keepHost: '유지',
  confirmRemoval: '제거 확인',
  activeConnectionsTerminated: '이 호스트에 대한 활성 연결이 종료됩니다.',
  changeManagerPasscode: '관리자 암호 변경',
  newPasscode: '새 암호',
  verifyNewPasscode: '암호 확인',
  cubridVersion: 'CUBRID 버전',
  environmentDetails: '환경 정보',
  osPlatform: 'OS',
  installPath: '설치 경로',
  haPeersDiscovered: 'HA 노드 발견',
  peerNodes: '피어 노드',
  editUser: '사용자 편집',
  deleteUser: '사용자 삭제',
  addUser: '사용자 추가',
  fullSystemAuth: '전체 시스템 권한',
  primaryAdminCannotDelete: '기본 관리자 계정은 삭제할 수 없습니다.',
  noAccess: '접근 없음',
  monitorOnly: '모니터만',
  fullControl: '전체 제어',
  permissions: '권한',
  brokerAuthority: '브로커 권한',

  serverDashboard: '서버 대시보드',
  refreshDashboard: '대시보드 새로 고침',
  syncedAt: (t) => `동기화: ${t}`,
  databases: '데이터베이스',
  autoStartup: '자동 시작',
  systemStatusError: '시스템 상태 오류',
  period: '기간',
  memory: '메모리',
  disk: '디스크',
  cpu: 'CPU',
  tps: 'TPS',
  qps: 'QPS',
  accessPoint: '접속 주소',
  authUser: '인증 사용자',
  operatingSystem: '운영 체제',
  cubridEngine: 'CUBRID 엔진',
  homeDirectory: '홈 디렉터리',
  permanent: '영구',
  temporary: '임시',
  freeStorage: '여유 공간',
  refreshBrokersList: '브로커 목록 새로 고침',
  startServices: '서비스 시작',
  stopAllServices: '모든 서비스 중지',
  sensorsOffline: '센서 오프라인',
  serviceError: '서비스 오류',
  groupHost: '그룹/호스트',
  dbStatus: 'DB 상태',
  undoChanges: '변경 취소',
  saveChanges: '변경 저장',
  reloadConfig: '설정 다시 불러오기',
  modified: '수정됨',
  sourceEditor: '소스 편집기',
  configPlaceholder: '# 설정 내용...',
  tableEditor: '테이블 편집기',

  signIn: '로그인',
  authorizeAccess: '접근 권한 부여',
  rememberDevice: '이 기기 기억',
  authenticationFailed: '인증 실패',
  createAccount: '계정 만들기',
  backToLogin: '로그인으로 돌아가기',
  accountRecovery: '계정 복구',
  resetCredentials: '접근 자격 증명을 재설정합니다.',
  registrationFailed: '등록에 실패했습니다. 다시 시도하세요.',
  passwordStrengthWeak: '약함',
  passwordStrengthAverage: '보통',
  passwordStrengthGood: '좋음',
  passwordStrengthStrong: '강함',
  minChars3: '3자 이상',

  brokerProperties: '브로커 속성',
  common: '일반',
  advanced: '고급',
  reset: '초기화',
  propertyName: '속성 이름',
  runtimeConfiguration: '런타임 설정',
  synchronizing: '동기화 중…',
  failedToLoadStatus: '상태를 불러오지 못했습니다',
  refreshBrokerStatus: '브로커 상태 새로 고침',
  downloadExcel: 'Excel로 다운로드',
  copyToClipboard: '클립보드에 복사',
  copyStatement: '문장 복사',
  refreshLog: '로그 새로 고침',
  monitoring: '모니터링',
  copyVisibleEntries: '표시 항목을 클립보드에 복사',
  connected: '연결됨',

  criticalWarning: '중요 경고',
  volumesToDelete: '삭제될 볼륨',
  destructiveAction: '위험한 작업',
  noBackupRecords: '백업 기록 없음',
  newDatabaseName: '새 데이터베이스 이름',
  downtimeRequired: '다운타임 필요',
  cloneDatabase: '데이터베이스 복제',
  cloneIdentifier: '복제 식별자',
  backupStrategy: '백업 전략',
  volumeNameCol: '볼륨 이름',
  backupInformation: '백업 정보',
  backupHistoryInformation: '백업 이력 정보',
  backupLevel: '백업 레벨',
  backupDate: '백업 날짜',
  backupPath: '백업 경로',
  backupHistoryListHint: '이 데이터베이스의 백업 이력 정보 목록입니다.',
  checkDatabaseConsistency: '데이터베이스 일관성 확인',
  deleteArchivedLogs: '불필요한 보관 로그 삭제',
  compressBackupVolume: '백업 볼륨 압축',
  safeBackup: '복제를 위한 안전 백업',
  parallelThreads: '병렬 스레드',
  dynamicCompaction: '동적 저장소 압축',
  compactDatabaseName: '데이터베이스 이름',
  compactDatabaseMessage: '선택한 데이터베이스를 압축합니다.',
  compactDescriptionInformation: '설명 정보',
  compactDatabaseDescription: '데이터베이스 압축은 사용하지 않는 객체 식별자와 관련 내부 데이터를 정리하여 재사용 가능한 저장 공간을 확보합니다.',
  maintenanceTarget: '유지보수 대상',
  compactionFailed: '압축 실패',
  performanceTuning: '성능 튜닝',
  noMatches: '일치 항목 없음',
  optimizationScope: '최적화 범위',
  provisionVolume: '스토리지 볼륨 추가',
  autoVolume: '자동 볼륨',
  triggerThreshold: '임계값',
  dataVolume: '데이터 볼륨',
  createBackupPlan: '백업 계획 생성',
  editBackupPlan: '백업 계획 편집',
  executionSchedule: '실행 일정',
  concurrentThreads: '동시 스레드',
  addQueryPlan: '쿼리 계획 추가',
  editQueryPlan: '쿼리 계획 편집',
  connectionInformation: '연결 정보',
  standardParameters: '표준 매개변수',
  syncingConfiguration: '설정 동기화 중',
  noPlanData: '플랜 데이터 없음',
  configuration: '설정',
  autoBackupLog: '자동 백업 로그',
  autoVolumeLog: '자동 볼륨 로그',
  autoQueryLog: '자동 쿼리 로그',
  filterLogs: '로그 필터...',
  auditHistoryFor: (db) => `감사 기록: ${db}`,
  noLog: '로그 없음',

  yes: '예',
  no: '아니오',
  ready: '준비됨',
  active: '활성',
  options: '옵션',
  locks: '잠금',
  size: '크기',
  regionLocale: '지역 로케일',
  noSessions: '세션 없음',
  noActiveTransactions: '활성 트랜잭션이 없습니다.',
  noObjectLocks: '객체 잠금 없음',
  noHeldObjectLocks: '보유된 객체 잠금이 없습니다.',
  failedToGetLockInfo: '잠금 정보를 가져오지 못했습니다.',
  leaveBlankNoPassword: '비밀번호 없음은 비워 두세요',
  repeatPassword: '비밀번호 확인',
  addVolume: '볼륨 추가',
  clickAddVolumeHint: '"볼륨 추가"를 클릭하여 추가 스토리지 세그먼트를 할당하세요.',
  identifier: '식별자',
  segment: '세그먼트',
  sizeMb: '크기(MB)',
  absolutePath: '절대 경로',
  autoStart: '자동 시작',
  totalVolumes: '전체 볼륨',
  genericVolume: '일반 볼륨',
  logVolume: '로그 볼륨',
  volumeTypeData: '데이터',
  volumeTypeIndex: '인덱스',
  volumeTypeTemp: '임시',
  operationInterrupted: '작업 중단됨',
  operationFailed: '작업 실패',
  operationComplete: '작업 완료',
  transactionDropped: '트랜잭션 중단됨',
  copyCompleted: '복사 완료',
  snapshotInProgress: '스냅샷 진행 중',
  snapshotSecured: '스냅샷 저장됨',
  backupSubtitle: '데이터베이스 볼륨의 영구 스냅샷을 생성합니다',
  storageConfiguration: '스토리지 구성',
  revisionId: '리비전 ID',
  backupDirectory: '백업 디렉터리',
  restoringDatabase: '데이터베이스 복원 중',
  reconstructingInstance: '인스턴스 재구성 중',
  restoreCompleted: '복원 완료',
  recoveryFailed: '복구 실패',
  restoreSubtitle: '인스턴스를 이전 스냅샷으로 되돌립니다',
  databaseMustBeStopped: '복원 전에 데이터베이스를 중지해야 합니다',
  targetInstance: '대상 인스턴스',
  snapshotCatalog: '스냅샷 카탈로그',
  scanningCatalog: '카탈로그 검색 중…',
  restoreOptions: '복원 옵션',
  applyIntermediateLogs: '중간 아카이브 로그 적용',
  pathOverride: '경로 재정의',
  restoreInPlaceHint: '비워 두면 제자리 복원',
  renamingDatabase: '데이터베이스 이름 변경 중',
  updatingIdentity: '식별자 업데이트 중',
  renameComplete: '이름 변경 완료',
  renameSuccessful: '이름 변경 성공',
  renameFailed: '이름 변경 실패',
  executeRename: '이름 변경 실행',
  retryRename: '이름 변경 재시도',
  sourceDatabase: '원본 데이터베이스',
  currentIdentifier: '현재 식별자',
  targetIdentifier: '대상 식별자',
  destructiveOptions: '위험 옵션',
  overwriteExistingTarget: '기존 대상 덮어쓰기',
  overwriteTargetDesc: '대상 경로가 이미 있으면 강제 삭제',
  overwriteTargetWarning: '마이그레이션 시작 전 대상 경로의 기존 디렉터리가 영구 삭제됩니다.',
  renameDowntimeHint: '이름 변경 전 데이터베이스 서비스를 완전히 중지하세요.',
  synchronizingVolumes: '볼륨 동기화 중',
  cloningComplete: '복제 완료',
  cloningFailed: '복제 실패',
  cloneSubtitle: '볼륨 및 환경 레지스트리 복제',
  cloningContext: '복제 컨텍스트',
  targetEnvironment: '대상 환경',
  executionStrategy: '실행 전략',
  overwriteExistingEnvironment: '기존 환경 덮어쓰기',
  transformToMove: '이동 작업으로 변환',
  executeCopy: '복사 실행',
  consolidatingBlocks: '블록 통합 중',
  optimizationComplete: '최적화 완료',
  optimizationPipeline: '최적화 파이프라인',
  executionOptions: '실행 옵션',
  executeCompaction: '압축 실행',
  retryOptimization: '최적화 재시도',
  verboseMonitoring: '상세 모니터링',
  verboseMonitoringDesc: '사후 감사를 위한 실시간 OID 변환 로그',
  executingHeuristics: '휴리스틱 실행 중',
  executionInterrupted: '실행 중단됨',
  performanceTuningSubtitle: '쿼리 실행 계획 최적화',
  optimizerIntel: '옵티마이저 정보',
  targetInstanceSection: '대상 인스턴스',
  applyChanges: '변경 적용',
  updateSuccessful: '업데이트 성공',
  configurationReIndexed: '설정 재인덱싱됨',
  updateRejected: '업데이트 거부됨',
  synchronizationHalted: '동기화 중단됨',
  updatingRegistry: '레지스트리 업데이트 중',
  syncingRegistrySubtitle: '호스트 런타임의 cubrid.conf를 패치하고 인덱스를 동기화합니다.',
  navigation: '탐색',
  context: '컨텍스트',
  loadingLabel: '로딩',
  queryingHostRegistry: '호스트 런타임 레지스트리 조회 중…',
  brokerConnection: '브로커 연결',
  brokerIp: '브로커 IP',
  publicAddress: '공개 주소',
  servicePort: '서비스 포트',
  activeBroker: '활성 브로커',
  textEncoding: '텍스트 인코딩',
  charset: '문자 집합',
  synchronizationNotice: '동기화 안내',
  brokerParamsNotice: '브로커 매개변수는 Web Manager가 CUBRID Broker와 통신하는 방식을 정의합니다. 변경은 Manager-호스트 동기화에만 영향을 줍니다.',
  lockingSection: '잠금',
  transactionSection: '트랜잭션',
  systemSection: '시스템',
  advancedHeuristics: '고급 휴리스틱',
  databaseProperties: '데이터베이스 속성',
  initializingSchedule: '일정 초기화 중',
  committingAutomation: '자동화 적용 중',
  scheduleCommitted: '일정 등록됨',
  automationActive: '자동화 활성',
  executionError: '실행 오류',
  initializeCycle: '주기 초기화',
  abstractionLevel: '추상화 수준',
  planRegistryId: '계획 레지스트리 ID',
  payloadPath: '페이로드 경로',
  rotationLogic: '로테이션 로직',
  targetTime: '대상 시간',
  standard24hCycle: '표준 24시간 주기',
  registryDate: '레지스트리 날짜',
  optimizationMatrix: '최적화 매트릭스',
  rotationRetention: '로테이션 보존',
  deleteBackupPlan: '백업 계획 삭제',
  deleteQueryPlan: '쿼리 계획 삭제',
  deletingQueryPlan: '쿼리 계획 삭제 중',
  removingRegistry: '레지스트리 제거 중',
  deletionSuccess: '삭제 성공',
  registryPurged: '레지스트리 제거됨',
  queryPlanRemovedMsg: '쿼리 계획이 시스템 스케줄러에서 제거되었습니다.',
  deletionFailed: '삭제 실패',
  signalRejected: '신호 거부됨',
  deletionSignalFailed: '이 쿼리 계획에 대한 삭제 신호를 완료하지 못했습니다.',
  retryDeletion: '삭제 재시도',
  dangerousDiscardQueryPlan: '위험: 쿼리 계획 폐기',
  permanentRemovalSql: 'SQL 자동화 레지스트리 영구 제거',
  executeDiscard: '폐기 실행',
  discardQueryStrategy: '쿼리 전략을 폐기하시겠습니까?',
  planRetirement: '계획 폐기',
  planCacheDumpTitle: '플랜 캐시 덤프',
  loadingParameters: '매개변수 로딩 중',
  parameter: '매개변수',
  serverValue: '서버 값',
  clientValue: '클라이언트 값',
  failedToGetDbParams: '데이터베이스 매개변수를 가져오지 못했습니다.',
  message: '메시지',
  activeContext: '활성 컨텍스트',
  offlineStatic: '오프라인 정적',
  noConfigParameters: '이 인스턴스에 대한 설정 매개변수가 없습니다.',
  parameterDumpSubtitle: '매개변수 값을 확인합니다',
  environmentReady: '환경 준비됨',
  analysisPipeline: '분석 파이프라인',
  comparativeAnalysis: '비교 분석',
  comparativeAnalysisDesc: '클라이언트/서버 힙 모두 추출',
  loadingBrokerStatus: '브로커 상태 로딩 중…',
  basicInformation: '기본 정보',
  lastAccess: '마지막 접근',
  clientIp: '클라이언트 IP',
  jobId: '작업 ID',
  priority: '우선순위',
  elapsed: '경과',
  request: '요청',
  activeCount: (n) => `${n}개 활성`,
  queuedCount: (n) => `${n}개 대기`,
  downloadAllLogs: '로드된 모든 로그를 단일 파일로 다운로드',
  setAutomationVolume: '자동화 볼륨 설정',
  addStorageVolume: '스토리지 볼륨 추가',
  editBackupPlanTitle: '백업 계획 편집',
  deleteBackupPlanTitle: '백업 계획 삭제',
  runBackup: '백업 실행',
  retryBackup: '백업 재시도',
  backupCompleted: '백업 완료',
  backupFailed: '백업 실패',
  targetDatabase: '대상 데이터베이스',
  executeRestore: '복원 실행',
  retryRecovery: '복구 재시도',
  restoreSuccessful: '복원 성공',
  initiateCopy: '복사 시작',
  retryClone: '복제 재시도',
  executeOptimization: '최적화 실행',
  retryExecution: '실행 재시도',
  volumeAllocation: '볼륨 할당',
  scalingFoundation: '기반 확장 중',
  allocationSuccessful: '할당 성공',
  storageExpanded: '스토리지 확장됨',
  allocationInterrupted: '할당 중단됨',
  scalingFailed: '확장 실패',
  storageOptimization: '스토리지 최적화',
  allocationStrategy: '할당 전략',
  instanceRegistry: '인스턴스 레지스트리',
  privilegedOperation: '권한 작업',
  extendDiskCapacity: (db) => `${db} 디스크 용량 확장`,
  historyForDatabase: (db) => `데이터베이스 기록: ${db}`,
  globalBackupHistory: '전역 백업 기록',
  dumpingPlanCache: '플랜 캐시 덤프 중',
  displayQueryPlan: '쿼리 플랜 표시',
  dumpingPlanCacheSubtitle: '서버에서 XASL 플랜 캐시 읽는 중...',
  runDumpHint: '덤프를 실행하여 쿼리 플랜 캐시 항목을 확인하세요.',
  backupId: '백업 ID',
  logTime: '로그 시간',
  description: '설명',

  actionMenu: '작업',
  configParam: '설정 매개변수',
  editCmConfig: 'CM 설정 편집',
  reportBug: '버그 보고',
  cubridOnlineForum: 'CUBRID 온라인 포럼',
  cubridToolsDevelopment: 'CUBRID 도구 개발',
  checkForUpdates: '업데이트 확인',

  globalHealthOverview: '전역 상태 개요',
  hostsLabel: '호스트',
  activeLabel: '활성',
  unknownHost: '알 수 없는 호스트',
  localhost: '로컬호스트',
  statusOn: '켜짐',
  statusOff: '꺼짐',
  synchronizingServices: '서비스 동기화 중',
  stopServices: '서비스 중지',
  startServicesConfirmTitle: '서비스 시작',
  startServicesConfirmDesc: (server) => `호스트 "${server}"의 모든 CUBRID 서비스를 시작하시겠습니까?`,
  stopServicesConfirmTitle: '서비스 중지',
  stopServicesConfirmDesc: (server) =>
    `호스트 "${server}"의 모든 CUBRID 서비스를 중지하시겠습니까? 활성 브로커와 데이터베이스가 모두 종료됩니다.`,
  startingServicesOn: (server) => `${server}에서 서비스 시작 중`,
  stoppingServicesOn: (server) => `${server}에서 서비스 중지 중`,
  serviceStartRejected: '호스트 에이전트가 서비스 시작 명령을 거부했습니다.',
  serviceStopFailed: '서비스 종료에 실패했습니다. 에이전트 로그를 확인하세요.',
  connectHostForMonitoring: '탐색기에서 호스트 서버에 연결하면 전역 리소스 모니터링이 활성화됩니다.',
  permanentTemp: '영구 임시',
  tempTemp: '임시',
  userLabel: '사용자',
  haMaster: '마스터',
  haSlave: '슬레이브',
  haReplica: '레플리카',
  clusterOverview: '클러스터 개요',

  databaseDashboard: '데이터베이스 대시보드',
  refreshDatabaseStatus: '데이터베이스 상태 새로 고침',
  exportMetricsCsv: '지표를 CSV로 내보내기',
  restartingCas: 'CAS 재시작 중',
  resettingCasProcess: '브로커 애플리케이션 서버 프로세스 재설정 중',
  loadingDashboard: '대시보드 로딩 중…',
  restartCasConfirm: (cas, broker) => `브로커 ${broker}의 CAS ID ${cas}를 재시작하시겠습니까?`,

  performanceMetrics: '성능 지표',
  realTime: '실시간',
  transPerSec: '트랜잭션/초',
  queriesPerSec: '쿼리/초',
  bufferHit: '버퍼 히트',
  fetchesPerSec: 'Fetch/초',
  dirtyPerSec: 'Dirty/초',
  ioReadsPerSec: 'IO 읽기/초',
  ioWritesPerSec: 'IO 쓰기/초',
  storageVolumes: '스토리지 볼륨',
  volumeLabel: '볼륨',
  purpose: '용도',
  spaceUsage: '공간 사용량',
  modifiedLabel: '수정일',
  pathLabel: '경로',
  fileDistribution: '파일 분포',
  logicalPartitioning: '논리적 파티셔닝',
  filesLabel: '파일',
  usedLabel: '사용',
  fileTable: '파일 테이블',
  reservedLabel: '예약',
  totalLabel: '합계',
  casBrokers: 'CAS 브로커',
  readyCount: (n) => `${n}개 준비`,
  busyCount: (n) => `${n}개 사용 중`,
  lastConn: '마지막 연결',
  sqlLogs: 'SQL 로그',
  slowQueryLogs: '느린 쿼리 로그',
  restartCasTitle: 'CAS 재시작',
  lockMode: '잠금 모드',
  activeLog: '활성 로그',
  archiveLog: '아카이브 로그',
  longTran: '장기 트랜',
  longQuery: '장기 쿼리',
  errQuery: '오류 쿼리',
  reqLabel: 'REQ',
  jqLabel: 'JQ',
  asLabel: 'AS',

  systemStatus: '시스템 상태',
  nowLabel: '현재',
  fiveMinAvg: '5분 평균',
  resume: '재개',
  haClusterStatus: 'HA 클러스터 상태',
  nodesActiveInCluster: (n) => `클러스터에 ${n}개 노드 활성`,
  environmentUnavailable: '환경 정보를 사용할 수 없습니다',

  language: '언어',
  languageEn: 'English',
  languageKo: '한국어',
};
