/**
 * UI labels aligned with CUBRID Manager (Admin) RCP.
 * Source: cubrid-manager .../cubrid/database/Messages.properties, spi/Messages.properties, common/Messages.properties
 *
 * Static English export — use useCM() in components for locale-aware labels.
 */
export const CM = {
  ok: 'OK',
  cancel: 'Cancel',
  close: 'Close',
  refresh: 'Refresh',
  confirm: 'Confirm',
  error: 'Error',
  warning: 'Warning',
  success: 'Success',
  failure: 'Failure',

  loginDatabase: 'Login Database',
  loginDatabaseMsg: 'Log into the selected database.',
  loggingInto: (db) => `Logging into "${db}" database...`,
  connectionSuccessful: 'The connection was successful.',
  userName: 'User name',
  password: 'Password',
  databaseName: 'Database name',
  savePassword: 'Save Password',

  transactionInformation: 'Transaction information',
  activeTransactionsOf: 'Active transactions of database:',
  tranIndex: 'Tran index',
  userNameCol: 'User name',
  host: 'Host',
  processId: 'Process id',
  programName: 'Program name',
  killTransaction: 'Kill transaction',
  killTransactionTitle: 'Kill Transaction',
  killType: 'Kill type',
  killSelectedOnly: 'Kill the selected transaction only',
  killSameUser: 'Kill all transactions associated with the same user',
  killSameHost: 'Kill all transactions associated with the same client host',
  killSameProgram: 'Kill all transactions associated with the same program name',
  killSuccess: 'Transaction has been successfully killed.',
  killParamResolveErrorMsg: 'Could not resolve kill parameter for the selected transaction.',

  lockingInformation: 'Locking Information',
  lockSettingClientInfo: 'Lock setting/client information',
  objectLockTable: 'Object lock table',
  lockAndTransaction: 'Lock and Transaction',
  loadingLockAndTransaction: 'Loading lock and transaction information...',
  lockIndex: 'Index',
  pname: 'Pname',
  uid: 'Uid',
  pid: 'Pid',
  isolationLevel: 'Isolation level',
  timeOut: 'Time out',
  oid: 'Oid',
  objectType: 'Object type',
  mode: 'Mode',
  numHolders: 'Num holders',
  numBlockedHolders: 'Num blocked holders',
  numWaiters: 'Num waiters',
  lockEscalation: 'Lock escalation',
  runDeadlockInterval: 'Run deadlock interval',
  currentLockedObjNum: 'Current number of objects which are locked',
  maxLockedObjNum: 'Maximum number of objects which can be locked',
  waitingSuffix: ' (waiting)',

  checkDatabase: 'Check Database',
  checkDatabaseDesc:
    'Verifies a database. If inconsistencies are found, please contact CUBRID Support to help interpret the output and address any indicated problem so that it will not reoccur.',
  repairWhenInconsistency: 'Repair when inconsistency is found',
  jobCompletedSuccess: (job) => `Job ${job} has been completed successfully`,

  createDatabase: 'Create Database',
  deleteDatabase: 'Delete Database',
  deleteDatabaseConfirm: 'Are you sure you want to delete this database?',
  backupDatabase: 'Backup Database',
  restoreDatabase: 'Restore Database',
  compactDatabase: 'Compact Database',
  optimizeDatabase: 'Optimize Database',
  copyDatabase: 'Copy Database',
  renameDatabase: 'Rename Database',
  loadDatabase: 'Load Database',
  unloadDatabase: 'Unload Database',
  dbaConfirm: 'DBA confirm',
  dbaPassword: 'DBA password',

  manageDatabase: 'Manage Database',
  databaseInfo: 'Database Info',
  usedParameterDump: 'Used Parameter Dump',
  planCacheDump: 'Plan Cache Dump',

  manageDatabaseMenu: {
    unload: 'Unload Database...',
    load: 'Load Database...',
    create: 'Create Database...',
    check: 'Check Database',
    compact: 'Compact Database',
    optimize: 'Optimize Database',
    copy: 'Copy Database',
    rename: 'Rename Database',
    restore: 'Restore Database',
    backup: 'Backup Database',
    delete: 'Delete Database',
  },

  // Create Database (createdb wizard)
  createDatabaseMsg: 'Create a new database.',
  createDbJobComplete: (job) => `Job ${job} has been completed.`,
  createDbFailed: 'Failed to start the database. Please verify that the connection credentials are correct.',
  databaseInitializedMsg: (dbName) => `Database "${dbName}" has been successfully initialized and commissioned.`,
  databaseCreationErrorMsg: 'An unexpected error occurred during database creation.',
  systemBadge: 'System',
  criticalBadge: 'Critical',
  startAfterCreationLabel: 'Start database after creation',
  startAfterCreationDesc: 'Automatically start the database when creation completes',
  extraVolumesDesc: 'Optionally add extra data or temporary volumes to the database.',
  noAdditionalVolumesMsg: 'No additional volumes',
  volumeNumberLabel: (idx) => `Volume ${idx}`,
  autoVolumeExpansionTitle: 'Auto Volume Expansion',
  autoVolumeExpansionDesc: "When a volume's free space drops below the threshold, CUBRID automatically appends additional pages to keep the database running.",
  dataIndexAutoExpansionPolicy: 'data & index auto-expansion policy',
  warningThresholdLabel: 'Warning threshold',
  ratioHintText: 'Ratio 0–1 (e.g. 0.15 = 15% free)',
  extensionSizeLabel: 'Extension size',
  pagesPerExtensionDesc: 'Number of pages to add per extension',
  dbaPasswordSetupDesc: 'Set a password for the dba administrator account. Leave blank for no password.',
  reviewConfigBeforeCreateDesc: 'Review your configuration below before creating the database. Once confirmed, the process cannot be undone.',
  ratioSuffixLabel: 'ratio (0–1)',
  pagesPerExtensionSuffix: 'pages per extension',
  wizardGeneral: 'General Information',
  wizardAdditionalVol: 'Additional Volume Information',
  wizardAutoVol: 'Automatic volume extension',
  wizardSetDbaPass: 'Set DBA Password',
  wizardDbInfo: 'Database Information',
  wizardDbInfoList:
    'You have completed the steps required to create a new database. The new database will be created according to the below preferences.',
  pageSize: 'Page size (byte)',
  logPageSize: 'Log page size (byte)',
  localeCharset: 'Charset',
  userDefined: 'User Defined',
  volumeSize: 'Volume size (Mbyte)',
  genericVolInfo: 'Generic Volume Information',
  genericVolPath: 'Generic volume path',
  logVolInfo: 'Log Volume Information',
  logVolPath: 'Log volume path',
  volumeName: 'Volume name',
  volumePath: 'Volume path',
  volumeType: 'Volume type',
  autoStartDb: 'Auto start database when start the cubrid service',
  passwordConfirm: 'Password Confirm',
  setPassword: 'Set Password',
  readyToCreate: 'Ready to create',
  back: 'Back',
  next: 'Next',
  finish: 'Finish',

  // Unload Database (unloaddb)
  unloadDatabaseMsg: 'Unload the selected database.',
  unloadSuccess: 'The database have been unloaded successfully.',
  unloadResultTitle: 'Unload Database Result',
  unloadResultMsg: 'Below you can view the unload database result informaton.',
  grpDbInfo: 'Database Information',
  targetDbName: 'Target database name',
  targetDirectory: 'Target directory',
  unloadTarget: 'Unload Target',
  unloadOption: 'Unload Option',
  unloadTableScope: 'Tables',
  unloadIncludeLabel: 'Include',
  includeSchema: 'Include Schema',
  includeData: 'Include Data',
  all: 'All',
  selectedTables: 'Selected tables',
  useDelimitedIdentifier: 'Use delimited identifier ("")',
  includeReferencedTables: 'Include referenced tables',
  prefixOutputFiles: 'Prefix for output files',
  fileForHash: 'File for hash',
  numCachedPages: 'Number of cached pages',
  estimatedInstances: 'Estimated number of instances',
  loFileCountPerDir: 'Lo file count per a directory',
  availableClasses: 'Available Classes',

  // Load Database (loaddb)
  loadDatabaseMsg: 'Load the selected database.',
  loadResultTitle: 'Load Database Result',
  loadResultMsg: 'Below you can view the load database result information.',
  unloadedFiles: 'Unloaded Files',
  loadType: 'Load Type',
  path: 'Path',
  date: 'Date',
  selectFromList: 'Select unloaded file from list',
  selectFromRemote: 'Select unloaded file from remote system',
  selectFromLocal: 'Select unloaded file from local system',
  loadOption: 'Load Option',
  loadSchema: 'Load schema',
  loadObject: 'Load object',
  loadIndex: 'Load index',
  loadTrigger: 'Load trigger',
  checkSyntaxAndLoad: 'Check syntax and load database',
  insertionCountPeriodicCommit: 'Insertion count for periodic commit',
  dontUseOid: "Don't use OID",
  dontUpdateStatistics: "Don't update statistics",
  usingErrorControlFile: 'Using error control file',
  ignoredTableFile: 'Ignored table file',
  loadDbTask: 'Load Database',

  // Common actions
  save: 'Save',
  retry: 'Retry',
  dismiss: 'Close',
  apply: 'Apply',
  discard: 'Discard',
  connect: 'Connect',
  loginAll: 'Login All',
  disconnect: 'Disconnect',
  tryAgain: 'Try Again',
  add: 'Add',
  edit: 'Edit',
  remove: 'Remove',
  startLabel: 'Start',
  stopLabel: 'Stop',
  restart: 'Restart',
  processing: 'Running...',
  pleaseWait: 'Please wait...',
  selectAll: 'Select All',
  name: 'Name',
  address: 'Address',
  port: 'Port',
  status: 'Status',
  type: 'Type',
  value: 'Value',
  actions: 'Actions',
  live: 'Live',
  paused: 'Paused',
  identity: 'Identity',
  credentials: 'Credentials',
  username: 'Username',
  newPassword: 'New Password',
  leaveBlankToKeep: 'Leave blank to keep current password',
  passwordsDoNotMatch: 'Passwords do not match',
  hostNameRequired: 'Host name is required',
  addressRequired: 'Address is required',
  portRequired: 'Port is required',
  usernameRequired: 'Username is required',
  passwordRequired: 'Password is required',

  // App / tabs / loading
  appName: 'CUBRID Manager',
  selectHostHint: 'Select a host from the sidebar to start monitoring databases, brokers, and logs.',
  hostManagement: 'Host Management',
  volumeMonitor: 'Volume Monitor',
  performance: 'Performance',
  lockInfo: 'Lock Info',
  systemReady: 'System Ready',
  managerAccess: 'Manager Access',
  managerError: 'Manager Error',
  brokerStatus: 'Broker Status',
  processingDbRequest: 'Processing database request...',
  processingRequest: 'Processing your request, please wait...',
  cmsJobRunningInBackground: (target, statusHint = '') =>
    `${target}${statusHint} — running in background`,
  backgroundJobsTitle: 'Background jobs',
  backgroundJobsRunning: (n) => `${n} running`,
  backgroundJobsEmpty: 'No background jobs',
  clearCompletedJobs: 'Clear completed',
  jobStatusQueued: 'Queued',
  jobStatusRunning: 'Running',
  jobStatusSucceeded: 'Completed',
  jobStatusFailed: 'Failed',
  jobNotifySucceeded: (op, db) => `${op} completed — ${db}`,
  jobNotifyFailed: (op, db) => `${op} failed — ${db}`,
  jobTypeUnload: 'Unload',
  jobTypeLoad: 'Load',
  jobTypeCreate: 'Create database',
  jobTypeOptimize: 'Optimize',
  jobTypeCheck: 'Check',
  jobTypeCompact: 'Compact',
  jobTypeCopy: 'Copy',
  jobTypeAddVol: 'Add volume',
  jobTypeRename: 'Rename',
  jobTypeBackupDb: 'Backup',
  databaseAction: 'Database Action',
  brokerAction: 'Broker Action',
  actionFailed: 'Action Failed',
  updateFailed: 'Update Failed',
  updateInterrupted: 'Update Interrupted',
  applyingChanges: 'Applying Changes...',
  startingDatabase: (db) => `Starting database: ${db}`,
  startingBroker: (b) => `Starting broker: ${b}`,
  startingService: 'Starting Service',
  stoppingService: 'Stopping Service',
  startingDbNamed: (db) => `Starting database : ${db}`,
  stoppingDbNamed: (db) => `Stopping database : ${db}`,
  startingBrokerNamed: (b) => `Starting Broker: ${b}`,
  stoppingBrokerNamed: (b) => `Stopping Broker: ${b}`,
  startBrokerLine: (name) => `Start broker : ${name}`,
  stopBrokerLine: (name) => `Stop broker : ${name}`,
  serviceStartWait: 'Please wait while we start all brokers and databases...',
  serviceStopWait: 'Please wait while we stop all brokers and databases...',
  editConfigTab: (name) => `Edit ${name}`,
  allLogsTab: (name) => `All Logs: ${name}`,
  allServerLogsTab: (name) => `All Server Logs: ${name}`,
  statusTab: (name) => `Status: ${name}`,
  spaceTab: (db) => `Space: ${db}`,
  volumeTab: (path) => `Volume: ${path}`,
  volumesTab: (cat) => `Volumes: ${cat.replace(/_/g, ' ')}`,
  brokerConfig: 'Broker Config',
  serviceDashboard: 'Service Dashboard',

  // Header / menus
  file: 'File',
  view: 'View',
  service: 'Service',
  database: 'Database',
  broker: 'Broker',
  addHost: 'Add Host',
  changeHost: 'Change Host',
  exportHost: 'Export Host',
  importHost: 'Import Host',
  exportHosts: 'Export Hosts',
  importHosts: 'Import Hosts',
  importHostsXml: 'Import Hosts XML',
  tools: 'Tools',
  hostServiceManagement: 'Host Service Management',
  help: 'Help',
  aboutCubridAdmin: 'About CUBRID Admin',
  aboutCubrid: 'About CUBRID',
  cubridWebManager: 'CUBRID Web Manager',
  systemDetails: 'System Details',
  coreVersion: 'Core Version',
  certifiedStable: 'Certified Stable',
  startService: 'Start Service',
  stopService: 'Stop Service',
  startStopService: 'Start/Stop Service',
  startStopDatabase: 'Start/Stop Database',
  startStopBroker: 'Start/Stop Broker',
  editCubridConfig: 'Edit Cubrid Config',
  logout: 'Logout',
  startSelectedDbBroker: 'Start selected database / broker',
  switchToDarkMode: 'Switch to dark mode',
  switchToLightMode: 'Switch to light mode',

  // Sidebar
  addYourFirstHost: 'Add your first host',
  connectToCubridServer: 'Connect to a CUBRID server',
  hostLogin: 'Host login',
  establishingSession: 'Establishing secure session...',
  connectionFailed: 'Connection failed',
  connectionLost: 'Connection Lost',
  reconnect: 'Reconnect',
  reconnectPrompt: 'Your session was disconnected, possibly because the token expired or another user logged into this host. Click Reconnect to attempt to re-establish the connection.',
  editHost: 'Edit Host',
  deleteHost: 'Delete Host',
  changePassword: 'Change Password',
  userManagement: 'User Management',
  cmsAccountManagement: 'CMS Account Management',
  serverVersion: 'Server Version',
  serverColon: (s) => `Server: ${s}`,
  databaseColon: (db) => `Database: ${db}`,
  allDatabases: 'All Databases',
  allBrokers: 'All Brokers',
  brokerColon: (b) => `Broker: ${b}`,
  startDatabase: 'Start Database',
  stopDatabase: 'Stop Database',
  startAllDatabases: 'Start All Databases',
  stopAllDatabases: 'Stop All Databases',
  restartAllDatabases: 'Restart All Databases',
  startAllBrokers: 'Start All Brokers',
  stopAllBrokers: 'Stop All Brokers',
  restartAllBrokers: 'Restart All Brokers',
  editBrokerConfig: 'Edit Broker Config',
  showStatus: 'Show Status',
  startBroker: 'Start Broker',
  stopBroker: 'Stop Broker',
  paramDump: 'Param Dump...',
  planDump: 'Plan Dump...',
  properties: 'Properties',
  databaseInfoMenu: 'Database Info',

  // Sidebar tree
  users: 'Users',
  jobAutomation: 'Job automation',
  backupPlan: 'Backup Plan',
  queryPlan: 'Query Plan',
  space: 'Space',
  log: 'Log',
  access: 'Access',
  adminLog: 'Admin Log',
  manager: 'Manager',
  accessLog: 'Access log',
  errorLog: 'Error log',
  serverLogs: 'Server logs',
  sqlLog: 'SQL Log',
  noHostSelectedTitle: 'No Host Selected',
  selectServerFromList: 'Select a server from the list above to view details.',
  serverListAbove: 'Server list above',
  admin: 'Admin',
  managerConsole: 'Manager Console',

  // Breadcrumb / footer
  closeTab: 'Close Tab',
  closeOtherTabs: 'Close Other Tabs',
  closeAllTabs: 'Close All Tabs',
  reloadTab: 'Reload Tab',
  connectedTo: (host) => `Connected to ${host}`,
  noHostSelected: 'No host selected',
  version: 'Version',

  // Host modals
  newConnection: 'New Connection',
  friendlyName: 'Alias',
  ipAddressDomain: 'IP Address / Domain',
  modifyHost: 'Modify Host',
  removeHostConnection: 'Remove Host Connection',
  keepHost: 'Keep Host',
  confirmRemoval: 'Confirm Removal',
  activeConnectionsTerminated: 'Active connections to this host will be terminated.',
  changeManagerPasscode: 'Change Manager Passcode',
  newPasscode: 'New Passcode',
  verifyNewPasscode: 'Verify New Passcode',
  cubridVersion: 'CUBRID Version',
  environmentDetails: 'Environment Details',
  osPlatform: 'OS Platform',
  installPath: 'Install Path',
  haPeersDiscovered: 'HA Peers Discovered',
  peerNodes: 'Peer Nodes',
  haNoGroupPromptTitle: 'This host isn\'t in a group yet',
  haNoGroupPromptDesc: 'Create a group for this HA cluster so peer nodes you add are placed together automatically.',
  haNewGroupNamePlaceholder: 'e.g. HA Cluster',
  createGroupAndContinue: 'Create Group',
  haGroupCreatedNotice: (name) => `New peers will be added to "${name}".`,
  editUser: 'Edit user',
  deleteUser: 'Delete user',
  addUser: 'Add User',
  fullSystemAuth: 'Full system authorization',
  primaryAdminCannotDelete: 'The primary administrator account cannot be deleted.',
  noAccess: 'none',
  monitorOnly: 'monitor',
  fullControl: 'admin',
  permissions: 'Permissions',
  brokerAuthority: 'Broker Authority',
  monitoringPermission: 'Status monitor authority:',
  dbCreatePermission: 'DB creation authority:',
  brokerPermission: 'Broker authority:',

  // Server dashboard
  serverDashboard: 'Server Dashboard',
  refreshDashboard: 'Refresh dashboard',
  syncedAt: (t) => `Synced ${t}`,
  databases: 'Databases',
  autoStartup: 'Auto Startup',
  systemStatusError: 'System Status Error',
  period: 'Period',
  memory: 'Memory',
  disk: 'Disk',
  cpu: 'CPU',
  tps: 'TPS',
  qps: 'QPS',
  accessPoint: 'Access Point',
  authUser: 'Auth User',
  operatingSystem: 'Operating System',
  cubridEngine: 'CUBRID Engine',
  homeDirectory: 'Home Directory',
  notApplicableFallback: 'N/A',
  permanent: 'Permanent',
  temporary: 'Temporary',
  freeStorage: 'Free Storage',
  refreshBrokersList: 'Refresh brokers list',
  startServices: 'Start Services',
  stopAllServices: 'Stop All Services',
  sensorsOffline: 'Sensors Offline',
  serviceError: 'Service Error',
  groupHost: 'GROUP/HOST',
  dbStatus: 'DB STATUS',
  undoChanges: 'Undo changes',
  saveChanges: 'Save changes',
  testConnectionAndSave: 'Test Connection & Save',
  reloadConfig: 'Reload config',
  modified: 'Modified',
  sourceEditor: 'Source Editor',
  configPlaceholder: '# Configuration content...',
  tableEditor: 'Table Editor',

  // Auth
  signIn: 'Sign In',
  authorizeAccess: 'Login',
  rememberDevice: 'Remember this device',
  authenticationFailed: 'Authentication Failed',
  createAccount: 'Create Account',
  backToLogin: 'Back to Login',
  accountRecovery: 'Account Recovery',
  resetCredentials: 'Reset your access credentials.',
  registrationFailed: 'Registration failed. Please try again.',
  loginFailedMsg: 'Login failed. Please check your credentials.',
  passwordStrengthWeak: 'Weak',
  passwordStrengthAverage: 'Average',
  passwordStrengthGood: 'Good',
  passwordStrengthStrong: 'Strong',
  minChars3: 'At least 3 characters',

  // Broker UI
  brokerProperties: 'Broker Properties',
  common: 'Common',
  advanced: 'Advanced',
  reset: 'Reset',
  propertyName: 'Property Name',
  propertyLabel: 'Property',
  brokerNumberFallback: (n) => `Broker ${n}`,
  propertiesBrokersCountLabel: (props, brokers) => `${props} properties · ${brokers} brokers`,
  runtimeConfiguration: 'Runtime Configuration',
  synchronizing: 'Synchronizing…',
  failedToLoadStatus: 'Failed to load status',
  refreshBrokerStatus: 'Refresh broker status',
  downloadExcel: 'Download as Excel',
  copyToClipboard: 'Copy to clipboard',
  copyStatement: 'Copy statement',
  refreshLog: 'Refresh Log',
  monitoring: 'Monitoring',
  copyVisibleEntries: 'Copy visible entries to clipboard',
  connected: 'Connected',
  jobQueue: 'Job Queue',
  autoAddAS: 'Auto Add AS',
  sqlLogMode: 'SQL Log Mode',
  longTranLabel: 'Long Trans',
  longQueryLabel: 'Long Query',
  rawLog: 'Raw Log',
  parsedSQL: 'Parsed SQL',
  topSQL: 'Top SQL',

  // Database modals (extra)
  criticalWarning: 'Critical Warning',
  volumesToDelete: 'Volumes To Be Deleted',
  destructiveAction: 'Destructive Action',
  noBackupRecords: 'No Backup Records Found',
  newDatabaseName: 'New Database Name',
  downtimeRequired: 'Downtime Required',
  cloneDatabase: 'Copy Database',
  cloneIdentifier: 'Database Name',
  backupStrategy: 'Backup Strategy',
  backupDatabaseNameLabel: 'Database name:',
  volumeNameCol: 'Volume name:',
  backupInformation: 'Backup Information',
  backupHistoryInformation: 'Backup History Information',
  backupLevel: 'Backup level:',
  backupLevelColumn: 'Level',
  noBackupPlansTitle: 'No Backup Plans',
  noBackupPlansMsg: 'No automated backup schedules are registered for this database.',
  noQueryPlansTitle: 'No Query Plans',
  noQueryPlansMsg: 'No automated query plans are registered for this database.',
  backupDate: 'Last Backup Date',
  backupSizeColumn: 'Size (MB)',
  backupPath: 'Backup Path',
  backupHistoryListHint: 'Previous backup history Information',
  checkDatabaseConsistency: 'Check the database consistency',
  deleteArchivedLogs: 'Delete unnecessary log-archives',
  compressBackupVolume: 'Compress backup volumes',
  safeBackup: 'Safe backup for replication',
  parallelThreads: 'Parallel backup:',
  dynamicCompaction: 'Compact Database',
  compactDatabaseName: 'Database name:',
  compactDatabaseMessage: 'Compact Database',
  compactDescriptionInformation: 'Description',
  compactDatabaseDescription: 'This utility reclaims space from two sources\n\n-OIDs of deleted objects\n-multiple table representations',
  maintenanceTarget: 'Maintenance Target',
  compactionFailed: 'Compaction Failed',
  performanceTuning: 'Performance Tuning',
  noMatches: 'No Matches',
  optimizationScope: 'Optimization Scope',
  provisionVolume: 'Add Volume',
  autoVolume: 'Volume Auto Expansion',
  triggerThreshold: 'Trigger threshold',
  dataVolume: 'Data Volume',
  dataIndexVolume: 'Data + Index Volume',
  dataIndexVolumeDescription: 'Data and index volumes',
  autoVolumeEnabled: 'Volume Auto Expansion On',
  autoVolumeDisabled: 'Volume Auto Expansion Off',
  createBackupPlan: 'Create Backup Plan',
  editBackupPlan: 'Edit Backup Plan',
  executionSchedule: 'Execution Schedule',
  concurrentThreads: 'Concurrent Threads',
  addQueryPlan: 'Add Query Plan',
  editQueryPlan: 'Edit Query Plan',
  connectionInformation: 'Connection Information',
  standardParameters: 'Standard Parameters',
  syncingConfiguration: 'Syncing Configuration',
  noPlanData: 'No Plan Data',
  configuration: 'Configuration',
  autoBackupLog: 'Auto Backup Log',
  autoVolumeLog: 'Volume Auto Expansion Log',
  autoQueryLog: 'Auto Query Log',
  filterLogs: 'Filter logs…',
  auditHistoryFor: (db) => `Audit history for: ${db}`,
  noLog: 'No log',
  noBackupLogsFoundMsg: 'No backup logs found for the current criteria.',
  noExecutionLogsFoundMsg: 'No execution logs found for the current criteria.',
  noAutomationLogsFoundMsg: 'No automation logs found.',

  yes: 'Yes',
  no: 'No',
  ready: 'Ready',
  active: 'Active',
  options: 'Options',
  locks: 'Locks',
  size: 'Size',
  regionLocale: 'Region locale',
  noSessions: 'No sessions',
  noActiveTransactions: 'No active transactions.',
  noObjectLocks: 'No object locks',
  noHeldObjectLocks: 'No held object locks.',
  failedToGetLockInfo: 'Failed to get lock information.',
  leaveBlankNoPassword: 'Leave blank for no password',
  repeatPassword: 'Repeat password',
  addVolume: 'Add Volume',
  clickAddVolumeHint: 'Click "Add Volume" to add extra storage volumes.',
  identifier: 'Identifier',
  segment: 'Segment',
  sizeMb: 'Size MB',
  absolutePath: 'Absolute Path',
  autoStart: 'Auto-start',
  totalVolumes: 'Total volumes',
  genericVolume: 'Generic volume',
  logVolume: 'Log volume',
  volumeTypeData: 'Data',
  volumeTypeIndex: 'Index',
  volumeTypeTemp: 'Temp',
  operationInterrupted: 'Operation Interrupted',
  operationFailed: 'Operation Failed',
  operationComplete: 'Operation Complete',
  transactionDropped: 'Transaction Dropped',
  copyCompleted: 'Copy completed',
  snapshotInProgress: 'Backup In Progress',
  snapshotSecured: 'Backup Completed',
  backupSubtitle: 'Create a backup of the database volumes',
  storageConfiguration: 'Backup Information',
  revisionId: 'Backup Level',
  backupDirectory: 'Backup Directory',
  backupDirFetchError: 'Could not retrieve the default backup directory. Please enter the path manually.',
  levelNumberLabel: (level) => `Level${level}`,
  volumePathBackupDirRequiredMsg: 'Volume path and Backup directory are required.',
  databaseBackedUpMsg: (db, dir) => `Database "${db}" has been successfully backed up to "${dir}".`,
  restoringDatabase: 'Restoring Database',
  reconstructingInstance: 'Restoring Database',
  restoreCompleted: 'Restore Completed',
  recoveryFailed: 'Recovery Failed',
  restoreSubtitle: 'Restore the database from a backup',
  databaseMustBeStopped: 'Database must be stopped before restoration',
  targetInstance: 'Target Database',
  snapshotCatalog: 'Backup Information',
  scanningCatalog: 'Loading backup information…',
  restoreOptions: 'Recovery Options',
  applyIntermediateLogs: 'Perform partial recovery when archive logs are absent',
  pathOverride: 'Specify Recovery Path',

  renamingDatabase: 'Renaming Database',
  updatingIdentity: 'Updating Identity',
  renameComplete: 'Rename Complete',
  renameSuccessful: 'Rename Successful',
  renameFailed: 'Rename Failed',
  renameFailedMsg: 'Failed to rename database. Ensure the database is stopped.',
  databaseRenamedMsg: (db, newName) => `Database "${db}" has been renamed to "${newName}".`,
  executeRename: 'Execute Rename',
  retryRename: 'Retry Rename',
  sourceDatabase: 'Source Database',
  currentIdentifier: 'Current Name',
  targetIdentifier: 'New Name',
  destructiveOptions: 'Options',
  overwriteExistingTarget: 'Overwrite Existing Target',
  overwriteTargetDesc: 'Force-delete target path directories if they already exist',
  overwriteTargetWarning: 'This will permanently delete any existing directory at the target path before migration begins.',
  renameDowntimeHint: 'Ensure the database service is fully stopped before renaming to prevent binary corruption.',
  extendedVolumePath: 'Extended volume path',
  renameIndividualVolumes: 'Rename individual volumes',
  currentVolumeName: 'Current volume name',
  newVolumeName: 'New volume name',
  currentDirectoryPath: 'Current directory path',
  newDirectoryPath: 'New directory path',
  forceDeleteBackupVolume: 'Force delete backup volumes',
  forceDeleteBackupVolumeDesc: 'Force-delete backup volumes if they already exist',
  forceDeleteBackupVolumeWarning: 'This will permanently delete any existing backup volumes at the target paths.',
  synchronizingVolumes: 'Copying Database',
  cloningComplete: 'Copy Complete',
  cloningFailed: 'Copy Failed',
  cloneSubtitle: 'Create a copy of the database',
  cloningContext: 'Copy Information',
  targetEnvironment: 'Destination',
  executionStrategy: 'Copy Options',
  overwriteExistingEnvironment: 'Overwrite Existing Files',
  transformToMove: 'Delete Source After Copy',
  executeCopy: 'Copy',

  // Desktop Copy Database Dialog labels
  grpDbSourceName: 'Source database',
  grpDbDestName: 'Destination database',
  lblSrcDbName: 'Database name:',
  lblSrcDbPathName: 'Database path:',
  lblSrcLogPathName: 'Log file path:',
  lblDescDbName: 'Database name:',
  lblDescDbPathName: 'Database path:',
  lblDescLogPathName: 'Log file path:',
  lblVolumePathName: 'Extend volume path:',
  btnCopyVolume: 'Copy individual volumes',
  tblColumnCurrentVolName: 'Current volume name',
  tblColumnCopyNewVolName: 'New volume name',
  tblColumnCopyNewDirPath: 'New directory path',
  btnReplaceDb: 'Replace an existing database',
  btnDeleteSrcDb: 'Delete a source database',
  lblCopyFreeDiskSize: (size) => `Free disk space: ${size}`,
  lblCopyDbSize: (size) => `Database size: ${size}`,
  msgCopyDbDialog: 'Please enter the database information.',
  consolidatingBlocks: 'Compacting Database',
  optimizationComplete: 'Optimization Complete',
  optimizationPipeline: 'Optimization',
  executionOptions: 'Options',
  executeCompaction: 'Compact',
  retryOptimization: 'Retry Optimization',
  verboseMonitoring: 'Verbose Monitoring',
  verboseMonitoringDesc: 'Show real-time OID transformation logs',
  executingHeuristics: 'Optimizing',
  executionInterrupted: 'Interrupted',
  performanceTuningSubtitle: 'Optimize query execution plans',
  optimizerIntel: 'Optimizer',
  targetInstanceSection: 'Target Database',
  applyChanges: 'Apply Changes',
  updateSuccessful: 'Update Successful',
  configurationReIndexed: 'Configuration Updated',
  updateRejected: 'Update Failed',
  synchronizationHalted: 'Synchronization Failed',
  updatingRegistry: 'Updating Configuration',
  syncingRegistrySubtitle: 'Updating cubrid.conf on the server.',
  navigation: 'Navigation',
  context: 'Context',
  loadingLabel: 'Loading',
  queryingHostRegistry: 'Loading configuration…',
  brokerConnection: 'Broker Connection',
  brokerIp: 'Broker IP',
  publicAddress: 'Public address',
  servicePort: 'Service Port',
  activeBroker: 'Active broker',
  textEncoding: 'Text Encoding',
  charset: 'Charset',
  synchronizationNotice: 'Synchronization Notice',
  brokerParamsNotice: 'Broker parameters define how the Web Manager communicates with the CUBRID Broker. Changes only impact Manager-to-Host synchronization logic.',
  lockingSection: 'Locking',
  transactionSection: 'Transaction',
  systemSection: 'System',
  advancedHeuristics: 'Advanced Heuristics',
  pagesCountTitle: 'Pages Count',
  physicalSizeLabel: 'Physical Size',
  configPatchRejectedMsg: 'System controller rejected the configuration patch.',
  connectionNavLabel: 'Connection',
  serverNavLabel: 'Server',
  generalParamsTab: 'General Parameters',
  advancedParamsTab: 'Advanced Parameters',
  kernelParamsTitle: 'Kernel Parameters',
  registrySubtitle: (db) => `${db} · Registry`,
  brokerCharsetConfigDesc: 'Broker and charset configuration for this database',
  deepSystemConfigDesc: 'Deep system configuration for the CUBRID instance',
  resetToOriginalBtn: 'Reset to Original',
  webManagerConnectionDesc: (db) => `Configure how Web Manager connects to ${db}. These parameters define how the Web Manager communicates with the CUBRID Broker.`,
  dataBufferAllocLabel: 'Data Buffer Allocation',
  sortBufferAllocLabel: 'Sort Buffer Allocation',
  logBufferAllocLabel: 'Log Buffer Allocation',
  advancedParamsWarning: 'Advanced parameters — changes may affect server stability and performance. Exercise caution when modifying these values.',
  databaseProperties: 'Database Properties',
  initializingSchedule: 'Initializing',
  committingAutomation: 'Saving',
  scheduleCommitted: 'Saved',
  automationActive: 'Active',
  executionError: 'Execution Error',
  initializeCycle: 'Save',
  abstractionLevel: 'Type',
  planRegistryId: 'Plan ID',
  payloadPath: 'Path',
  rotationLogic: 'Rotation',
  targetTime: 'Target Time',
  standard24hCycle: 'Daily (24h cycle)',
  fullSpectrumPreset: 'Full Spectrum',
  resetGridPreset: 'Reset Grid',
  standardWeekPreset: 'Standard Week',
  weekendCyclePreset: 'Weekend Cycle',
  dailySyncInfoBanner: (time) => `Instance synchronized daily at exactly ${time}.`,
  registryDate: 'Date',
  optimizationMatrix: 'Optimization',
  rotationRetention: 'Retention',
  deleteBackupPlan: 'Delete Backup Plan',
  deleteQueryPlan: 'Delete Query Plan',
  deletingQueryPlan: 'Deleting Query Plan',
  removingRegistry: 'Deleting',
  deletionSuccess: 'Deletion Success',
  registryPurged: 'Query Plan Deleted',
  queryPlanRemovedMsg: 'The query plan has been deleted.',
  deletionFailed: 'Deletion Failed',
  signalRejected: 'Deletion Failed',
  deletionSignalFailed: 'Failed to delete the query plan.',
  retryDeletion: 'Retry Deletion',
  dangerousDiscardQueryPlan: 'Delete Query Plan',
  permanentRemovalSql: 'Remove SQL automation entry',
  discardingAutomationHandleMsg: (id) => `Discarding automation handle "${id}".`,
  logsNotPurgedNotice: 'Existing logs generated by this plan will not be purged, but no new executions will be scheduled.',
  executeDiscard: 'Delete',
  discardQueryStrategy: 'Delete Query Plan?',
  planRetirement: 'Delete Query Plan',
  planCacheDumpTitle: 'Plan Cache Dump',
  loadingParameters: 'Loading parameters',
  parameter: 'Parameter',
  serverValue: 'Server Value',
  clientValue: 'Client Value',
  failedToGetDbParams: 'Failed to get database parameters.',
  message: 'Message',
  activeContext: 'Active Context',
  offlineStatic: 'Offline Static',
  noConfigParameters: 'No configuration parameters identified for this instance.',
  parameterDumpSubtitle: 'Check out the parameter values',
  environmentReady: 'Ready',
  analysisPipeline: 'Analysis',
  comparativeAnalysis: 'Comparative Analysis',
  comparativeAnalysisDesc: 'Extract both client/server values',
  paramsFetchErrorMsg: (db) => `Could not get parameters for ${db}.`,
  extractionProfileDesc: 'Extraction profile captures a snapshot of parameters currently active in the database memory heap. Provides visibility into the hardware-tailored operational metrics.',
  loadingBrokerStatus: 'Loading broker status…',
  basicInformation: 'Basic Information',
  lastAccess: 'Last Access',
  clientIp: 'Client IP',
  jobId: 'Job ID',
  priority: 'Priority',
  elapsed: 'Elapsed',
  request: 'Request',
  activeCount: (n) => `${n} active`,
  queuedCount: (n) => `${n} queued`,
  downloadAllLogs: 'Download all loaded logs into a single file',
  setAutomationVolume: 'Set Automation Volume',
  addStorageVolume: 'Add Storage Volume',
  editBackupPlanTitle: 'Edit Backup Plan',
  deleteBackupPlanTitle: 'Delete Backup Plan',
  runBackup: 'Run Backup',
  retryBackup: 'Retry Backup',
  backupCompleted: 'Backup Completed',
  backupFailed: 'Backup Failed',
  targetDatabase: 'Target Database',
  executeRestore: 'Execute Restore',
  retryRecovery: 'Retry Recovery',
  restoreSuccessful: 'Restore Successful',
  initiateCopy: 'Copy',
  retryClone: 'Retry',
  executeOptimization: 'Execute Optimization',
  retryExecution: 'Retry Execution',
  volumeAllocation: 'Add Volume',
  scalingFoundation: 'Adding Volume',
  allocationSuccessful: 'Volume Added',
  storageExpanded: 'Volume Added Successfully',
  allocationInterrupted: 'Add Volume Error',
  scalingFailed: 'Failed to Add Volume',
  storageOptimization: 'Optimize Database',
  allocationStrategy: 'Volume Options',
  instanceRegistry: 'Database',
  privilegedOperation: 'Note',
  addVolumeNote: 'The database must be running to add a volume. Ensure the volume path has write permissions.',
  extendDiskCapacity: (db) => `Add volume to ${db}`,
  historyForDatabase: (db) => `History for database: ${db}`,
  globalBackupHistory: 'Global Backup History',
  dumpingPlanCache: 'Dumping Plan Cache',
  displayQueryPlan: 'Show the query plan',
  dumpingPlanCacheSubtitle: 'Reading XASL plan cache from server...',
  runDumpHint: 'Run the dump to view query plan cache entries.',
  backupId: 'Backup ID',
  logTime: 'Log Time',
  description: 'Description',

  // Header menu (extra)
  actionMenu: 'Top Tasks',
  configParam: 'Config Param',
  editCmConfig: 'Edit CM Config',
  reportBug: 'Report Bug',
  cubridOnlineForum: 'CUBRID Online Forum',
  cubridToolsDevelopment: 'CUBRID tools developments',
  checkForUpdates: 'Check for Updates',

  // Dashboard shared
  globalHealthOverview: 'Global Health Overview',
  hostsLabel: 'Hosts',
  activeLabel: 'Active',
  unknownHost: 'Unknown Host',
  localhost: 'Localhost',
  statusOn: 'On',
  statusOff: 'Off',
  synchronizingServices: 'Synchronizing Services',
  stopServices: 'Stop Services',
  startServicesConfirmTitle: 'Start Services',
  startServicesConfirmDesc: (server) => `Are you sure you want to start all CUBRID services on host "${server}"?`,
  stopServicesConfirmTitle: 'Stop Services',
  stopServicesConfirmDesc: (server) =>
    `Are you sure you want to stop all CUBRID services on host "${server}"? This will terminate all active brokers and databases.`,
  startingServicesOn: (server) => `Starting services on ${server}`,
  stoppingServicesOn: (server) => `Stopping services on ${server}`,
  serviceStartRejected: 'Service start command rejected by host agent.',
  serviceStopFailed: 'Service termination failed. Check agent logs.',
  connectHostForMonitoring: 'Connect to a host server from the navigator to activate global resource monitoring.',
  permanentTemp: 'Permanent Temp',
  tempTemp: 'Temporary Temp',
  userLabel: 'User',
  haMaster: 'Master',
  haSlave: 'Slave',
  haReplica: 'Replica',
  clusterOverview: 'Cluster Overview',
  expandGroupTitle: 'Expand group',
  collapseGroupTitle: 'Collapse group',
  nodesCountLabel: (n) => `${n} nodes`,
  haBadge: 'HA',
  onColonLabel: (n) => `ON: ${n}`,
  offColonLabel: (n) => `OFF: ${n}`,

  // Database dashboard
  databaseDashboard: 'Database Dashboard',
  refreshDatabaseStatus: 'Refresh database status',
  exportMetricsCsv: 'Export metrics as CSV',
  restartingCas: 'Restarting CAS',
  resettingCasProcess: 'Resetting broker application server process',
  loadingDashboard: 'Loading Dashboard…',
  restartCasConfirm: (cas, broker) => `Are you sure you want to restart CAS ID: ${cas} on broker: ${broker}?`,

  // Database dashboard sections
  performanceMetrics: 'Performance Metrics',
  realTime: 'Real-time',
  transPerSec: 'Trans/sec',
  queriesPerSec: 'Queries/sec',
  bufferHit: 'Buffer Hit',
  fetchesPerSec: 'Fetches/s',
  dirtyPerSec: 'Dirty/s',
  ioReadsPerSec: 'IO Reads/s',
  ioWritesPerSec: 'IO Writes/s',
  hitRatioLabel: 'Hit Ratio',
  fetchPerSecLabel: 'Fetch/s',
  sectionLabel: 'Section',
  keyLabel: 'Key',
  summaryLabel: 'Summary',
  pagesCountLabel: (n) => `${n} pages`,
  storageVolumes: 'Storage Volumes',
  volumeLabel: 'Volume',
  purpose: 'Purpose',
  spaceUsage: 'Space Usage',
  modifiedLabel: 'Modified',
  pathLabel: 'Path',
  fileDistribution: 'File Distribution',
  logicalPartitioning: 'Logical Partitioning',
  filesLabel: 'Files',
  usedLabel: 'Used',
  fileTable: 'File Table',
  reservedLabel: 'Reserved',
  totalLabel: 'Total',
  casBrokers: 'CAS Brokers',
  readyCount: (n) => `${n} ready`,
  busyCount: (n) => `${n} busy`,
  lastConn: 'Last Conn',
  sqlLogs: 'SQL Logs',
  slowQueryLogs: 'Slow Query Logs',
  restartCasTitle: 'Restart CAS',
  lockMode: 'Lock Mode',
  activeLog: 'Active Log',
  archiveLog: 'Archive Log',
  longTran: 'Long-T',
  longQuery: 'Long-Q',
  errQuery: 'Err-Q',
  reqLabel: 'REQ',
  jqLabel: 'JQ',
  asLabel: 'AS',

  // System status section
  systemStatus: 'System Status',
  nowLabel: 'Now',
  fiveMinAvg: '5 min Avg',
  resume: 'Resume',
  haClusterStatus: 'HA Cluster Status',
  nodesActiveInCluster: (n) => `${n} nodes active in cluster`,
  environmentUnavailable: 'Environment information unavailable',

  language: 'Language',
  languageEn: 'English',
  languageKo: 'Korean',

  // Backup dialog options (aligned with CUBRID Admin)
  backupLevelFullTitle: 'Full Backup',
  backupLevelFullDesc: 'Complete backup of all data',
  backupLevelIncrL1Title: 'Incremental (L1)',
  backupLevelIncrDesc: 'Changes since last L0 backup',
  backupLevelIncrL2Title: 'Incremental (L2)',
  backupLevelDiffDesc: 'Changes since last L1 backup',
  checkConsistencyLabel: 'Check Database Consistency',
  checkConsistencyDesc: 'Check the database consistency during backup',
  deleteArchiveLogsLabel: 'Delete Unnecessary Log-Archives',
  deleteArchiveLogsDesc: 'Remove transaction logs already archived',
  compressBackupLabel: 'Compress Backup Volumes',
  compressBackupDesc: 'Reduce backup file size with compression',
  parallelBackupDesc: 'Number of parallel backup threads',
  threadsLabel: 'Threads',

  // Compact database steps
  compactStep1Label: 'Clean References',
  compactStep1Desc: 'Remove unused object references',
  compactStep2Label: 'Clean Metadata',
  compactStep2Desc: 'Clean internal metadata',
  compactStep3Label: 'Consolidate Disk',
  compactStep3Desc: 'Merge fragmented disk pages',

  // Optimize database
  allTables: 'All Tables',
  filterObjects: 'Filter objects...',
  regeneratingStatistics: 'Regenerating Statistics',
  optimizationSuccess: 'Optimization Complete',
  optimizationFailed: 'Optimization Failed',
  optimizerHint: 'Regenerating statistics allows the query optimizer to choose the most efficient execution paths.',
  globalScanHint: 'Global scans may briefly lock schema metadata during analysis.',
  lblOptimizeDbName: 'Database name:',
  lblOptimizeClassName: 'Table name:',
  grpOptimizeDesc: 'Description',
  lblOptimizeDesc: 'The query optimizer uses statistical information such as the number of objects in a table, the number of pages to access and the distribution of attribute values.',
  msgOptimizeDbInformation: 'Please select a table to optimize.',

  // Copy database path labels
  primaryVolumePath: 'Database Volume Path',
  extVolumePath: 'Extended Volume Path',
  logVolumePath: 'Log Volume Path',
  replaceExistingDesc: 'Replace destination files if a database with this name already exists.',
  moveSourceDesc: 'Delete source files after copy completes.',

  // Query plan modals (Add/Edit)
  queryIdentifierRequired: 'A Query ID is required.',
  sqlStatementRequired: 'An SQL statement is required.',
  queryPlanAdded: 'Query Plan Added',
  addQueryPlanFailed: 'Failed to Add Query Plan',
  editQueryPlanFailed: 'Failed to Update Query Plan',
  planUpdatedMsg: (id) => `Plan "${id}" has been successfully updated.`,
  addQueryPlanFailedMsg: 'Failed to add query plan.',
  objectIdentification: 'Identification',
  queryIdentifierLabel: 'Query ID',
  secureContextSection: 'Database Credentials',
  databaseUsernameLabel: 'Username',
  databasePasswordLabel: 'Password',
  recurrenceFrequency: 'Frequency',
  startTimeLabel: 'Time',
  dailyLabel: 'Daily',
  weeklyLabel: 'Weekly',
  monthlyLabel: 'Monthly',
  specificDateLabel: 'Specific Date',
  sqlStatementSection: 'SQL Statement',
  systemComplianceNote: 'Queries are executed on the server side. The database user must have sufficient privileges.',
  runSchedule: 'Save',
  automatingDatabase: 'Automating database',

  // Backup plan level descs (short)
  levelFullShortDesc: 'Full backup',
  levelIncrL0ShortDesc: 'Since last L0',
  levelIncrL1ShortDesc: 'Since last L1',

  // Backup plan option labels
  updateStatisticsLabel: 'Update Statistics',
  updateStatisticsDesc: 'Update query optimizer statistics',
  deleteArchiveDesc: 'Delete transaction logs that have already been archived',

  // Backup plan schedule options
  monthly: 'Monthly',
  weekly: 'Weekly',
  daily: 'Daily',
  specificDays: 'Specific Date',
  onlineMode: 'Online',
  onlineModeDesc: 'Backup while the database is running',
  offlineMode: 'Offline',
  offlineModeDesc: 'Backup with the database stopped',
  savingSchedule: 'Saving',
  updatingSchedule: 'Updating',

  // Edit backup plan modal
  backupPlanUpdatedMsg: (id) => `Backup plan ${id} successfully updated.`,
  patchRejectedMsg: 'System controller rejected the patch. Verify schema integrity.',

  // Delete backup plan modal
  deletingBackupPlan: 'Deleting Backup Plan',
  backupPlanDeleted: 'Backup Plan Deleted',
  backupPlanRemovedMsg: (id) => `Backup plan ${id} successfully removed.`,
  deleteBackupPlanFailed: 'Delete Backup Plan Failed',
  discardBackupStrategy: 'Delete Backup Plan?',
  backupScheduleNote: 'This only removes the schedule. Existing backup files remain on disk.',
  dangerousDiscardBackupPlan: 'Delete Backup Plan',
  permanentRemovalBackup: 'Permanently remove this backup schedule',
  deletionSignalRejectedMsg: 'System controller rejected the deletion signal. Registry remains active.',

  // SetAutomationVolumeModal
  savingPolicies: 'Saving',
  policiesSaved: 'Saved',
  savedSuccessfully: 'Saved Successfully',
  saveInterrupted: 'Save Failed',
  savePolicies: 'Save',
  expansionSize: 'Expansion Size (MB)',
  extensionPages: 'Extension Pages',
  autoVolumeActive: 'Volume Auto Expansion Active',
  loadingConfig: 'Loading configuration…',
  indexVolume: 'Index Volume',

  // AddVolumeModal
  retryAddVolume: 'Retry',
  activeInstanceRequired: 'Database must be running',
  availableSpace: 'Free Space',
  customCapacity: 'Volume Size (MB)',
  blocksAllocated: 'Number of Pages',
  volumeIdentifier: 'Volume Name',
  volumeDir: 'Volume Path',
  addVolumeTargetDb: 'Target Database',
  calculating: 'Calculating',
  volumeSizeVisualizer: 'Volume Size',
  addVolumeSuccessMessage: (volName, db) => volName ? `Volume "${volName}" has been added to ${db}.` : `Volume has been added to ${db}.`,
  volumeTypeDataDesc: 'Tables and rows',
  volumeTypeTempDesc: 'Temporary workspace',

  // RestoreDatabaseModal
  logCatchup: 'Partial Recovery',
  noBackupFound: 'No Backup Records Found',
  noBackupHint: 'Ensure the backup directory is configured and synchronized.',
  showAllBackups: 'Show all',

  selectBackupFirst: 'Please select a backup to restore from.',
  restoreErrorFallback: 'An unexpected error occurred during restore.',
  tryOtherBackupLevel: 'Try selecting another backup level, or view all.',
  recoveryPathPlaceholder: 'Default: original location',
  pointInTimeRecovery: 'Point-in-Time Recovery',
  pointInTimeHint: 'Restore to a specific moment after the backup was taken',
  restoreToDate: 'Restore to Date & Time',

  restoreDateRequired: 'Enter the recovery date and time.',
  restoreDateBeforeBackup: 'Recovery date must be on or after the backup date.',
  backupLevelFullLongDesc: 'Complete snapshot of all data, schema and volumes.',
  backupLevelIncrL1LongDesc: 'Changes since last L0 backup. Requires L0 to restore.',
  backupLevelIncrL2LongDesc: 'Changes since last L1 backup. Requires L0 + L1 to restore.',
  grpDbName: 'Database Name',
  lblDbNameRestore: 'Database name:',
  grpRestoredData: 'Restored Data',
  grpDbPath: 'Recovery Path',
  grpPartialRecovery: 'Partial Recovery',
  selectRestoreDateTime: 'Select restore date and time',
  lblDate: 'Date:',
  lblTime: 'Time:',
  backupTimeLabel: 'Backup time',
  specifyRestoreDate: 'Specify a restore date',
  selectBackupInfoLabel: 'Select available backup information',
  level0FileLabel: 'Level 0 file:',
  level1FileLabel: 'Level 1 file:',
  level2FileLabel: 'Level 2 file:',
  changeRestorePathLabel: 'Recovery path:',
  performPartialRecovery: 'Perform partial recovery if any log archive is absent',
  errLevel0File: 'The level 0 file is not valid.',
  errLevel1File: 'The level 1 file is not valid.',
  errLevel2File: 'The level 2 file is not valid.',
  errRecoveryPath: 'The user-defined recovery path is not valid.',
  errLoadSchema: 'Loaded schema file is not valid.',
  errLoadObjects: 'Loaded objects file is not valid.',
  errLoadIndex: 'Loaded index file is not valid.',
  errLoadTrigger: 'Loaded trigger file is not valid.',
  errLoadFileFromSys: 'Please select the unloaded file from the file system',
  errLoadFileFromList: 'Please select the unloaded file from the list.',
  errInsertCount: 'The value of insertion count for periodic commit is not valid. It can only be an integer value greater than 0.',
  errControlFile: 'The error control file is not valid.',
  errClassFile: 'The ignored table file is not valid.',
  errNoSelectedPath: 'Please check the unloaded files of the selected database from the following list.',
  errNumOfInstances: 'The estimated number of instances is not valid. It can only be an integer greater than 0.',


  // Auth
  pickUniqueUsername: 'Pick a unique username',
  createStrongPassword: 'Create a strong password',
  repeatPassword: 'Repeat your password',
  emailAddressLabel: 'Email Address',

  // Sidebar context menus
  newGroup: 'New Group',
  addNode: 'Add Node',
  renameGroup: 'Rename Group',
  deleteGroup: 'Delete Group',
  manageGroupMembers: 'Manage Group',
  manageGroupMembersTitle: (groupName) => `Manage Group — ${groupName}`,
  manageGroupMembersDesc: 'Check a host to add it to this group. Uncheck a host to move it to Ungrouped.',
  saveChangesCount: (count) => `Save ${count} change${count === 1 ? '' : 's'}`,
  moveHostFailedError: (names) => `Failed to move: ${names}. Please try again.`,
  searchHostsPlaceholder: 'Search hosts…',
  ungroupedHosts: 'Ungrouped',
  viewAllLogs: 'View All Logs',
  viewDatabase: 'View Database',

  // Host modals
  loginIdLabel: 'Login ID',
  statusAuthorityLabel: 'Status Authority',
  administratorAccount: 'Administrator Account',
  groupNameLabel: 'Group Name',
  hostPasswordPlaceholder: 'Host password',
  haClusterLinked: 'HA Cluster Linked',
  mergeHAPeers: 'Merge HA Cluster Peers',
  groupNameRequired: 'Group name is required',
  groupNamePlaceholderHint: 'e.g. Production Cluster',
  deleteGroupConfirmTitle: (groupName) => `Delete group "${groupName}"?`,
  deleteGroupConfirmDesc: 'This will permanently delete the group itself.',
  deleteGroupHostsWarning: (count) => `This will also permanently delete ${count} host${count === 1 ? '' : 's'} registered in this group — they are not moved to Ungrouped.`,
  haClusterLinkedDesc: (count) => `This host is part of an HA cluster. ${count} node(s) are registered in`,
  haPeerMergeDesc: (count) => `This host belongs to an HA cluster. ${count} registered peer(s) are in other groups. Merge them into`,
  fromGroupLabel: (groupName) => `from ${groupName}`,

  // User modals
  moveToGroups: 'Move to Groups',
  removeFromAssigned: 'Remove from assigned',
  departmentLabel: 'Department',
  currentPasswordLabel: 'Current Password',
  confirmNewPassword: 'Confirm New Password',
  dropDatabaseUser: 'Drop Database User',
  droppingUser: 'Deleting',
  userDropped: 'Deleted',
  dropUserConfirmSection: 'Confirm Delete',
  dropUserWarning: 'This action is permanent.',
  dropUserBtn: 'Drop User',

  // DeleteDatabaseModal
  deletingDatabase: 'Deleting',
  deleteSuccessful: 'Delete Successful',
  authorizationPointTitle: 'Authorization',
  targetSelection: 'Target Selection',
  recoveryCleanup: 'Recovery Cleanup',
  purgeLinkedBackups: 'Delete Linked Backups',
  purgeLinkedBackupsDesc: 'Remove all backup volumes and snapshots linked to this database.',
  fetchingAssets: 'Loading...',
  noVolumesDetected: 'No volumes detected',
  proceedBtn: 'Proceed',
  backBtn: 'Back',
  databaseDeletedMsg: (db) => `Database "${db}" was deleted.`,
  authOrOperationFailedMsg: 'Authentication or operation failed. Verify credentials and instance state.',
  deleteDatabaseWarningDesc: 'This action is permanent. All database files and logs listed below will be erased and cannot be recovered.',
  assetsCountLabel: (n) => `${n} Assets`,
  freeSpaceLabel: (free) => `${free} free`,
  confirmCredentialsToDeleteDesc: (db) => `Confirm your database credentials to permanently delete ${db}.`,
  finalDeleteStepDesc: 'This is the final step. After confirmation, all data for this instance will be permanently erased.',

  // VolumeInfoMonitor
  loadingVolumeInfo: 'Loading Volume Information',
  loadingVolumeInfoSub: 'Fetching volume allocation data...',
  volumeNotFound: 'Volume Not Found',
  location: 'Location',
  pageSizeLabel: 'Page Size',
  totalPages: 'Total Pages',
  freePages: 'Free Pages',
  totalSize: 'Total Size',

  // Log modals
  filterLogsById: 'Filter by ID or description...',
  buffering: 'Buffering',
  synchronizedStatus: 'Synchronized',
  logAllLevels: 'All Levels',
  infoLog: 'Info',
  statusNotice: 'Notice',

  // Monitoring / misc
  monitoringSync: 'Monitoring Synchronization',
  customIntervalPlaceholder: 'Custom interval',
  defaultValuePlaceholder: 'Default',

  // Config editors
  undoAllChanges: 'Undo all changes',
  brokerConfigPlaceholder: '# Enter broker configuration here...',
  initializingEditor: 'Initializing Editor...',
  brokerConfigFile: 'Configuration: cubrid_broker.conf',
  brokerConfigFetchError: 'Could not retrieve broker configuration.',
  brokerConfigSaveSuccess: 'Broker configuration updated successfully.',
  brokerConfigSaveError: 'An error occurred while saving broker configuration.',

  // EditCMSUserModal
  savingChanges: 'Saving Changes',
  creatingUser: 'Creating User',
  accountInformation: 'Account Information',
  allowDatabaseCreation: 'Allow Database Creation',
  allowDbCreationDesc: 'User can create and drop databases on this host',

  // CreateUserModal
  createUser: 'Create User',
  userUpdated: 'User Updated',
  userCreated: 'User Created',

  // UserProfileModal
  accountDetails: 'Account Details',
  updateProfileSection: 'Update Profile',
  accountProfile: 'Account Profile',
  editProfile: 'Edit Profile',
  updatePasswordBtn: 'Update Password',
  securitySettings: 'Security Settings',

  // DatabasePropertyModal
  confirmReturn: 'Confirm & Return',
  retryPatch: 'Retry Patch',
  discardChanges: 'Discard Changes',

  // HaPeerMergeModal / HostGroupNameModal
  mergeIntoGroup: 'Merge into group',
  createGroup: 'Create Group',

  // CMSUserManagementModal
  systemAdministrator: 'System administrator',
  managementUsers: 'Management users',

  // Monitor refresh buttons
  refreshVolumeData: 'Refresh volume data',
  refreshCategoryMetrics: 'Refresh category metrics',
  refreshSpaceMetrics: 'Refresh space metrics',

  // VolumeCategoryMonitor
  volumeCategoryMonitor: 'Volume Category Monitor',
  capacity: 'Capacity',
  usageLabel: 'Usage',
  overallUtilization: 'Overall Utilization',
  volumesLabel: 'Volumes',
  pagesLabel: 'Pages',
  freeLabel: 'Free',

  // Auto log modals / CASLogModal
  timeLabel: 'Time',
  outcomeLabel: 'Outcome',
  executionTime: 'Execution Time',
  globalAutomationHistory: 'Global Volume Auto Expansion History',
  globalQueryHistory: 'Global Query Execution History',
  casSqlLog: 'CAS SQL Log',
  casSlowQueryLog: 'CAS Slow Query Log',

  // Modal subtitles (automation modals)
  addQueryPlanSubtitle: (db) => `Schedule automated SQL execution for ${db}`,
  editQueryPlanSubtitle: (db) => `Modify automated SQL execution for ${db}`,
  addBackupPlanSubtitle: (db) => `Configure automated scheduled backups for ${db}`,
  editBackupPlanSubtitle: (db) => `Modify automated scheduled backup for ${db}`,
  setAutomationVolumeSubtitle: (db) => `Configure expansion policies for "${db}"`,
  permanentDataVolDesc: 'Permanent data volumes',
  indexSearchVolDesc: 'Index & search volumes',
  permanentData: 'Permanent Data',
  temporaryData: 'Temporary Data',

  // DatabaseSpaceMonitor
  storageAnalysisError: 'Storage Analysis Error',

  // CreateDatabaseModal
  removeVolume: 'Remove volume',
  storage: 'Storage',

  // CreateUserModal
  source: 'Source',

  // Auth pages
  recoverPassword: 'Recover your password',
  linkExpiry: 'Link Expiry',
  registrationFailedTitle: 'Registration Failed',
  desktopOnly: 'Desktop only',
  desktopBridgeUnavailable: 'Desktop bridge unavailable',

  // DesktopWorkspaceSettingsPage
  workspaceSettingsLoadFailedMsg: 'Failed to load workspace settings',
  applyingWorkspaceMsg: 'Applying workspace…',
  workspaceSaveFailedMsg: 'Failed to save workspace',
  workspaceAppliedRelogMsg: 'Workspace applied. Please log in again.',
  workspaceResetFailedMsg: 'Failed to reset workspace',
  workspaceDesktopOnlyDesc: 'Workspace settings are available in the CUBRID Web Manager desktop app.',
  desktopConnectFailedMsg: 'Could not connect to the desktop app. Quit and run again with',
  selectWorkspaceTitle: 'Select Workspace',
  workspaceTitle: 'Workspace',
  workspaceDescPrefix: 'You only need to specify ',
  workspaceDescFolderPhrase: 'a single folder',
  workspaceDescMiddle: ' to store your data, certificates, and settings. The app will automatically create ',
  workspaceDescSuffix: ' inside it automatically.',
  workspaceFolderLabel: 'Workspace folder',
  defaultLocationLabel: (path) => `Default location: ${path}`,
  defaultLocationBtn: 'Default location',
  settingsFileLabel: (path) => `Settings file: ${path}`,
  selectFolderEllipsis: 'Select folder…',
  continueBtn: 'Continue',

  // CAS Log Viewer
  casSqlTransactionLog: 'CAS SQL Log',
  casSlowQueryRegistry: 'CAS Slow Query Log',
  broker: 'Broker',
  casUid: 'CAS UID',
  noLogData: 'No Log Data',
  logStreamEmptyMsg: "The requested log stream is currently empty or hasn't been initialized by the broker process.",
  logResolveError: (suffix) => `Log file identifier [${suffix}] could not be resolved in the current broker directory.`,
  logRetrievalRefused: 'The remote host refused the log retrieval request. Please verify broker connectivity.',

  // Broker Config
  fetchFailed: 'Fetch failed',
  brokerConfigRetrieveError: 'Could not retrieve broker configuration.',
  configSaved: 'Config saved',
  brokerConfigSaveSuccess: 'Broker configuration updated successfully.',
  saveFailed: 'Save failed',
  brokerConfigSaveError: 'An error occurred while saving broker configuration.',
  initializingEditor: 'Initializing Editor...',
  brokerConfig: 'Broker Config',
  brokerConfiguration: 'Broker Configuration',
  modified: 'Modified',
  commentsPreserved: 'Comments preserved in source view',
  linesLabel: (count) => `${count} lines`,

  // Node Group Tree
  addNodeToGroup: 'Add host to group',

  // Auth pages
  forgotLink: 'Forgot?',
  newToCubrid: 'New to CUBRID?',
  workspaceSettings: 'Workspace settings',
  website: 'Website',
  github: 'GitHub',
  atLeast6Chars: 'At least 6 characters',
  confirmPasswordRequired: 'Please confirm your password',
  weakPassword: 'Weak',
  averagePassword: 'Average',
  goodPassword: 'Good',
  strongPassword: 'Strong',
  architecture: 'Architecture',
  license: 'License',
  engine: 'Engine',
  security: 'Security',
  passwordsMatch: 'Passwords match',
  alreadyHaveAccount: 'Already have an account?',
  agreeTermsPrefix: 'By creating an account, you agree to the CUBRID Open Source ',
  projectTerms: 'Project Terms',
  agreeTermsSuffix: ' and data policies.',

  // Sidebar — host tree empty/login state
  addFirstHostTitle: 'Add your first host',
  addFirstHostMsg: 'Connect to a CUBRID server',
  hostLoginTitle: 'Host login',
  establishingSession: 'Establishing secure session...',
  connectionFailed: 'Connection failed',
  tryAgain: 'Try Again',
  allBrokers: 'All Brokers',
  brokerLogs: 'Broker Logs',
  errorLogs: 'Error Logs',
  adminLogs: 'Admin Logs',
  managerLogs: 'Manager Logs',
  serverLogs: 'Server Logs',
  backupPlanLabel: 'Backup Plan',
  indexEmpty: 'Index Empty',
  noDatabasesAvailable: 'No databases available',

  // DatabaseSpaceMonitor
  databaseLabel: 'Database',
  usedLabel: 'Used',
  freeLabel: 'Free',
  headroomAvailable: 'headroom available',
  usageLabel: 'Usage',
  volumeCategorization: 'Volume Categorization',
  physicalVolumeTopology: 'Physical Volume Topology',
  fileSpaceUsage: 'File Space Usage',
  distributionLabel: 'Distribution',
  dbSpaceMonitor: 'Database Space Monitor',
  qtyLabel: 'Qty',
  dataTypeLabel: 'Data Type',
  analyzingStorage: 'Analyzing storage capacity...',
  ofSizeLabel: (size) => `of ${size}`,
  spaceInfoFetchErrorMsg: 'Failed to fetch space info',

  // VolumeInfoMonitor
  volumeInfo: 'Volume Info',
  volumeHealth: 'Volume Health',
  mbPhysical: 'MB Physical',
  mbAvailable: 'MB Available',
  utilizationLabel: 'Utilization',
  volumeUsage: 'Volume Usage',
  allocationLabel: 'Allocation',
  percentUsed: '{0}% used',
  volNameRow: 'Volume Name',
  locationRow: 'Location',
  purposeRow: 'Purpose',
  pageSizeRow: 'Page Size',
  totalPagesRow: 'Total Pages',
  usedPagesRow: 'Used Pages',
  freePagesRow: 'Free Pages',
  totalSizeRow: 'Total Size',

  // VolumeCategoryMonitor
  capacityLabel: 'Capacity',
  overallUtilization: 'Overall Utilization',
  permanentDataLabel: 'Permanent Data',
  temporaryDataLabel: 'Temporary Data',

  // TransactionInfoModal
  queryTime: 'Query time',
  tranTime: 'Tran time',
  waitHolder: 'Wait holder',
  dbUserRequiredForDiagnosticsMsg: 'Database user (dbuser) is required for transaction diagnostics.',
  emptyAllowedPlaceholder: '(empty allowed)',

  // UnloadResultModal
  classLabel: 'Class',
  resultLabel: 'Result',
  noResultsLabel: 'No results',

  // SetAutomationVolumeModal
  targetDatabase: 'Target database',
  autoVolumePoliciesSavedMsg: (db) => `Auto-volume policies for "${db}" were saved successfully.`,
  saveConfigFailedRetryMsg: 'Failed to save configuration. Please try again.',
  pageSize16kLabel: 'Page size: 16K',
  autoVolumeExpandDesc: 'Volumes expand automatically when free space falls below the trigger threshold. Calculations are based on a 16K page size.',

  // DatabasePlanDumpModal
  selectedInstance: 'Selected Instance',
  xaslCache: 'XASL Cache',
  flushCacheAfterExport: 'Flush Cache after export',
  clearsXaslEntries: 'Clears XASL entries from server memory',
  hitsLabel: 'Hits',
  missesLabel: 'Misses',
  inspectStepLabel: 'Inspect',
  extractStepLabel: 'Extract',
  aggregateStepLabel: 'Aggregate',
  runDumpBtn: 'Run Dump',
  clearCachedPlansWarning: 'This will permanently clear all cached plans. Performance may decrease temporarily.',
  queryPlanEntriesLabel: 'Query Plan Entries',
  linesCountLabel: (n) => `${n} lines`,
  emptyLabel: 'Empty',

  // CMSUserManagementModal
  fullSystemAuthorization: 'Full system authorization',
  addManagementUser: 'Add a management user',

  // ChangeHostPasswordModal
  passcodeUpdated: 'Passcode Updated',
  targetHost: 'Target Host',

  // DeleteHostModal
  impactSummary: 'Impact Summary',
  deleteHostBullet1: 'Saved credentials and authentication tokens removed',
  deleteHostBullet2: 'Associated configuration profiles will be purged',
  deleteHostConfirmTitle: (alias) => `Permanently remove "${alias}"?`,
  irreversibleActionNotice: 'This action is irreversible and cannot be undone.',

  // ImportExportHostModal
  filenameLabel: 'Filename:',
  duplicateLabel: 'DUPLICATE',
  invalidLabel: 'INVALID',
  importErrorTitle: 'Import Error',
  importValidationFailedTitle: 'Import validation failed',
  importResultTitle: 'Import Result',
  importFailedTitle: 'Import failed',
  importCompleteTitle: 'Import Complete',
  importParseErrorMsg: 'An error occurred while parsing the file.',
  importNoValidHostsMsg: 'No valid hosts selected for import.',
  importSummaryMsg: (addedCount, groupSummary, skippedCount) =>
    `Imported ${addedCount} host(s) into ${groupSummary}. ${skippedCount} item(s) were skipped.`,
  importRolledBackMsg: 'Import was rolled back. No hosts were added.',
  importFailedMsg: 'Failed to import hosts.',
  failedToCreateImportGroupMsg: (name) => `Failed to create import group "${name}".`,
  passwordSavedMsg: (count) => `Password saved for ${count} host(s). Log in from the sidebar when ready.`,
  passwordNotSavedMsg: (list) => `Password not saved: ${list}.`,
  noPasswordsEnteredMsg: 'No passwords were entered.',
  passwordSavedCountMsg: (count) => `Password saved for ${count} host(s).`,
  connectedHostsMsg: (count) => `Connected ${count} host(s).`,
  loginFailedListMsg: (list) => `Login failed: ${list}.`,
  loginImportedFailedMsg: 'Failed to log in to imported hosts.',
  setPasswordsForImportedTitle: 'Set Passwords for Imported Hosts',
  pendingPasswordsSubtitle: (count) => `${count} host(s) imported. Add passwords now or skip.`,
  pendingPasswordsDesc: 'Imported hosts were added without passwords. Enter passwords now or skip.',
  importedSetPasswordsLaterMsg: (count) => `${count} host(s) imported. You can set passwords later by editing each host.`,
  exportHostsDesc: 'Export hosts to XML file. Note: The passwords are not included.',
  importHostsDesc: 'Import flat host lists into a single group (legacy XML / .prefs / .properties).',
  changeFileBtn: 'Change File',
  applyPasswordsBtn: 'Apply Passwords',
  addPasswordsBtn: 'Add Passwords',
  skip: 'Skip',
  addPasswordsConfirmTitle: 'Add passwords for imported hosts?',
  addPasswordsConfirmDesc: 'You can add them now, or skip and edit each host individually later.',
  importFormatHelp: 'CUBRID hosts XML or legacy desktop .prefs / .properties (CUBRID_SERVERS and host groups). Encrypted passwords in .prefs are not imported.',
  importGroupsHelp: 'Host groups from the .prefs file are preserved. Hosts not in any group use the name below.',
  allHostsIntoGroupHelp: 'All selected hosts go into this group',
  fallbackGroupLabel: 'Fallback group',
  validationErrorRowsHelp: 'Rows with validation errors cannot be imported. Fix the source file or deselect them.',
  selectedCountLabel: (count) => `${count} SELECTED`,
  unnamedFallback: 'Unnamed',
  groupLabel: 'Group',
  noGroupOption: 'No group',
  passwordsSkippedMsg: 'Passwords were skipped for imported hosts. You can edit each host later.',

  // CubridConfigEditor
  loadingConfiguration: 'Loading Configuration...',
  configFetchErrorMsg: 'Could not retrieve configuration file contents.',
  configUpdatedMsg: (confname) => `${confname} has been updated successfully.`,
  saveErrorFallbackMsg: 'An error occurred while saving.',
  configEditorColonLabel: (confname) => `Config Editor: ${confname}`,

  // Databases (server dashboard legacy component)
  databasesLabel: 'Databases',

  // CreateUserModal
  availableLabel: 'Available',
  noIdentities: 'No identities',
  groupsLabel: 'Groups',
  dropGroupsHere: 'Drop groups here',
  membersLabel: 'Members',
  dropMembersHere: 'Drop members here',
  loadingLabel: 'Loading...',
  noObjects: 'No objects',
  accessMaskConfig: 'Access mask configuration',
  dmlLabel: 'DML',
  ddlLabel: 'DDL',
  grantDelegation: 'Grant Delegation',
  selectAnObject: 'Select an object',
  identitySyncFailedMsg: 'Identity synchronization failed. Please check host availability.',
  newDatabaseUserTitle: 'New Database User',
  updateCredentialsSubtitle: 'Update credentials and group memberships below.',
  defineIdentitySubtitle: 'Define identity, credentials, and role membership.',
  accountSectionLabel: 'Account',
  usernamePlaceholderHint: 'e.g. sys_auditor',
  rolePurposePlaceholder: 'Role or purpose',
  groupsAndMembersLabel: 'Groups & Members',
  dragOrDoubleClickHint: 'Drag or double-click to assign',
  searchPlaceholder: 'Search...',
  groupBadge: 'GROUP',
  clearBtn: 'Clear',
  rowsSuffix: 'rows',
  proceduresLabel: 'Procedures',
  structuralPermLabel: (perm) => `Structural ${perm}`,

  // DropUserModal
  identityPurgedMsg: (username, dbname) => `Identity @${username} has been successfully purged from ${dbname}.`,
  purgeRejectedMsg: 'Purge request rejected by foreign host boundary.',

  // MonitoringSettingsPopover
  globalHeartbeat: 'Global Heartbeat',
  resourceDashboard: 'Resource Dashboard',
  syncDbThroughputMsg: 'Synchronizes database throughput and disk IO latency.',
  brokerInfrastructure: 'Broker Infrastructure',
  propagatesConnectionMsg: 'Propagates connection pool health and query load balancing.',
  sessionPreferences: 'Session Preferences',
  manualLabel: 'Manual',
  secondsSuffix: 'seconds',

  // UserProfileModal
  userIdLabel: 'User ID',
  departmentLabel: 'Department',
  lockedLabel: 'locked',
  fillAllPasswordFieldsMsg: 'Please fill in all password fields.',
  newPasswordsDoNotMatchMsg: 'New passwords do not match.',
  profileUpdateFailedMsg: 'Failed to update profile',
  unexpectedErrorMsg: 'An unexpected error occurred',
  administratorLabel: 'Administrator',
  notAssignedFallback: 'Not assigned',
  departmentPlaceholderHint: 'e.g. Engineering',

  // BrokerPropertyModal
  resetLabel: 'Reset',
  applyLabel: 'Apply',
  runtimeConfiguration: 'Runtime Configuration',
  deployingChanges: 'Deploying Changes',
  updateSynchronized: 'Update Synchronized',

  // BrokerStatus
  basicInformation: 'Basic Information',
  applicationServers: 'Application Servers (AS)',
  jobQueue: 'Job Queue',

  // CMSLogViewer
  loadingManagerLogs: 'Loading manager logs...',
  managerSystemActivity: 'Manager System Activity',
  copiedLabel: 'Copied',
  timeLabel: 'Time',
  userLabel: 'User',
  taskLabel: 'Task',
  noLogEntriesFound: 'No log entries found for this category.',
  errLabel: 'ERR',
  successLabel: 'SUCCESS',
  showingAllRecords: 'Showing all records',
  showingAllRecordsCount: (count) => `Showing all ${count} records`,
  showingRangeOfTotal: (start, end, total) => `Showing ${start}–${end} of ${total}`,
  recordsCountLabel: (count) => `${count} Records`,

  // LogViewer (Broker Log Viewer)
  brokerLogViewer: 'Broker Log Viewer',
  noContentAvailable: 'No content available for this range.',
  noSqlStatementsFound: 'No SQL statements found in this page.',
  maxSeconds: 'Max (s)',
  avgSeconds: 'Avg (s)',
  countLabel: 'Count',
  errorsLabel: 'Errors',
  sqlPattern: 'SQL Pattern',
  noQueriesToAnalyze: 'No queries found to analyze.',

  // AllLogsViewer
  loadingLogLines: 'Loading log lines...',
  noContentAvailableShort: 'No content available',
  scanningForLogFiles: 'Scanning for log files...',
  noLogFilesFound: 'No Log Files Found',
  noLogFilesFoundMsg: "We couldn't find any log files for this resource.",

  // DatabasePlanDumpModal
  flushCacheAfterExport2: 'Flush Cache after export',
  clearsXaslEntries2: 'Clears XASL entries from server memory',

  // ImportExportHostModal
  importedPlaceholder: 'Imported',

  // CMSUserManagementModal add-user CTA
  addManagementUserBtn: 'Add a management user',

  // DatabaseSpaceMonitor inline labels
  freeBadge: 'free',

  // ForgotPasswordPage
  forgotPasswordLabel: 'Forgot Password',
  backToLogin: 'Back to Login',
  backToSignIn: 'Back to Sign In',
  enterpriseSuite: 'Enterprise Database Suite',
  resetAccessCredentials: 'Reset your access credentials.',
  securityProtocol: 'Security Protocol',
  recoveryLabel: 'Recovery',
  emailPlaceholder: 'admin@organization.com',
  sendRecoveryLink: 'Send Recovery Link',
  linkSent: 'Link Sent',
  checkInbox: 'Check your inbox',
  rememberPasswordQuestion: 'Remember your password?',
  enterEmailInstruction: 'Enter your registered email address to begin the account recovery process.',
  recoverySecurityDesc: 'Account recovery is handled with the same enterprise-grade security as our database clustering. We\'ll help you regain access.',
  recoveryProtocolDesc: 'You will receive a one-time cryptographic link to authorize a new master password creation. The link expires in 15 minutes.',
  submitEmailStep: 'Submit your registered email',
  checkInboxStep: 'Check inbox for recovery link',
  setNewPasswordStep: 'Set a new secure password',
  securityInfrastructure: 'CUBRID Manager Security Infrastructure',
  recoveryInstructionsSent: 'Recovery instructions have been sent to',
  checkSpamMsg: 'The link expires in 15 minutes. Check your spam folder if it doesn\'t arrive.',
  resendRecoveryEmail: 'Resend recovery email',
  serverListHeader: 'Server List',
  resourcesHeader: 'Resources',

  // CMSUserManagementModal
  managementAccountsRegistered: (count) => count === 1 ? '1 management account registered' : `${count} management accounts registered`,
  confirmDeleteCmsUser: (username) => `Are you sure you want to permanently delete the management user "${username}"?`,
  synchronizingRegistry: 'Synchronizing registry...',
  noUsersFound: 'No users found',
  managementRegistryEmpty: 'Management registry is empty or inaccessible.',

  // EditCMSUserModal & ChangeHostPasswordModal
  updatePasscode: 'Update Passcode',
  passcodeChangedSuccessMsg: (host) => `The manager access passcode for ${host} has been successfully changed.`,
  passcodeUpdateNote: 'This will update the manager access passcode stored locally for this connection.',
  userUpdatedSuccessMsg: (username) => `User @${username} successfully updated.`,
  userCreatedSuccessMsg: (username) => `User @${username} successfully created.`,
  synchronizationFailed: 'Synchronization failed.',
  savingChanges: 'Saving Changes',
  creatingUser: 'Creating User',
  updating: 'Updating...',
  creating: 'Creating...',
  editingUser: (username) => `Editing @${username}`,
  createManagementAccount: 'Create a new management account',
  primaryAdminNotice: 'This is the primary system administrator account. System level permissions are fixed and cannot be modified.',
  operationCompletedSuccess: 'The operation completed successfully.',
  operationCouldNotBeCompleted: 'The operation could not be completed.',
  viewAll: 'View All',
  paginated: 'Paginated',
  weekdaysShort: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  weekdaysFull: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],

  // AllLogsViewer
  allServerLogsTitle: (name) => `All Server Logs for Database: ${name}`,
  allSqlLogsTitle: (name) => `All SQL Logs for ${name}`,
  aggregateServerLogsDesc: 'Displaying aggregate database server logs',
  aggregateCasLogsDesc: 'Displaying aggregate logs for all active CAS processes',
  noCachedLogLinesMsg: '(No cached log lines available for this file)',
  expandAllBtn: 'Expand All',
  collapseAllBtn: 'Collapse All',
  refreshAllBtn: 'Refresh All',
  downloadAllBtn: 'Download All',
  totalFilesLabel: (n) => `Total Files: ${n}`,
  hostColonLabel: (host) => `Host: ${host}`,

  // BrokerPropertyModal
  pendingCountLabel: (n) => `${n} Pending`,
  brokerSettingsAppliedMsg: (name) => `Broker settings for ${name} have been applied successfully.`,

  // BrokerStatus
  noAppServersActiveMsg: 'No application servers currently active.',
  jobQueueEmptyMsg: 'Job queue is empty.',
  idLabel: 'ID',

  // CMSLogViewer
  managerAccessLogTitle: 'Manager Access Log',
  managerErrorLogTitle: 'Manager Error Log',
  systemFallback: 'System',
  detailNoteHeader: 'Detail / Note',
  operationCompletedLabel: (task) => `Operation: ${task} completed`,
  totalEntriesLabel: (n) => `Total entries: ${n}`,
  showingRangeLabel: (start, end) => `Showing: ${start} - ${end}`,

  // LogViewer (Broker Log Viewer)
  rawLogMode: 'Raw Log',
  parsedSqlMode: 'Parsed SQL',
  topSqlMode: 'Top SQL',
  exportBtn: 'Export',
  statementNumberLabel: (n) => `Statement #${n}`,
  linesRangeLabel: (start, end, total) => `Lines: ${start}–${end} of ${total}`,
  statementsCountLabel: (n) => `${n} statements`,
  patternsCountLabel: (n) => `${n} patterns`,
  disconnectedLabel: 'Disconnected',

  // AboutModal
  cubridLogoAlt: 'CUBRID logo',
  aboutTagline: 'Engineered with precision for the modern web stack.',
  webBridgeLabel: 'Web Bridge',
  stackLabel: 'Stack',
  copyrightNotice: '© 2026 CUBRID Corporation',

  // Breadcrumb
  unsavedChangesDesc: (name) => `You have unsaved changes in "${name}". If you close it, your changes will be lost.`,

  // Footer
  unknownFallback: 'unknown',

  // Sidebar
  failedListSuffix: (list) => ` Failed: ${list}.`,
  loginToHostsFailedMsg: 'Failed to log in to hosts.',
  allHostsAlreadyConnectedMsg: 'All hosts are already connected.',
  groupColonLabel: (name) => `Group: ${name}`,
  startingAllDatabasesMsg: 'Starting all databases ...',
  stoppingAllDatabasesMsg: 'Stopping all databases ...',
  restartingAllDatabasesMsg: 'Restarting all databases ...',
  startingAllBrokersMsg: 'Starting all brokers ...',
  stoppingAllBrokersMsg: 'Stopping all brokers ...',
  restartingAllBrokersMsg: 'Restarting all brokers ...',
  sqlLogsColonLabel: (broker) => `SQL Logs: ${broker}`,
  serverLogsColonLabel: (db) => `Server Logs: ${db}`,
  usersColonLabel: (db) => `Users: ${db}`,
  spaceColonLabel: (db) => `Space: ${db}`,
  backupColonLabel: (planId) => `Backup: ${planId}`,
  queryPlanColonLabel: (db) => `Query Plan: ${db}`,
  queryPlanItemColonLabel: (qId) => `Query Plan Item: ${qId}`,

  // DS generic components (design system)
  unknownErrorFallback: 'Unknown error',
  breadcrumbAriaLabel: 'Breadcrumb',
  synchronizingDataTitle: 'Synchronizing Data',
  fetchingMetricsSubtitle: 'Fetching real-time metrics from the instance...',
  paginationAriaLabel: 'Pagination',
  processingEllipsis: 'Processing...',
  serviceActionLabel: 'SERVICE ACTION',
  hostActionLabel: 'HOST ACTION',
  actionLabel: 'ACTION',
  requestInProgressLabel: 'Request in Progress',
  selectDatePlaceholder: 'Select date…',
  chooseFileLabel: 'Choose file',
  dragDropFileHint: 'Drag and drop a file, or click to browse',
  requiredFieldTitle: 'Required',
  selectOptionsPlaceholder: 'Select options...',
  noOptionsLabel: 'No options',
  clearSearchAriaLabel: 'Clear search',
  selectOptionPlaceholder: 'Select option...',
  noOptionsAvailableLabel: 'No options available',
  noDataTitle: 'No Data',
  dragToResizeTitle: 'Drag to resize',
  noDataAvailableMsg: 'No data available',

  // Domain components
  oneHourLabel: '1 Hour',
  sixHoursLabel: '6 Hours',
  twentyFourHoursLabel: '24 Hours',
  brokerMetricsTitle: 'Broker Metrics',
  connectionsQpsOverTimeDesc: 'Connections & QPS over time',
  noMetricsAvailableTitle: 'No metrics available',
  noDataForTimeRangeDesc: 'No data collected for the selected time range.',
  timeColonLabel: 'Time: ',
  connColonLabel: 'Conn: ',
  maxLabel: 'Max',
  queryFailedTitle: 'Query Failed',
  resultsLabel: 'Results',
  noResultsFoundMsg: 'No results found',
  formatBtn: 'Format',
  execute: 'Execute',
  sqlQueryPlaceholder: 'Enter SQL query here...',
  deleteJobConfirmTitle: 'Delete Job?',
  deleteJobConfirmDesc: (jobName) => `Are you sure you want to delete the job "${jobName}"? This cannot be undone.`,
  deleteBtn: 'Delete',
  jobNameLabel: 'Job Name',
  cronExpressionLabel: 'Cron Expression',
  nextRunLabel: 'Next Run',
  runNowTitle: 'Run Now',
  noAutomatedJobsMsg: 'No automated jobs scheduled.',
  allLevelsLabel: 'All Levels',
  infoLabel: 'Info',
  searchLogsPlaceholder: 'Search logs...',
  noLogsFoundTitle: 'No logs found',
  adjustFiltersDesc: 'Adjust your filters or wait for new logs.',

  // Host / backup / database modal placeholders
  hostAddressPlaceholder: 'localhost',
  hostPortPlaceholder: '8001',
  hostUsernamePlaceholder: 'admin',
  friendlyNamePlaceholder: 'e.g. Production Server',
  backupPlanIdPlaceholder: 'backup_plan_1',
  backupDirPlaceholder: '/var/backups',
  exportFilenamePlaceholder: 'export_servers',
  localeDescriptions: {
    'en_US.iso88591': 'English, Western European',
    'en_US.utf8': 'English, Universal',
    'ko_KR.euckr': 'Korean, Legacy',
    'ko_KR.utf8': 'Korean, Universal',
  },

  // Broker status metric labels
  autoAddAsLabel: 'Auto Add AS',
  sqlLogModeLabel: 'SQL Log Mode',
  longTransLabel: 'Long Trans',
  longQueryLabel: 'Long Query',

  // StatusModal
  gotIt: 'Got it',
  statusSuccessTitle: 'Operation complete',
  statusErrorTitle: 'Something went wrong',
};

