/**
 * CUBRID Manager 스타일 UI 라벨 (한국어).
 * cmLabels.js 와 동일한 키 구조.
 */
export const CM_KO = {
  ok: '확인',
  cancel: '취소',
  close: '닫기',
  refresh: '새로 고침',
  confirm: '확인',
  error: '오류',
  warning: '경고',
  success: '성공',
  failure: '실패',

  loginDatabase: '데이터베이스 로그인',
  loginDatabaseMsg: '선택한 데이터베이스에 로그인합니다.',
  loggingInto: (db) => `"${db}" 데이터베이스에 로그인 중...`,
  connectionSuccessful: '연결에 성공했습니다.',
  userName: '사용자 이름',
  password: '비밀번호',
  databaseName: '데이터베이스 이름',
  savePassword: '비밀번호 저장',

  transactionInformation: '트랜잭션 정보',
  activeTransactionsOf: '데이터베이스의 활성 트랜잭션:',
  tranIndex: '트랜잭션 인덱스',
  userNameCol: '사용자 이름',
  host: '호스트',
  processId: '프로세스 ID',
  programName: '프로그램 이름',
  killTransaction: '트랜잭션 종료',
  killTransactionTitle: '트랜잭션 종료',
  killType: '종료 유형',
  killSelectedOnly: '선택한 트랜잭션만 종료',
  killSameUser: '동일 사용자의 모든 트랜잭션 종료',
  killSameHost: '동일 클라이언트 호스트의 모든 트랜잭션 종료',
  killSameProgram: '동일 프로그램의 모든 트랜잭션 종료',
  killSuccess: '트랜잭션이 성공적으로 종료되었습니다.',

  lockingInformation: '잠금 정보',
  lockSettingClientInfo: '잠금 설정/클라이언트 정보',
  objectLockTable: '객체 잠금 테이블',
  lockAndTransaction: '잠금 및 트랜잭션',
  loadingLockAndTransaction: '잠금 및 트랜잭션 정보를 불러오는 중...',
  lockIndex: '인덱스',
  pname: '프로세스명',
  uid: '사용자 ID',
  pid: '프로세스 ID',
  isolationLevel: '격리 수준',
  timeOut: '타임아웃',
  oid: 'OID',
  objectType: '객체 유형',
  mode: '모드',
  numHolders: '보유자 수',
  numBlockedHolders: '차단 보유자 수',
  numWaiters: '대기자 수',
  lockEscalation: '잠금 에스컬레이션',
  runDeadlockInterval: '데드락 검사 간격',
  currentLockedObjNum: '현재 잠긴 객체 수',
  maxLockedObjNum: '최대 잠금 가능 객체 수',

  checkDatabase: '데이터베이스 검사',
  checkDatabaseDesc:
    '데이터베이스를 검사합니다. 불일치가 발견되면 CUBRID 지원에 문의하여 결과 해석 및 조치를 진행하십시오.',
  repairWhenInconsistency: '불일치 발견 시 복구',
  jobCompletedSuccess: (job) => `${job} 작업이 성공적으로 완료되었습니다`,

  createDatabase: '데이터베이스 생성',
  deleteDatabase: '데이터베이스 삭제',
  deleteDatabaseConfirm: '이 데이터베이스를 삭제하시겠습니까?',
  backupDatabase: '데이터베이스 백업',
  restoreDatabase: '데이터베이스 복구',
  compactDatabase: '데이터베이스 공간 정리',
  optimizeDatabase: '데이터베이스 최적화',
  copyDatabase: '데이터베이스 복사',
  renameDatabase: '데이터베이스 이름 변경',
  loadDatabase: '데이터베이스 로드',
  unloadDatabase: '데이터베이스 언로드',
  dbaConfirm: 'DBA 확인',
  dbaPassword: 'DBA 비밀번호',

  manageDatabase: '데이터베이스 관리',
  databaseInfo: '데이터베이스 정보',
  usedParameterDump: '사용 파라미터 덤프',
  planCacheDump: '플랜 캐시 덤프',

  manageDatabaseMenu: {
    unload: '데이터베이스 언로드...',
    load: '데이터베이스 로드...',
    create: '데이터베이스 생성...',
    check: '데이터베이스 검사',
    compact: '데이터베이스 압축',
    optimize: '데이터베이스 최적화',
    copy: '데이터베이스 복사',
    rename: '데이터베이스 이름 변경',
    restore: '데이터베이스 복구',
    backup: '데이터베이스 백업',
    delete: '데이터베이스 삭제',
  },

  createDatabaseMsg: '새 데이터베이스를 생성합니다.',
  createDbJobComplete: (job) => `${job} 작업이 완료되었습니다.`,
  createDbFailed: '데이터베이스를 시작하지 못했습니다. 연결 정보를 확인하십시오.',
  wizardGeneral: '일반 정보',
  wizardAdditionalVol: '추가 볼륨 정보',
  wizardAutoVol: '볼륨 자동 확장',
  wizardSetDbaPass: 'DBA 비밀번호 설정',
  wizardDbInfo: '데이터베이스 정보',
  wizardDbInfoList: '새 데이터베이스 생성에 필요한 단계를 완료했습니다. 아래 설정에 따라 생성됩니다.',
  pageSize: '페이지 크기 (byte)',
  logPageSize: '로그 페이지 크기 (byte)',
  localeCharset: '문자 집합',
  userDefined: '사용자 정의',
  volumeSize: '볼륨 크기 (Mbyte)',
  genericVolInfo: '일반 볼륨 정보',
  genericVolPath: '일반 볼륨 경로',
  logVolInfo: '로그 볼륨 정보',
  logVolPath: '로그 볼륨 경로',
  volumeName: '볼륨 이름',
  volumePath: '볼륨 경로',
  volumeType: '볼륨 유형',
  autoStartDb: 'CUBRID 서비스 시작 시 데이터베이스 자동 시작',
  passwordConfirm: '비밀번호 확인',
  setPassword: '비밀번호 설정',
  readyToCreate: '생성 준비 완료',
  back: '이전',
  next: '다음',
  finish: '완료',

  unloadDatabaseMsg: '선택한 데이터베이스를 언로드합니다.',
  unloadSuccess: '데이터베이스가 성공적으로 언로드되었습니다.',
  unloadResultTitle: '데이터베이스 언로드 결과',
  unloadResultMsg: '아래에서 언로드 결과를 확인할 수 있습니다.',
  grpDbInfo: '데이터베이스 정보',
  targetDbName: '대상 데이터베이스 이름',
  targetDirectory: '대상 디렉터리',
  unloadTarget: '언로드 대상',
  unloadOption: '언로드 옵션',
  schema: '스키마',
  data: '데이터',
  all: '전체',
  selectedTables: '선택한 테이블',
  notInclude: '포함 안 함',
  useDelimitedIdentifier: '구분 식별자 사용 ("")',
  includeReferencedTables: '참조 테이블 포함',
  prefixOutputFiles: '출력 파일 접두사',
  fileForHash: '해시 파일',
  numCachedPages: '캐시 페이지 수',
  estimatedInstances: '예상 인스턴스 수',
  loFileCountPerDir: '디렉터리당 LO 파일 수',
  availableClasses: '사용 가능한 클래스',

  loadDatabaseMsg: '선택한 데이터베이스를 로드합니다.',
  loadResultTitle: '데이터베이스 로드 결과',
  loadResultMsg: '아래에서 로드 결과를 확인할 수 있습니다.',
  unloadedFiles: '언로드된 파일',
  loadType: '로드 유형',
  path: '경로',
  date: '날짜',
  selectFromList: '목록에서 언로드 파일 선택',
  selectFromRemote: '원격 시스템에서 언로드 파일 선택',
  selectFromLocal: '로컬 시스템에서 언로드 파일 선택',
  loadOption: '로드 옵션',
  loadSchema: '스키마 로드',
  loadObject: '객체 로드',
  loadIndex: '인덱스 로드',
  loadTrigger: '트리거 로드',
  checkSyntaxAndLoad: '구문 검사 후 로드',
  insertionCountPeriodicCommit: '주기적 커밋 삽입 건수',
  dontUseOid: 'OID 사용 안 함',
  dontUpdateStatistics: '통계 갱신 안 함',
  usingErrorControlFile: '오류 제어 파일 사용',
  ignoredTableFile: '무시할 테이블 파일',
  loadDbTask: '데이터베이스 로드',

  save: '저장',
  retry: '다시 시도',
  dismiss: '닫기',
  apply: '적용',
  discard: '취소',
  connect: '연결',
  loginAll: '전체 로그인',
  disconnect: '연결 해제',
  tryAgain: '다시 시도',
  add: '추가',
  edit: '편집',
  remove: '제거',
  startLabel: '시작',
  stopLabel: '중지',
  restart: '재시작',
  processing: '진행 중...',
  pleaseWait: '잠시만 기다려 주세요.',
  selectAll: '전체 선택',
  name: '이름',
  address: '주소',
  port: '포트',
  status: '상태',
  type: '유형',
  value: '값',
  actions: '작업',
  live: '실시간',
  paused: '일시정지',
  identity: '식별 정보',
  credentials: '인증 정보',
  username: '사용자 이름',
  newPassword: '새 비밀번호',
  leaveBlankToKeep: '비워 두면 기존 비밀번호 유지',
  passwordsDoNotMatch: '비밀번호가 일치하지 않습니다.',
  hostNameRequired: '호스트 이름을 입력하세요.',
  addressRequired: '주소를 입력하세요.',
  portRequired: '포트를 입력하세요.',
  usernameRequired: '사용자 이름을 입력하세요.',
  passwordRequired: '비밀번호를 입력하세요.',

  appName: 'CUBRID Manager',
  selectHostHint: '사이드바에서 호스트를 선택하면 데이터베이스, 브로커, 로그를 모니터링할 수 있습니다.',
  hostManagement: '호스트 관리',
  volumeMonitor: '볼륨 모니터',
  performance: '성능',
  lockInfo: '잠금 정보',
  systemReady: '시스템 준비됨',
  managerAccess: '관리자 접근 로그',
  managerError: '관리자 오류 로그',
  brokerStatus: '브로커 상태',
  processingDbRequest: '데이터베이스 요청 처리 중...',
  processingRequest: '요청을 처리하는 중입니다. 잠시만 기다려 주세요.',
  cmsJobRunningInBackground: (target, statusHint = '') =>
    `${target}${statusHint} — 백그라운드에서 실행 중`,
  backgroundJobsTitle: '백그라운드 작업',
  backgroundJobsRunning: (n) => `${n}개 실행 중`,
  backgroundJobsEmpty: '백그라운드 작업 없음',
  clearCompletedJobs: '완료 항목 지우기',
  jobStatusQueued: '대기',
  jobStatusRunning: '실행 중',
  jobStatusSucceeded: '완료',
  jobStatusFailed: '실패',
  jobNotifySucceeded: (op, db) => `${op} 완료 — ${db}`,
  jobNotifyFailed: (op, db) => `${op} 실패 — ${db}`,
  jobTypeUnload: '언로드',
  jobTypeLoad: '로드',
  jobTypeCreate: 'DB 생성',
  jobTypeOptimize: '최적화',
  jobTypeCheck: '검사',
  jobTypeCompact: '압축',
  jobTypeCopy: '복사',
  jobTypeAddVol: '볼륨 추가',
  jobTypeRename: '이름 변경',
  databaseAction: '데이터베이스 작업',
  brokerAction: '브로커 작업',
  actionFailed: '작업 실패',
  updateFailed: '업데이트 실패',
  updateInterrupted: '업데이트 중단',
  applyingChanges: '변경 사항 적용 중...',
  startingDatabase: (db) => `데이터베이스 시작 중: ${db}`,
  startingBroker: (b) => `브로커 시작 중: ${b}`,
  startingService: '서비스 시작 중',
  stoppingService: '서비스 중지 중',
  startingDbNamed: (db) => `데이터베이스 시작: ${db}`,
  stoppingDbNamed: (db) => `데이터베이스 중지: ${db}`,
  startingBrokerNamed: (b) => `브로커 시작: ${b}`,
  stoppingBrokerNamed: (b) => `브로커 중지: ${b}`,
  startBrokerLine: (name) => `브로커 시작: ${name}`,
  stopBrokerLine: (name) => `브로커 중지: ${name}`,
  serviceStartWait: '모든 브로커와 데이터베이스를 시작하는 중입니다. 잠시만 기다려 주세요.',
  serviceStopWait: '모든 브로커와 데이터베이스를 중지하는 중입니다. 잠시만 기다려 주세요.',
  editConfigTab: (name) => `${name} 편집`,
  allLogsTab: (name) => `전체 로그: ${name}`,
  allServerLogsTab: (name) => `서버 전체 로그: ${name}`,
  statusTab: (name) => `상태: ${name}`,
  spaceTab: (db) => `공간: ${db}`,
  volumeTab: (path) => `볼륨: ${path}`,
  volumesTab: (cat) => `볼륨: ${cat.replace(/_/g, ' ')}`,
  brokerConfig: '브로커 설정',
  serviceDashboard: '서비스 대시보드',

  file: '파일',
  view: '보기',
  service: '서비스',
  database: '데이터베이스',
  broker: '브로커',
  addHost: '호스트 추가',
  changeHost: '호스트 변경',
  exportHost: '호스트보내기',
  importHost: '호스트 가져오기',
  exportHosts: '호스트보내기',
  importHosts: '호스트 가져오기',
  importHostsXml: '호스트 XML 가져오기',
  tools: '도구',
  hostServiceManagement: '호스트 서비스 관리',
  help: '도움말',
  aboutCubridAdmin: 'CUBRID Admin 정보',
  aboutCubrid: 'CUBRID 정보',
  cubridWebManager: 'CUBRID Web Manager',
  systemDetails: '시스템 정보',
  coreVersion: '코어 버전',
  certifiedStable: '안정 인증',
  startService: '서비스 시작',
  stopService: '서비스 중지',
  startStopService: '서비스 시작/중지',
  startStopDatabase: '데이터베이스 시작/중지',
  startStopBroker: '브로커 시작/중지',
  editCubridConfig: 'CUBRID 설정 편집',
  logout: '로그아웃',
  startSelectedDbBroker: '선택한 데이터베이스/브로커 시작',
  switchToDarkMode: '다크 모드',
  switchToLightMode: '라이트 모드',

  addYourFirstHost: '첫 호스트를 추가하세요',
  connectToCubridServer: 'CUBRID 서버에 연결',
  hostLogin: '호스트 로그인',
  establishingSession: '보안 세션을 설정하는 중...',
  connectionFailed: '연결 실패',
  editHost: '호스트 편집',
  deleteHost: '호스트 삭제',
  changePassword: '비밀번호 변경',
  userManagement: '사용자 관리',
  cmsAccountManagement: 'CMS 계정 관리',
  serverVersion: '서버 버전',
  serverColon: (s) => `서버: ${s}`,
  databaseColon: (db) => `데이터베이스: ${db}`,
  allDatabases: '모든 데이터베이스',
  allBrokers: '모든 브로커',
  brokerColon: (b) => `브로커: ${b}`,
  startDatabase: '데이터베이스 시작',
  stopDatabase: '데이터베이스 중지',
  startAllDatabases: '모든 데이터베이스 시작',
  stopAllDatabases: '모든 데이터베이스 중지',
  restartAllDatabases: '모든 데이터베이스 재시작',
  startAllBrokers: '모든 브로커 시작',
  stopAllBrokers: '모든 브로커 중지',
  restartAllBrokers: '모든 브로커 재시작',
  editBrokerConfig: '브로커 설정 편집',
  showStatus: '상태 보기',
  startBroker: '브로커 시작',
  stopBroker: '브로커 중지',
  paramDump: '파라미터 덤프...',
  planDump: '플랜 덤프...',
  properties: '속성',
  databaseInfoMenu: '데이터베이스 정보',

  users: '사용자',
  jobAutomation: '작업 자동화',
  backupPlan: '백업 자동화',
  queryPlan: '질의 자동화',
  space: '공간',
  log: '로그',
  access: '접근',
  adminLog: '관리 로그',
  manager: '관리자',
  accessLog: '접근 로그',
  errorLog: '오류 로그',
  serverLogs: '서버 로그',
  sqlLog: 'SQL 로그',
  noHostSelectedTitle: '호스트 미선택',
  selectServerFromList: '위 목록에서 서버를 선택하세요.',
  serverListAbove: '위 서버 목록',
  admin: 'Admin',
  managerConsole: '관리 콘솔',

  closeTab: '탭 닫기',
  closeOtherTabs: '다른 탭 닫기',
  closeAllTabs: '모든 탭 닫기',
  reloadTab: '탭 새로 고침',
  connectedTo: (host) => `${host}에 연결됨`,
  noHostSelected: '호스트가 선택되지 않음',
  version: '버전',

  newConnection: '새 연결',
  friendlyName: '표시 이름',
  ipAddressDomain: 'IP 주소 / 도메인',
  modifyHost: '호스트 수정',
  removeHostConnection: '호스트 연결 제거',
  keepHost: '유지',
  confirmRemoval: '제거 확인',
  activeConnectionsTerminated: '이 호스트에 대한 활성 연결이 종료됩니다.',
  changeManagerPasscode: '관리자 암호 변경',
  newPasscode: '새 암호',
  verifyNewPasscode: '암호 확인',
  cubridVersion: 'CUBRID 버전',
  environmentDetails: '환경 정보',
  osPlatform: 'OS',
  installPath: '설치 경로',
  haPeersDiscovered: 'HA 노드 발견',
  peerNodes: '피어 노드',
  editUser: '사용자 편집',
  deleteUser: '사용자 삭제',
  addUser: '사용자 추가',
  fullSystemAuth: '전체 시스템 권한',
  primaryAdminCannotDelete: '기본 관리자 계정은 삭제할 수 없습니다.',
  noAccess: 'none',
  monitorOnly: 'monitor',
  fullControl: 'admin',
  permissions: '권한',
  brokerAuthority: '브로커 권한',
  monitoringPermission: '상태 모니터 권한',
  dbCreatePermission: 'DB 생성 권한',
  brokerPermission: '브로커 권한',

  serverDashboard: '서버 대시보드',
  refreshDashboard: '대시보드 새로 고침',
  syncedAt: (t) => `동기화: ${t}`,
  databases: '데이터베이스',
  autoStartup: '자동 시작',
  systemStatusError: '시스템 상태 오류',
  period: '기간',
  memory: '메모리',
  disk: '디스크',
  cpu: 'CPU',
  tps: 'TPS',
  qps: 'QPS',
  accessPoint: '접속 주소',
  authUser: '인증 사용자',
  operatingSystem: '운영 체제',
  cubridEngine: 'CUBRID 엔진',
  homeDirectory: '홈 디렉터리',
  permanent: '영구',
  temporary: '임시',
  freeStorage: '여유 공간',
  refreshBrokersList: '브로커 목록 새로 고침',
  startServices: '서비스 시작',
  stopAllServices: '모든 서비스 중지',
  sensorsOffline: '센서 오프라인',
  serviceError: '서비스 오류',
  groupHost: '그룹/호스트',
  dbStatus: 'DB 상태',
  undoChanges: '변경 취소',
  saveChanges: '변경 저장',
  reloadConfig: '설정 다시 불러오기',
  modified: '수정됨',
  sourceEditor: '소스 편집기',
  configPlaceholder: '# 설정 내용...',
  tableEditor: '테이블 편집기',

  signIn: '로그인',
  authorizeAccess: '접근 권한 부여',
  rememberDevice: '이 기기 기억',
  authenticationFailed: '인증 실패',
  createAccount: '계정 만들기',
  backToLogin: '로그인으로 돌아가기',
  accountRecovery: '계정 복구',
  resetCredentials: '접근 자격 증명을 재설정합니다.',
  registrationFailed: '등록에 실패했습니다. 다시 시도하세요.',
  passwordStrengthWeak: '약함',
  passwordStrengthAverage: '보통',
  passwordStrengthGood: '좋음',
  passwordStrengthStrong: '강함',
  minChars3: '3자 이상',

  brokerProperties: '브로커 속성',
  common: '일반',
  advanced: '고급',
  reset: '초기화',
  propertyName: '속성 이름',
  runtimeConfiguration: '런타임 설정',
  synchronizing: '동기화 중…',
  failedToLoadStatus: '상태를 불러오지 못했습니다',
  refreshBrokerStatus: '브로커 상태 새로 고침',
  downloadExcel: 'Excel로 다운로드',
  copyToClipboard: '클립보드에 복사',
  copyStatement: '문장 복사',
  refreshLog: '로그 새로 고침',
  monitoring: '모니터링',
  copyVisibleEntries: '표시 항목을 클립보드에 복사',
  connected: '연결됨',

  criticalWarning: '중요 경고',
  volumesToDelete: '삭제될 볼륨',
  destructiveAction: '위험한 작업',
  noBackupRecords: '백업 기록 없음',
  newDatabaseName: '새 데이터베이스 이름',
  downtimeRequired: '다운타임 필요',
  cloneDatabase: '데이터베이스 복사',
  cloneIdentifier: '복사 식별자',
  backupStrategy: '백업 전략',
  backupDatabaseNameLabel: '데이터베이스 이름',
  volumeNameCol: '볼륨 이름',
  backupInformation: '백업 정보',
  backupHistoryInformation: '백업 수행 이력',
  backupLevel: '백업 수준',
  backupDate: '최종 백업일',
  backupSizeColumn: '크기(Mbyte)',
  backupPath: '백업 경로',
  backupHistoryListHint: '백업 수행 이력 리스트',
  checkDatabaseConsistency: '데이터베이스 일관성 검사',
  deleteArchivedLogs: '불필요한 보관(archive)로그 파일을 지움',
  compressBackupVolume: '압축 백업 사용',
  safeBackup: '복제를 위한 안전 백업',
  parallelThreads: '병렬 스레드',
  dynamicCompaction: '동적 공간 정리',
  compactDatabaseName: '데이터베이스 이름',
  compactDatabaseMessage: '데이터베이스 최적화를 수행합니다.',
  compactDescriptionInformation: '설명',
  compactDatabaseDescription: '이 기능은 두 가지 방법으로 데이터베이스 볼륨 공간을 정리합니다.\n\n  -지워진 객체의 OID 제거\n  -스키마가 변경된(ALTER TABLE) 데이터의 변경 내용 반영',
  maintenanceTarget: '대상 데이터베이스',
  compactionFailed: '공간 정리 실패',
  performanceTuning: '성능 튜닝',
  noMatches: '일치 항목 없음',
  optimizationScope: '최적화 범위',
  provisionVolume: '볼륨 추가',
  autoVolume: '자동 볼륨',
  triggerThreshold: '임계값',
  dataVolume: '데이터 볼륨',
  dataIndexVolume: '데이터 + 인덱스 볼륨',
  dataIndexVolumeDescription: '데이터 및 인덱스 볼륨',
  autoVolumeEnabled: '자동 볼륨 켜짐',
  autoVolumeDisabled: '자동 볼륨 꺼짐',
  createBackupPlan: '백업 자동화 추가',
  editBackupPlan: '백업 자동화 편집',
  executionSchedule: '실행 일정',
  concurrentThreads: '동시 스레드',
  addQueryPlan: '질의 자동화 추가',
  editQueryPlan: '질의 자동화 편집',
  connectionInformation: '연결 정보',
  standardParameters: '표준 매개변수',
  syncingConfiguration: '설정 동기화 중',
  noPlanData: '플랜 데이터 없음',
  configuration: '설정',
  autoBackupLog: '백업 자동화 수행로그',
  autoVolumeLog: '볼륨 자동 추가 로그',
  autoQueryLog: '질의 자동화 수행로그',
  filterLogs: '로그 필터...',
  auditHistoryFor: (db) => `감사 기록: ${db}`,
  noLog: '로그 없음',

  yes: '예',
  no: '아니오',
  ready: '준비됨',
  active: '활성',
  options: '옵션',
  locks: '잠금',
  size: '크기',
  regionLocale: '지역 로케일',
  noSessions: '세션 없음',
  noActiveTransactions: '활성 트랜잭션이 없습니다.',
  noObjectLocks: '객체 잠금 없음',
  noHeldObjectLocks: '보유된 객체 잠금이 없습니다.',
  failedToGetLockInfo: '잠금 정보를 가져오지 못했습니다.',
  leaveBlankNoPassword: '비밀번호 없음은 비워 두세요',
  repeatPassword: '비밀번호 확인',
  addVolume: '볼륨 추가',
  clickAddVolumeHint: '"볼륨 추가"를 클릭하여 추가 스토리지 세그먼트를 할당하세요.',
  identifier: '식별자',
  segment: '세그먼트',
  sizeMb: '크기(MB)',
  absolutePath: '절대 경로',
  autoStart: '자동 시작',
  totalVolumes: '전체 볼륨',
  genericVolume: '일반 볼륨',
  logVolume: '로그 볼륨',
  volumeTypeData: '데이터',
  volumeTypeIndex: '인덱스',
  volumeTypeTemp: '임시',
  operationInterrupted: '작업 중단됨',
  operationFailed: '작업 실패',
  operationComplete: '작업 완료',
  transactionDropped: '트랜잭션 중단됨',
  copyCompleted: '복사 완료',
  snapshotInProgress: '백업 진행 중',
  snapshotSecured: '백업 완료',
  backupSubtitle: '데이터베이스 백업을 수행합니다',
  storageConfiguration: '백업 정보',
  revisionId: '백업 레벨',
  backupDirectory: '백업 디렉터리',
  backupDirFetchError: '기본 백업 디렉터리를 조회하지 못했습니다. 경로를 직접 입력하세요.',
  restoringDatabase: '데이터베이스 복구 중',
  reconstructingInstance: '데이터베이스 복구 중',
  restoreCompleted: '복구 완료',
  recoveryFailed: '복구 실패',
  restoreSubtitle: '백업된 데이터베이스를 복구합니다',
  databaseMustBeStopped: '복구 전에 데이터베이스를 중지해야 합니다',
  targetInstance: '대상 데이터베이스',
  snapshotCatalog: '백업 정보',
  scanningCatalog: '백업 정보를 불러오는 중…',
  restoreOptions: '복구 옵션',
  applyIntermediateLogs: '아카이브 로그가 없으면 강제로 부분 복구 수행',
  pathOverride: '복구 경로 지정',
  restoreInPlaceHint: '비워 두면 원래 위치로 복구',
  renamingDatabase: '데이터베이스 이름 변경 중',
  updatingIdentity: '식별자 업데이트 중',
  renameComplete: '이름 변경 완료',
  renameSuccessful: '이름 변경 성공',
  renameFailed: '이름 변경 실패',
  executeRename: '이름 변경 실행',
  retryRename: '이름 변경 재시도',
  sourceDatabase: '원본 데이터베이스',
  currentIdentifier: '현재 이름',
  targetIdentifier: '새 이름',
  destructiveOptions: '옵션',
  overwriteExistingTarget: '기존 대상 덮어쓰기',
  overwriteTargetDesc: '대상 경로가 이미 있으면 강제 삭제',
  overwriteTargetWarning: '마이그레이션 시작 전 대상 경로의 기존 디렉터리가 영구 삭제됩니다.',
  renameDowntimeHint: '이름 변경 전 데이터베이스 서비스를 완전히 중지하세요.',
  synchronizingVolumes: '데이터베이스 복사 중',
  cloningComplete: '복사 완료',
  cloningFailed: '복사 실패',
  cloneSubtitle: '데이터베이스를 복사합니다',
  cloningContext: '복사 정보',
  targetEnvironment: '대상 경로',
  executionStrategy: '복사 옵션',
  overwriteExistingEnvironment: '기존 데이터 덮어쓰기',
  transformToMove: '이동으로 변환',
  executeCopy: '복사',
  consolidatingBlocks: '공간 정리 중',
  optimizationComplete: '최적화 완료',
  optimizationPipeline: '최적화 정보',
  executionOptions: '옵션',
  executeCompaction: '공간 정리',
  retryOptimization: '최적화 재시도',
  verboseMonitoring: '상세 모니터링',
  verboseMonitoringDesc: 'OID 변환 정보 로그 출력',
  executingHeuristics: '최적화 중',
  executionInterrupted: '실행 중단',
  performanceTuningSubtitle: '쿼리 실행 계획을 최적화합니다',
  optimizerIntel: '옵티마이저',
  targetInstanceSection: '대상 데이터베이스',
  applyChanges: '변경 적용',
  updateSuccessful: '갱신 성공',
  configurationReIndexed: '설정 완료',
  updateRejected: '갱신 실패',
  synchronizationHalted: '동기화 중단',
  updatingRegistry: '설정 갱신 중',
  syncingRegistrySubtitle: '서버 설정(cubrid.conf)을 갱신합니다.',
  navigation: '탐색',
  context: '컨텍스트',
  loadingLabel: '로딩',
  queryingHostRegistry: '설정 불러오는 중…',
  brokerConnection: '브로커 연결',
  brokerIp: '브로커 IP',
  publicAddress: '공개 주소',
  servicePort: '서비스 포트',
  activeBroker: '활성 브로커',
  textEncoding: '텍스트 인코딩',
  charset: '문자 집합',
  synchronizationNotice: '동기화 안내',
  brokerParamsNotice: '브로커 매개변수는 Web Manager가 CUBRID Broker와 통신하는 방식을 정의합니다. 변경은 Manager-호스트 동기화에만 영향을 줍니다.',
  lockingSection: '잠금',
  transactionSection: '트랜잭션',
  systemSection: '시스템',
  advancedHeuristics: '고급 휴리스틱',
  databaseProperties: '데이터베이스 속성',
  initializingSchedule: '초기화 중',
  committingAutomation: '저장 중',
  scheduleCommitted: '저장됨',
  automationActive: '활성',
  executionError: '실행 오류',
  initializeCycle: '저장',
  abstractionLevel: '유형',
  planRegistryId: '계획 ID',
  payloadPath: '경로',
  rotationLogic: '로테이션',
  targetTime: '대상 시간',
  standard24hCycle: '매일 (24시간 주기)',
  registryDate: '등록일',
  optimizationMatrix: '최적화',
  rotationRetention: '보존',
  deleteBackupPlan: '백업 자동화 삭제',
  deleteQueryPlan: '질의 자동화 삭제',
  deletingQueryPlan: '질의 자동화 삭제 중',
  removingRegistry: '삭제 중',
  deletionSuccess: '삭제 성공',
  registryPurged: '질의 자동화 삭제됨',
  queryPlanRemovedMsg: '질의 자동화가 삭제되었습니다.',
  deletionFailed: '삭제 실패',
  signalRejected: '삭제 실패',
  deletionSignalFailed: '질의 자동화 삭제에 실패했습니다.',
  retryDeletion: '삭제 재시도',
  dangerousDiscardQueryPlan: '질의 자동화 삭제',
  permanentRemovalSql: 'SQL 자동화 항목을 삭제합니다',
  executeDiscard: '삭제',
  discardQueryStrategy: '질의 자동화를 삭제하시겠습니까?',
  planRetirement: '질의 자동화 삭제',
  planCacheDumpTitle: '플랜 캐시 덤프',
  loadingParameters: '매개변수 로딩 중',
  parameter: '매개변수',
  serverValue: '서버 값',
  clientValue: '클라이언트 값',
  failedToGetDbParams: '데이터베이스 매개변수를 가져오지 못했습니다.',
  message: '메시지',
  activeContext: '활성 컨텍스트',
  offlineStatic: '오프라인 정적',
  noConfigParameters: '이 인스턴스에 대한 설정 매개변수가 없습니다.',
  parameterDumpSubtitle: '매개변수 값을 확인합니다',
  environmentReady: '준비됨',
  analysisPipeline: '분석',
  comparativeAnalysis: '비교 분석',
  comparativeAnalysisDesc: '클라이언트/서버 값 모두 추출',
  loadingBrokerStatus: '브로커 상태 로딩 중…',
  basicInformation: '기본 정보',
  lastAccess: '마지막 접근',
  clientIp: '클라이언트 IP',
  jobId: '작업 ID',
  priority: '우선순위',
  elapsed: '경과',
  request: '요청',
  activeCount: (n) => `${n}개 활성`,
  queuedCount: (n) => `${n}개 대기`,
  downloadAllLogs: '로드된 모든 로그를 단일 파일로 다운로드',
  setAutomationVolume: '볼륨 자동 추가 설정',
  addStorageVolume: '스토리지 볼륨 추가',
  editBackupPlanTitle: '백업 자동화 편집',
  deleteBackupPlanTitle: '백업 자동화 삭제',
  runBackup: '백업 실행',
  retryBackup: '백업 재시도',
  backupCompleted: '백업 완료',
  backupFailed: '백업 실패',
  targetDatabase: '대상 데이터베이스',
  executeRestore: '복구 실행',
  retryRecovery: '복구 재시도',
  restoreSuccessful: '복구 성공',
  initiateCopy: '복사 시작',
  retryClone: '복사 재시도',
  executeOptimization: '최적화 실행',
  retryExecution: '실행 재시도',
  volumeAllocation: '볼륨 추가',
  scalingFoundation: '볼륨 추가 중',
  allocationSuccessful: '볼륨 추가 성공',
  storageExpanded: '볼륨 추가 완료',
  allocationInterrupted: '볼륨 추가 오류',
  scalingFailed: '볼륨 추가 실패',
  storageOptimization: '데이터베이스 최적화',
  allocationStrategy: '볼륨 정보',
  instanceRegistry: '데이터베이스',
  privilegedOperation: '주의',
  addVolumeNote: '볼륨을 추가하려면 데이터베이스가 실행 중이어야 합니다. 볼륨 경로에 쓰기 권한이 있는지 확인하세요.',
  extendDiskCapacity: (db) => `${db} 볼륨 추가`,
  historyForDatabase: (db) => `데이터베이스 기록: ${db}`,
  globalBackupHistory: '전역 백업 기록',
  dumpingPlanCache: '플랜 캐시 덤프 중',
  displayQueryPlan: '질의 수행 계획 표시',
  dumpingPlanCacheSubtitle: '서버에서 XASL 플랜 캐시 읽는 중...',
  runDumpHint: '덤프를 실행하여 쿼리 플랜 캐시 항목을 확인하세요.',
  backupId: '백업 ID',
  logTime: '로그 시간',
  description: '설명',

  actionMenu: '주요 작업',
  configParam: '설정 매개변수',
  editCmConfig: 'CM 설정 편집',
  reportBug: '버그 보고',
  cubridOnlineForum: 'CUBRID 온라인 포럼',
  cubridToolsDevelopment: 'CUBRID 도구 개발',
  checkForUpdates: '업데이트 확인',

  globalHealthOverview: '전역 상태 개요',
  hostsLabel: '호스트',
  activeLabel: '활성',
  unknownHost: '알 수 없는 호스트',
  localhost: '로컬호스트',
  statusOn: '켜짐',
  statusOff: '꺼짐',
  synchronizingServices: '서비스 동기화 중',
  stopServices: '서비스 중지',
  startServicesConfirmTitle: '서비스 시작',
  startServicesConfirmDesc: (server) => `호스트 "${server}"의 모든 CUBRID 서비스를 시작하시겠습니까?`,
  stopServicesConfirmTitle: '서비스 중지',
  stopServicesConfirmDesc: (server) =>
    `호스트 "${server}"의 모든 CUBRID 서비스를 중지하시겠습니까? 활성 브로커와 데이터베이스가 모두 종료됩니다.`,
  startingServicesOn: (server) => `${server}에서 서비스 시작 중`,
  stoppingServicesOn: (server) => `${server}에서 서비스 중지 중`,
  serviceStartRejected: '호스트 에이전트가 서비스 시작 명령을 거부했습니다.',
  serviceStopFailed: '서비스 종료에 실패했습니다. 에이전트 로그를 확인하세요.',
  connectHostForMonitoring: '탐색기에서 호스트 서버에 연결하면 전역 리소스 모니터링이 활성화됩니다.',
  permanentTemp: '영구 임시',
  tempTemp: '임시',
  userLabel: '사용자',
  haMaster: '마스터',
  haSlave: '슬레이브',
  haReplica: '레플리카',
  clusterOverview: '클러스터 개요',

  databaseDashboard: '데이터베이스 대시보드',
  refreshDatabaseStatus: '데이터베이스 상태 새로 고침',
  exportMetricsCsv: '지표를 CSV로 내보내기',
  restartingCas: 'CAS 재시작 중',
  resettingCasProcess: '브로커 애플리케이션 서버 프로세스 재설정 중',
  loadingDashboard: '대시보드 로딩 중…',
  restartCasConfirm: (cas, broker) => `브로커 ${broker}의 CAS ID ${cas}를 재시작하시겠습니까?`,

  performanceMetrics: '성능 지표',
  realTime: '실시간',
  transPerSec: '트랜잭션/초',
  queriesPerSec: '쿼리/초',
  bufferHit: '버퍼 히트',
  fetchesPerSec: 'Fetch/초',
  dirtyPerSec: 'Dirty/초',
  ioReadsPerSec: 'IO 읽기/초',
  ioWritesPerSec: 'IO 쓰기/초',
  storageVolumes: '스토리지 볼륨',
  volumeLabel: '볼륨',
  purpose: '용도',
  spaceUsage: '공간 사용량',
  modifiedLabel: '수정일',
  pathLabel: '경로',
  fileDistribution: '파일 분포',
  logicalPartitioning: '논리적 파티셔닝',
  filesLabel: '파일',
  usedLabel: '사용',
  fileTable: '파일 테이블',
  reservedLabel: '예약',
  totalLabel: '합계',
  casBrokers: 'CAS 브로커',
  readyCount: (n) => `${n}개 준비`,
  busyCount: (n) => `${n}개 사용 중`,
  lastConn: '마지막 연결',
  sqlLogs: 'SQL 로그',
  slowQueryLogs: '느린 쿼리 로그',
  restartCasTitle: 'CAS 재시작',
  lockMode: '잠금 모드',
  activeLog: '활성 로그',
  archiveLog: '아카이브 로그',
  longTran: '장기 트랜',
  longQuery: '장기 쿼리',
  errQuery: '오류 쿼리',
  reqLabel: 'REQ',
  jqLabel: 'JQ',
  asLabel: 'AS',

  systemStatus: '시스템 상태',
  nowLabel: '현재',
  fiveMinAvg: '5분 평균',
  resume: '재개',
  haClusterStatus: 'HA 클러스터 상태',
  nodesActiveInCluster: (n) => `클러스터에 ${n}개 노드 활성`,
  environmentUnavailable: '환경 정보를 사용할 수 없습니다',

  language: '언어',
  languageEn: 'English',
  languageKo: '한국어',

  // Backup dialog options (aligned with CUBRID Admin)
  backupLevelFullTitle: '전체 백업',
  backupLevelFullDesc: '전체 데이터를 완전 백업합니다',
  backupLevelIncrL1Title: '증분 백업 (L1)',
  backupLevelIncrDesc: '마지막 L0 백업 이후 변경 내용',
  backupLevelIncrL2Title: '증분 백업 (L2)',
  backupLevelDiffDesc: '마지막 L1 백업 이후 변경 내용',
  checkConsistencyLabel: '데이터베이스 일관성 검사',
  checkConsistencyDesc: '백업 중 데이터베이스 일관성을 검사합니다',
  deleteArchiveLogsLabel: '불필요한 아카이브 로그 삭제',
  deleteArchiveLogsDesc: '이미 보관된 트랜잭션 로그를 삭제합니다',
  compressBackupLabel: '백업 볼륨 압축',
  compressBackupDesc: '백업 파일 크기를 압축합니다',
  parallelBackupDesc: '병렬 백업 스레드 수',
  threadsLabel: '스레드',

  // Compact database steps
  compactStep1Label: '참조 정리',
  compactStep1Desc: '사용하지 않는 객체 참조를 제거합니다',
  compactStep2Label: '메타데이터 정리',
  compactStep2Desc: '내부 메타데이터를 정리합니다',
  compactStep3Label: '디스크 통합',
  compactStep3Desc: '조각화된 디스크 페이지를 통합합니다',

  // Optimize database
  allTables: '전체 테이블',
  filterObjects: '테이블 필터...',
  regeneratingStatistics: '통계 갱신 중',
  optimizationSuccess: '최적화 완료',
  optimizationFailed: '최적화 실패',
  optimizerHint: '통계 갱신을 통해 쿼리 옵티마이저가 최적의 실행 경로를 선택할 수 있습니다.',
  globalScanHint: '전체 스캔 시 스키마 메타데이터가 일시적으로 잠길 수 있습니다.',

  // Copy database path labels
  primaryVolumePath: '데이터베이스 볼륨 경로',
  extVolumePath: '확장 볼륨 경로',
  logVolumePath: '로그 볼륨 경로',
  replaceExistingDesc: '동일한 이름의 데이터베이스가 이미 있으면 덮어씁니다.',
  moveSourceDesc: '복사 완료 후 원본 파일을 삭제합니다.',

  // Query plan modals (Add/Edit)
  queryIdentifierRequired: '질의 자동화 ID가 필요합니다.',
  sqlStatementRequired: 'SQL 구문을 입력해야 합니다.',
  queryPlanAdded: '질의 자동화 추가 완료',
  addQueryPlanFailed: '질의 자동화 추가 실패',
  editQueryPlanFailed: '질의 자동화 수정 실패',
  objectIdentification: '식별',
  queryIdentifierLabel: '질의 ID',
  secureContextSection: '데이터베이스 자격 증명',
  databaseUsernameLabel: '사용자 이름',
  databasePasswordLabel: '비밀번호',
  recurrenceFrequency: '주기',
  startTimeLabel: '시간',
  dailyLabel: '매일',
  weeklyLabel: '매주',
  monthlyLabel: '매월',
  specificDateLabel: '특정 날짜',
  sqlStatementSection: 'SQL 구문',
  systemComplianceNote: '질의는 서버 측에서 실행됩니다. 데이터베이스 사용자에게 충분한 권한이 있어야 합니다.',
  runSchedule: '저장',
  automatingDatabase: '자동화 대상 데이터베이스',

  // Backup plan level descs (short)
  levelFullShortDesc: '전체 백업',
  levelIncrL0ShortDesc: 'L0 기준',
  levelIncrL1ShortDesc: 'L1 기준',

  // Backup plan option labels
  updateStatisticsLabel: '통계 정보 갱신',
  updateStatisticsDesc: '질의 최적화기 통계 정보를 갱신합니다',
  deleteArchiveDesc: '이미 보관된 트랜잭션 로그를 삭제합니다',

  // Backup plan schedule options
  monthly: '매월',
  weekly: '매주',
  daily: '매일',
  specificDays: '특정 날짜',
  onlineMode: '온라인',
  onlineModeDesc: '데이터베이스 실행 중 백업',
  offlineMode: '오프라인',
  offlineModeDesc: '데이터베이스 중지 후 백업',
  savingSchedule: '저장 중',
  updatingSchedule: '수정 중',

  // Delete backup plan modal
  deletingBackupPlan: '백업 자동화 삭제 중',
  backupPlanDeleted: '백업 자동화 삭제됨',
  backupPlanRemovedMsg: '백업 자동화가 스케줄러에서 삭제되었습니다.',
  deleteBackupPlanFailed: '백업 자동화 삭제 실패',
  discardBackupStrategy: '백업 자동화를 삭제하시겠습니까?',
  backupScheduleNote: '이 작업은 스케줄만 삭제합니다. 디스크의 기존 백업 파일은 유지됩니다.',
  dangerousDiscardBackupPlan: '백업 자동화 삭제',
  permanentRemovalBackup: '백업 자동화를 영구 삭제합니다',

  // SetAutomationVolumeModal
  savingPolicies: '저장 중',
  policiesSaved: '저장됨',
  savedSuccessfully: '저장 성공',
  saveInterrupted: '저장 실패',
  savePolicies: '저장',
  expansionSize: '확장 크기 (MB)',
  extensionPages: '확장 페이지 수',
  autoVolumeActive: '볼륨 자동화 활성',
  loadingConfig: '설정 불러오는 중...',
  indexVolume: '인덱스 볼륨',

  // AddVolumeModal
  retryAddVolume: '다시 시도',
  activeInstanceRequired: '데이터베이스가 실행 중이어야 합니다',
  availableSpace: '여유 공간',
  customCapacity: '볼륨 크기 (MB)',
  blocksAllocated: '페이지 수',
  volumeIdentifier: '볼륨 이름',
  volumeDir: '볼륨 경로',
  addVolumeTargetDb: '대상 데이터베이스',
  calculating: '계산 중',
  volumeSizeVisualizer: '볼륨 크기',
  addVolumeSuccessMessage: (volName, db) => `볼륨 "${volName}"이(가) ${db}에 성공적으로 추가되었습니다.`,
  volumeTypeDataDesc: '테이블, 행 데이터',
  volumeTypeTempDesc: '임시 작업 공간',

  // RestoreDatabaseModal
  logCatchup: '부분 복구',
  noBackupFound: '백업 정보 없음',
  noBackupHint: '백업 디렉터리가 설정되어 있고 호스트와 동기화되어 있는지 확인하세요.',
  showAllBackups: '전체 보기',
  irreversibleOperation: '되돌릴 수 없는 작업',
  restoreOverwriteNote: '선택한 백업으로 기존 볼륨이 영구적으로 덮어씌워집니다.',
  selectBackupFirst: '복구할 백업을 선택해 주십시오.',
  restoreErrorFallback: '복구 중 예기치 않은 오류가 발생했습니다.',
  tryOtherBackupLevel: '다른 백업 레벨을 선택하거나 전체를 보십시오.',
  recoveryPathPlaceholder: '기본값: 원래 위치',
  backupLevelFullLongDesc: '모든 데이터, 스키마, 볼륨의 전체 스냅샷입니다.',
  backupLevelIncrL1LongDesc: '마지막 L0 백업 이후 변경 내용입니다. 복구 시 L0이 필요합니다.',
  backupLevelIncrL2LongDesc: '마지막 L1 백업 이후 변경 내용입니다. 복구 시 L0 + L1이 필요합니다.',

  // Auth
  pickUniqueUsername: '고유한 사용자 이름을 입력하세요',
  createStrongPassword: '강력한 비밀번호를 만드세요',
  repeatPassword: '비밀번호를 다시 입력하세요',
  emailAddressLabel: '이메일 주소',

  // Sidebar context menus
  newGroup: '새 그룹',
  addNode: '호스트 추가',
  renameGroup: '그룹 이름 변경',
  deleteGroup: '그룹 삭제',
  viewAllLogs: '전체 로그 보기',
  viewDatabase: '데이터베이스 보기',

  // Host modals
  loginIdLabel: '로그인 ID',
  statusAuthorityLabel: '권한 상태',
  administratorAccount: '관리자 계정',
  groupNameLabel: '그룹 이름',
  hostPasswordPlaceholder: '호스트 비밀번호',
  haClusterLinked: 'HA 클러스터 연결됨',
  mergeHAPeers: 'HA 클러스터 노드 병합',

  // User modals
  moveToGroups: '그룹으로 이동',
  removeFromAssigned: '할당 해제',
  departmentLabel: '부서',
  currentPasswordLabel: '현재 비밀번호',
  confirmNewPassword: '새 비밀번호 확인',
  dropDatabaseUser: '데이터베이스 사용자 삭제',
  droppingUser: '삭제 중',
  userDropped: '삭제됨',
  dropUserConfirmSection: '삭제 확인',
  dropUserWarning: '이 작업은 되돌릴 수 없습니다.',
  dropUserBtn: '사용자 삭제',

  // DeleteDatabaseModal
  deletingDatabase: '삭제 중',
  deleteSuccessful: '삭제 성공',
  authorizationPointTitle: '인증',
  targetSelection: '대상 선택',
  recoveryCleanup: '복구 파일 정리',
  purgeLinkedBackups: '연결된 백업 삭제',
  purgeLinkedBackupsDesc: '이 데이터베이스에 연결된 모든 백업 볼륨과 스냅샷을 삭제합니다.',
  fetchingAssets: '불러오는 중...',
  noVolumesDetected: '볼륨 없음',
  proceedBtn: '계속',
  backBtn: '뒤로',

  // VolumeInfoMonitor
  loadingVolumeInfo: '볼륨 정보 불러오는 중',
  loadingVolumeInfoSub: '볼륨 할당 데이터를 가져오는 중...',
  volumeNotFound: '볼륨을 찾을 수 없음',

  // Log modals
  filterLogsById: 'ID 또는 설명으로 필터',
  buffering: '버퍼링 중',
  synchronizedStatus: '동기화됨',

  // Monitoring / misc
  monitoringSync: '모니터링 동기화',
  customIntervalPlaceholder: '사용자 지정 간격',
  defaultValuePlaceholder: '기본값',

  // Config editors
  undoAllChanges: '모든 변경 사항 되돌리기',
  brokerConfigPlaceholder: '# 여기에 브로커 설정을 입력하세요...',

  // EditCMSUserModal
  savingChanges: '저장 중',
  creatingUser: '생성 중',
  accountInformation: '계정 정보',
  allowDatabaseCreation: '데이터베이스 생성 허용',
  allowDbCreationDesc: '이 호스트에서 데이터베이스를 생성하고 삭제할 수 있습니다',

  // CreateUserModal
  createUser: '사용자 생성',
  userUpdated: '사용자 업데이트됨',
  userCreated: '사용자 생성됨',

  // UserProfileModal
  accountDetails: '계정 정보',
  updateProfileSection: '프로필 업데이트',
  accountProfile: '계정 프로필',
  editProfile: '프로필 편집',
  updatePasswordBtn: '비밀번호 업데이트',
  securitySettings: '보안 설정',

  // DatabasePropertyModal
  confirmReturn: '확인 후 돌아가기',
  retryPatch: '패치 재시도',
  discardChanges: '변경 사항 취소',

  // HaPeerMergeModal / HostGroupNameModal
  mergeIntoGroup: '그룹으로 병합',
  createGroup: '그룹 생성',

  // CMSUserManagementModal
  systemAdministrator: '시스템 관리자',
  managementUsers: '관리 사용자',

  // Monitor refresh buttons
  refreshVolumeData: '볼륨 데이터 새로 고침',
  refreshCategoryMetrics: '카테고리 지표 새로 고침',
  refreshSpaceMetrics: '공간 지표 새로 고침',

  // DatabaseSpaceMonitor
  storageAnalysisError: '스토리지 분석 오류',

  // CreateDatabaseModal
  removeVolume: '볼륨 제거',
  storage: '스토리지',

  // ConfigSourceEditor
  source: '소스',

  // Auth pages
  recoverPassword: '비밀번호 복구',
  linkExpiry: '링크 만료',
  registrationFailedTitle: '회원가입 실패',
  desktopOnly: '데스크톱 전용',
  desktopBridgeUnavailable: '데스크톱 브리지를 사용할 수 없음',

  // CAS Log Viewer
  casSqlTransactionLog: 'CAS SQL 로그 조회',
  casSlowQueryRegistry: 'CAS SLOW Query 로그 조회',
  broker: '브로커',
  casUid: 'CAS UID',
  noLogData: '로그 데이터 없음',
  logStreamEmptyMsg: '요청한 로그 스트림이 현재 비어 있거나 브로커 프로세스에 의해 초기화되지 않았습니다.',
  logResolveError: (suffix) => `현재 브로커 디렉토리에서 로그 파일 식별자 [${suffix}]를 확인할 수 없습니다.`,
  logRetrievalRefused: '원격 호스트가 로그 조회 요청을 거부했습니다. 브로커 연결을 확인하십시오.',

  // Broker Config
  fetchFailed: '가져오기 실패',
  brokerConfigRetrieveError: '브로커 구성을 가져올 수 없습니다.',
  configSaved: '설정 저장됨',
  brokerConfigSaveSuccess: '브로커 구성이 성공적으로 업데이트되었습니다.',
  saveFailed: '저장 실패',
  brokerConfigSaveError: '브로커 구성을 저장하는 동안 오류가 발생했습니다.',
  initializingEditor: '에디터 초기화 중...',
  brokerConfig: '브로커 구성',
  brokerConfiguration: '브로커 설정',
  modified: '수정됨',
  commentsPreserved: '소스 보기에서 주석이 보존됩니다',
  linesLabel: (count) => `${count} 줄`,

  // Node Group Tree
  addNodeToGroup: '그룹에 호스트 추가',

  // Auth pages
  forgotLink: '비밀번호를 잊으셨나요?',
  newToCubrid: 'CUBRID가 처음이신가요?',
  workspaceSettings: '워크스페이스 설정',
  website: '웹사이트',
  github: 'GitHub',
  atLeast6Chars: '최소 6자 이상',
  confirmPasswordRequired: '비밀번호를 확인하십시오',
  weakPassword: '약함',
  averagePassword: '보통',
  goodPassword: '좋음',
  strongPassword: '강함',
  architecture: '아키텍처',
  license: '라이선스',
  engine: '엔진',
  security: '보안',
  passwordsMatch: '비밀번호 일치',
  alreadyHaveAccount: '이미 계정이 있으신가요?',
  agreeTermsPrefix: '계정을 생성하면 CUBRID 오픈 소스 ',
  projectTerms: '프로젝트 약관',
  agreeTermsSuffix: ' 및 데이터 정책에 동의하는 것으로 간주됩니다.',

  // 사이드바 — 호스트 트리 비어있는 상태 / 로그인 상태
  addFirstHostTitle: '첫 번째 호스트 추가',
  addFirstHostMsg: 'CUBRID 서버에 연결',
  hostLoginTitle: '호스트 로그인',
  establishingSession: '보안 세션을 설정하는 중...',
  connectionFailed: '연결 실패',
  tryAgain: '다시 시도',
  allBrokers: '모든 브로커',
  brokerLogs: '브로커 로그',
  errorLogs: '오류 로그',
  adminLogs: '관리자 로그',
  managerLogs: '매니저 로그',
  serverLogs: '서버 로그',
  backupPlanLabel: '백업 계획',
  indexEmpty: '인덱스 없음',
  noDatabasesAvailable: '사용 가능한 데이터베이스 없음',

  // 데이터베이스 공간 모니터
  databaseLabel: '데이터베이스',
  usedLabel: '사용됨',
  freeLabel: '여유',
  headroomAvailable: '여유 공간',
  usageLabel: '사용량',
  volumeCategorization: '볼륨 분류',
  physicalVolumeTopology: '물리 볼륨 구성',
  fileSpaceUsage: '파일 공간 사용량',
  distributionLabel: '분포',

  // 볼륨 정보 모니터
  volumeInfo: '볼륨 정보',
  volumeHealth: '볼륨 상태',
  mbPhysical: 'MB 물리',
  mbAvailable: 'MB 사용 가능',
  utilizationLabel: '사용률',

  // 볼륨 카테고리 모니터
  capacityLabel: '용량',
  overallUtilization: '전체 사용률',

  // 트랜잭션 정보 모달
  queryTime: '쿼리 시간',
  tranTime: '트랜잭션 시간',
  waitHolder: '대기 홀더',

  // 언로드 결과 모달
  classLabel: '클래스',
  resultLabel: '결과',

  // 자동화 볼륨 설정 모달
  targetDatabase: '대상 데이터베이스',

  // 데이터베이스 플랜 덤프 모달
  selectedInstance: '선택된 인스턴스',
  xaslCache: 'XASL 캐시',
  flushCacheAfterExport: '내보내기 후 캐시 초기화',
  clearsXaslEntries: '서버 메모리에서 XASL 항목을 지웁니다',

  // CMS 사용자 관리 모달
  fullSystemAuthorization: '전체 시스템 권한',
  addManagementUser: '관리 사용자 추가',

  // 호스트 비밀번호 변경 모달
  passcodeUpdated: '패스코드 업데이트됨',
  targetHost: '대상 호스트',

  // 호스트 삭제 모달
  impactSummary: '영향 요약',

  // 호스트 가져오기/내보내기 모달
  filenameLabel: '파일명:',
  duplicateLabel: '중복',
  invalidLabel: '유효하지 않음',

  // CUBRID 설정 편집기
  loadingConfiguration: '설정 로드 중...',

  // 데이터베이스 대시보드 레거시
  databasesLabel: '데이터베이스',

  // 사용자 생성 모달
  availableLabel: '사용 가능',
  noIdentities: '아이덴티티 없음',
  groupsLabel: '그룹',
  dropGroupsHere: '여기에 그룹 놓기',
  membersLabel: '멤버',
  dropMembersHere: '여기에 멤버 놓기',
  loadingLabel: '로딩 중...',
  noObjects: '객체 없음',
  accessMaskConfig: '접근 마스크 설정',
  dmlLabel: 'DML',
  ddlLabel: 'DDL',
  grantDelegation: '권한 위임',
  selectAnObject: '객체 선택',

  // 모니터링 설정 팝오버
  globalHeartbeat: '전역 하트비트',
  resourceDashboard: '리소스 대시보드',
  syncDbThroughputMsg: '데이터베이스 처리량 및 디스크 IO 지연 시간을 동기화합니다.',
  brokerInfrastructure: '브로커 인프라',
  propagatesConnectionMsg: '연결 풀 상태 및 쿼리 부하 분산을 전파합니다.',
  sessionPreferences: '세션 환경설정',

  // 사용자 프로필 모달
  userIdLabel: '사용자 계정',
  departmentLabel: '부서',
  lockedLabel: '잠김',

  // 브로커 속성 모달
  resetLabel: '초기화',
  applyLabel: '적용',
  runtimeConfiguration: '런타임 구성',
  deployingChanges: '변경 사항 배포 중',
  updateSynchronized: '업데이트 완료',

  // 브로커 상태
  basicInformation: '기본 정보',
  applicationServers: '응용 프로그램 서버 (AS)',
  jobQueue: '작업 대기열',

  // CMS 로그 뷰어
  loadingManagerLogs: '관리자 로그 로딩 중...',
  managerSystemActivity: '관리자 시스템 활동',
  copiedLabel: '복사됨',
  timeLabel: '시간',
  userLabel: '사용자',
  taskLabel: '작업',
  noLogEntriesFound: '이 범주에 대한 로그 항목이 없습니다.',
  errLabel: '오류',
  successLabel: '성공',
  showingAllRecords: '전체 레코드 표시',

  // 로그 뷰어 (브로커)
  brokerLogViewer: '브로커 로그 뷰어',
  noContentAvailable: '이 범위에 사용 가능한 내용이 없습니다.',
  noSqlStatementsFound: '이 페이지에서 SQL 구문을 찾을 수 없습니다.',
  maxSeconds: '최대 (초)',
  avgSeconds: '평균 (초)',
  countLabel: '횟수',
  errorsLabel: '오류',
  sqlPattern: 'SQL 패턴',
  noQueriesToAnalyze: '분석할 쿼리가 없습니다.',

  // 전체 로그 뷰어
  loadingLogLines: '로그 행 로딩 중...',
  noContentAvailableShort: '사용 가능한 내용이 없습니다',
  scanningForLogFiles: '로그 파일 검색 중...',
  noLogFilesFound: '로그 파일 없음',
  noLogFilesFoundMsg: '이 리소스에 대한 로그 파일을 찾을 수 없습니다.',

  // 데이터베이스 계획 덤프 모달
  flushCacheAfterExport2: '내보내기 후 캐시 지우기',
  clearsXaslEntries2: '서버 메모리에서 XASL 항목 제거',

  // 가져오기/내보내기 호스트 모달
  importedPlaceholder: '가져옴',

  // CMS 사용자 관리 모달
  addManagementUserBtn: '관리자 계정 추가',

  // 데이터베이스 공간 모니터
  freeBadge: '여유',

  // 비밀번호 찾기 페이지
  forgotPasswordLabel: '비밀번호 찾기',
  backToLogin: '로그인으로 돌아가기',
  backToSignIn: '로그인으로 돌아가기',
  enterpriseSuite: '엔터프라이즈 데이터베이스 제품군',
  resetAccessCredentials: '접속 자격 증명 재설정',
  securityProtocol: '보안 프로토콜',
  recoveryLabel: '비밀번호 찾기',
  emailPlaceholder: 'admin@organization.com',
  sendRecoveryLink: '재설정 링크 전송',
  linkSent: '링크 전송됨',
  checkInbox: '수신함을 확인하세요',
  rememberPasswordQuestion: '비밀번호가 생각나셨나요?',
  enterEmailInstruction: '계정 복구 프로세스를 시작하려면 등록된 이메일 주소를 입력하십시오.',
  recoverySecurityDesc: '계정 복구는 데이터베이스 클러스터링과 동일한 기업 수준의 보안으로 처리됩니다. 계정 복구를 도와드리겠습니다.',
  recoveryProtocolDesc: '새 마스터 비밀번호 생성을 승인할 수 있는 일회성 암호화 링크를 받게 됩니다. 링크는 15분 후에 만료됩니다.',
  submitEmailStep: '등록된 이메일 주소 입력',
  checkInboxStep: '수신함에서 복구 링크 확인',
  setNewPasswordStep: '새로운 보안 비밀번호 설정',
  securityInfrastructure: 'CUBRID 매니저 보안 인프라',
  recoveryInstructionsSent: '복구 지침이 다음 이메일로 전송되었습니다:',
  checkSpamMsg: '링크는 15분 후에 만료됩니다. 메일이 오지 않으면 스팸 메일함을 확인해 주세요.',
  resendRecoveryEmail: '복구 이메일 재전송',
  serverListHeader: '서버 목록',
  resourcesHeader: '리소스',

  // CMSUserManagementModal
  managementAccountsRegistered: (count) => `${count}개의 관리자 계정이 등록되었습니다.`,
  confirmDeleteCmsUser: (username) => `관리자 계정 "${username}"을(를) 영구히 삭제하시겠습니까?`,
  synchronizingRegistry: '설정을 동기화하는 중...',
  noUsersFound: '등록된 사용자가 없습니다',
  managementRegistryEmpty: '관리자 설정이 비어 있거나 액세스할 수 없습니다.',

  // EditCMSUserModal & ChangeHostPasswordModal
  updatePasscode: '암호 변경',
  passcodeChangedSuccessMsg: (host) => `${host}의 관리자 암호 변경을 성공적으로 완료하였습니다.`,
  passcodeUpdateNote: '이 작업은 이 연결에 대해 로컬에 저장된 관리자 접속 암호를 업데이트합니다.',
  userUpdatedSuccessMsg: (username) => `사용자 @${username}이(가) 성공적으로 수정되었습니다.`,
  userCreatedSuccessMsg: (username) => `사용자 @${username}이(가) 성공적으로 생성되었습니다.`,
  synchronizationFailed: '동기화에 실패했습니다.',
  savingChanges: '변경 사항 저장 중',
  creatingUser: '사용자 생성 중',
  updating: '업데이트 중...',
  creating: '생성 중...',
  editingUser: (username) => `@${username} 편집 중`,
  createManagementAccount: '새 관리자 계정 생성',
  primaryAdminNotice: '기본 시스템 관리자 계정입니다. 시스템 수준 권한은 고정되어 있으며 수정할 수 없습니다.',
  operationCompletedSuccess: '작업이 성공적으로 완료되었습니다.',
  operationCouldNotBeCompleted: '작업을 완료할 수 없습니다.',
  viewAll: '전체 보기',
  paginated: '페이지별 보기',
};

